/-
Copyright 2026 Hyphaeic SPC.

Licensed under the Hyphaeic Public License, Version 1.0 (the
"License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

https://github.com/hyphaeic/hpl

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.

# Filtration Formalism

This file formalizes the σ-algebras generated by cylinder sets at each depth,
forming a filtration.

## References

- fdrs.md, Phase 1 Fragment 3
- σ-algebras ℱ_L generated by length-L cylinders
- Monotone nesting: ℱ_1 ⊆ ℱ_2 ⊆ ℱ_3 ⊆ ...
- Connection to Borel σ-algebra

## Status

SCAFFOLDING ONLY - proofs not yet attempted
-/

import FdrsFormal.Core.Infinite
import FdrsFormal.Topology.Ultrametric
import FdrsFormal.Topology.Compactness
import Mathlib.MeasureTheory.MeasurableSpace.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.Topology.Bases

namespace FdrsFormal.Topology.Filtration

open FdrsFormal.Core.Primitives FdrsFormal.Core.Finite FdrsFormal.Core.Infinite
open FdrsFormal.Topology.Ultrametric FdrsFormal.Topology.Compactness

/-! ## Definition 17: Filtration of σ-algebras

**fdrs.md**: Definition 17 (filtration of σ-algebras) [§1.3 · Phase 2, Fragment 1] (lines 565-573)

The cylinder sets at each depth L generate a σ-algebra ℱ_L, forming a filtration.
-/

/--
**fdrs.md**: Definition 17 (filtration of σ-algebras) [§1.3 · Phase 2, Fragment 1] (lines 565-573)

σ-algebra generated by length-L cylinders: ℱ_L := σ({U(s) : s ∈ Σ_L}).
Then ℱ_1 ⊆ ℱ_2 ⊆ ... is an increasing filtration.
-/
def cylinderAlgebra (b : RadixSeq) (L : ℕ) :
    MeasurableSpace (CompletedSpace b) :=
  MeasurableSpace.generateFrom {S | ∃ s : (i : Fin L) → Fin (b i), S = cylinder b L s}

notation "ℱ_" L => cylinderAlgebra _ L

/-- **Monotone nesting**: ℱ_L ⊆ ℱ_{L+1}
The key insight is that each L-level cylinder is a union of (L+1)-level cylinders. -/
theorem filtration_monotone (b : RadixSeq) (L : ℕ) :
    cylinderAlgebra b L ≤ cylinderAlgebra b (L + 1) := by
  -- Each L-cylinder is a union of (L+1)-cylinders, hence measurable in ℱ_{L+1}
  apply MeasurableSpace.generateFrom_le
  intro S hS
  obtain ⟨s, rfl⟩ := hS
  -- cylinder b L s = ⋃ d, cylinder b (L+1) (extend s d)
  -- Need to show this cylinder is measurable in the (L+1) σ-algebra
  -- This is a countable (actually finite) union of generating sets
  have h : cylinder b L s = ⋃ d : Fin (b L), cylinder b (L + 1) (Fin.snoc s d) := by
    ext x
    simp only [Set.mem_iUnion, cylinder, Set.mem_setOf_eq]
    constructor
    · intro hx
      use x L
      intro i
      rcases Fin.eq_castSucc_or_eq_last i with ⟨j, rfl⟩ | rfl
      · simp only [Fin.snoc_castSucc]
        exact hx j
      · simp only [Fin.snoc_last, Fin.val_last]
    · intro ⟨d, hd⟩ i
      have := hd (Fin.castSucc i)
      simp only [Fin.snoc_castSucc] at this
      exact this
  rw [h]
  apply MeasurableSet.iUnion
  intro d
  exact MeasurableSpace.measurableSet_generateFrom ⟨Fin.snoc s d, rfl⟩

/--
**General monotonicity**: ℱ_L ⊆ ℱ_M for L ≤ M.

This extends filtration_monotone to arbitrary gaps, not just successive levels.
-/
theorem filtration_monotone_of_le (b : RadixSeq) (L M : ℕ) (hLM : L ≤ M) :
    cylinderAlgebra b L ≤ cylinderAlgebra b M := by
  -- Prove by induction on the gap M - L
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hLM
  clear hLM
  induction k with
  | zero =>
    -- L = M: reflexivity
    simp
  | succ k ih =>
    -- L ≤ L+k ≤ L+k+1: transitivity
    calc cylinderAlgebra b L
        ≤ cylinderAlgebra b (L + k) := ih
      _ ≤ cylinderAlgebra b (L + k + 1) := filtration_monotone b (L + k)

/-- **Every cylinder is measurable in its own level** -/
theorem cylinder_measurable (b : RadixSeq) (L : ℕ)
    (s : (i : Fin L) → Fin (b i)) :
    @MeasurableSet (CompletedSpace b) (cylinderAlgebra b L) (cylinder b L s) :=
  MeasurableSpace.measurableSet_generateFrom ⟨s, rfl⟩

/-- **Cylinders form a topological basis** for the ultrametric topology.

The key insight is that closed balls = cylinders (closedBall_eq_cylinder), and in
a metric space, closed balls of arbitrarily small radius exist around each point. -/
theorem cylinder_isTopologicalBasis (b : RadixSeq) :
    TopologicalSpace.IsTopologicalBasis
      {S : Set (CompletedSpace b) | ∃ L : ℕ, ∃ s : (i : Fin L) → Fin (b i), S = cylinder b L s} := by
  refine TopologicalSpace.isTopologicalBasis_of_isOpen_of_nhds ?_ ?_
  · -- All cylinders are open
    intro S hS
    obtain ⟨L, s, rfl⟩ := hS
    exact (cylinder_isClopen L s).isOpen
  · -- Every open neighborhood contains a cylinder
    intro x U hxU hU
    -- Since U is open, ∃ ε > 0 such that ball(x, ε) ⊆ U
    rw [Metric.isOpen_iff] at hU
    obtain ⟨ε, hε_pos, hε_ball⟩ := hU x hxU
    -- Find L such that B_L^{-1} < ε
    have h_arch : ∃ L, (placeValue b L : ℝ)⁻¹ < ε := by
      obtain ⟨L, hL⟩ := Compactness.placeValue_unbounded b (Nat.ceil ε⁻¹)
      use L
      have h_pos_L : (0 : ℝ) < placeValue b L := Nat.cast_pos.mpr (placeValue.pos L)
      rw [inv_lt_comm₀ h_pos_L hε_pos]
      calc ε⁻¹ ≤ Nat.ceil ε⁻¹ := Nat.le_ceil _
        _ < placeValue b L := Nat.cast_lt.mpr hL
    obtain ⟨L, hL⟩ := h_arch
    -- The cylinder containing x at level L is inside U
    let s : (i : Fin L) → Fin (b i) := fun i => x i
    refine ⟨cylinder b L s, ⟨L, s, rfl⟩, ?_, ?_⟩
    · -- x ∈ cylinder b L s
      intro i
      rfl
    · -- cylinder b L s ⊆ U
      intro y hy
      apply hε_ball
      -- y ∈ cylinder b L s means y agrees with x on first L coordinates
      -- So dist(x, y) ≤ B_L^{-1} < ε
      have h_agree : ∀ i < L, x i = y i := fun i hi => (hy ⟨i, hi⟩).symm
      rw [Metric.mem_ball, dist_comm]
      calc dist x y = ultrametricDist b x y := rfl
        _ ≤ (placeValue b L : ℝ)⁻¹ := by
          rw [ultrametricDist_le_placeValue_inv_iff]
          by_cases heq : x = y
          · left; exact heq
          · right
            -- firstDiff ≥ L since they agree on first L positions
            by_contra h_not
            push_neg at h_not
            have h_lt : firstDiff b x y < L := h_not
            have h_diff := firstDiff_spec heq
            exact h_diff (h_agree (firstDiff b x y) h_lt)
        _ < ε := hL

/-- CompletedSpace is separable (has a countable dense subset) -/
instance completed_space_separableSpace (b : RadixSeq) :
    TopologicalSpace.SeparableSpace (CompletedSpace b) := by
  haveI := direct_limit_countable b
  exact ⟨⟨Set.range (DirectLimitSpace.embed b),
    Set.countable_range _,
    direct_limit_dense_in_completed b⟩⟩

/-- CompletedSpace is second countable -/
instance completed_space_secondCountableTopology (b : RadixSeq) :
    SecondCountableTopology (CompletedSpace b) :=
  UniformSpace.secondCountable_of_separable (CompletedSpace b)

/-- **The full σ-algebra is the limit of the filtration**

The supremum of all cylinderAlgebra b L equals the Borel σ-algebra on CompletedSpace b.
This follows because:
1. Cylinders form a basis for the topology
2. The σ-algebra generated by a topological basis equals the Borel σ-algebra -/
theorem filtration_generates_borel (b : RadixSeq) :
    ⨆ L, cylinderAlgebra b L = borel (CompletedSpace b) := by
  apply le_antisymm
  · -- ⨆ L, cylinderAlgebra b L ≤ borel
    apply iSup_le
    intro L
    apply MeasurableSpace.generateFrom_le
    intro S hS
    obtain ⟨s, rfl⟩ := hS
    exact MeasurableSpace.measurableSet_generateFrom (cylinder_isClopen L s).isOpen
  · -- borel ≤ ⨆ L, cylinderAlgebra b L
    -- Use: cylinders form a topological basis (cylinder_isTopologicalBasis)
    -- And: basis generates Borel σ-algebra (IsTopologicalBasis.borel_eq_generateFrom)
    rw [(cylinder_isTopologicalBasis b).borel_eq_generateFrom]
    apply MeasurableSpace.generateFrom_le
    intro S hS
    obtain ⟨L, s, rfl⟩ := hS
    -- cylinder b L s is in cylinderAlgebra b L, hence in ⨆ L, cylinderAlgebra b L
    exact le_iSup (cylinderAlgebra b) L _ (cylinder_measurable b L s)

/-- Cylinders generate the Borel σ-algebra directly -/
theorem cylinder_generateFrom_eq_borel (b : RadixSeq) :
    MeasurableSpace.generateFrom
      {S | ∃ L : ℕ, ∃ s : (i : Fin L) → Fin (b i), S = cylinder b L s} =
      borel (CompletedSpace b) := by
  apply le_antisymm
  · -- generateFrom(cylinders) ≤ borel
    -- Each cylinder is clopen, hence Borel measurable
    apply MeasurableSpace.generateFrom_le
    intro S hS
    obtain ⟨L, s, rfl⟩ := hS
    exact MeasurableSpace.measurableSet_generateFrom (cylinder_isClopen L s).isOpen
  · -- borel ≤ generateFrom(cylinders)
    -- Use cylinder_isTopologicalBasis and borel_eq_generateFrom
    -- The generating sets are identical, so the rewrite closes the goal
    rw [(cylinder_isTopologicalBasis b).borel_eq_generateFrom]

end FdrsFormal.Topology.Filtration
