/-
Copyright 2026 Hyphaeic SPC.

Licensed under the Hyphaeic Public License, Version 1.0 (the
"License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

https://github.com/hyphaeic/hpl

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.

# Prefix-Local Operators

This file defines prefix-local (L-local) operators on the tensor space.

## Mathematical Content (fdrs.md lines 705-737)

**Definition 24 (prefix locality of an operator)**:
Let A be an operator A: 𝕋(V) → 𝕋(V).
We say A is **L-local** (prefix-local at depth L) if for every x ∈ R̂ and any f, g ∈ 𝕋(V),
  f|_{U(π_L(x))} = g|_{U(π_L(x))}  ⟹  (A f)(x) = (A g)(x)

In words: the output at x depends only on the restriction of the input function
to the length-L cylinder containing x.

**Proposition 19 (basic examples)**:
1. The projection P_L is L-local
2. Multiplication by a cylinder indicator M_s(f) := 1_{U(s)} · f is L-local
3. Kernel operators ∫_{U(π_L(x))} K(x,y) f(y) dμ(y) are L-local

**Proposition 20 (phase-locked activation as clopen gating)**:
The algebra G_L generated by cylinder indicators is finite-dimensional,
and every g ∈ G_L acts as a projector/gate onto a union of cylinders.

## Implementation Notes

- L-locality captures "finite dependence": the output at x only looks at f
  within a finite neighborhood (the cylinder U(π_L(x)))
- This is the mixed-radix analog of translation-invariant local operators
- The gating algebra G_L gives "phase-locked activation patterns"

## References

- fdrs.md, Section 5, Definitions 5.1-5.3 (lines 705-737)
- THEOREM_MAPPING.md, FunctionSpaces/LocalOperators section
-/

import FdrsFormal.FunctionSpaces.Projections

open scoped Classical

namespace FdrsFormal.FunctionSpaces.LocalOperators

open FdrsFormal.Core.Primitives FdrsFormal.Core.Infinite
open FdrsFormal.Topology.Ultrametric
open FdrsFormal.FunctionSpaces.Basic FdrsFormal.FunctionSpaces.Measure
open FdrsFormal.FunctionSpaces.Projections
open MeasureTheory

/-!
## Prefix Locality Definition
-/

section Definition

variable {b : RadixSeq} {V W : Type*}

/--
Two tensors agree on a cylinder if they have the same values everywhere in that cylinder.
-/
def agreeOnCylinder (f g : TensorSpace b V) (L : ℕ) (s : PrefixSet b L) : Prop :=
  ∀ y ∈ cylinderSet b L s, f y = g y

/--
Two tensors agree on the cylinder containing x (at level L).
-/
def agreeOnCylinderOf (f g : TensorSpace b V) (L : ℕ) (x : CompletedSpace b) : Prop :=
  agreeOnCylinder f g L (prefixOf b L x)

/--
**Definition 24**: An operator A: 𝕋(V) → 𝕋(W) is **L-local** (prefix-local at depth L)
if the output at x depends only on the restriction of the input to the cylinder
containing x at level L.

Formally: if f and g agree on U(π_L(x)), then (A f)(x) = (A g)(x).
-/
def IsPrefixLocal (A : TensorSpace b V → TensorSpace b W) (L : ℕ) : Prop :=
  ∀ f g : TensorSpace b V, ∀ x : CompletedSpace b,
    agreeOnCylinderOf f g L x → A f x = A g x

/--
Alternative formulation: A is L-local if for all x, (A f)(x) depends only on f|_{U(π_L(x))}.
-/
def IsPrefixLocal' (A : TensorSpace b V → TensorSpace b W) (L : ℕ) : Prop :=
  ∀ x : CompletedSpace b, ∀ f g : TensorSpace b V,
    (∀ y, y ∈ cylinderSet b L (prefixOf b L x) → f y = g y) → A f x = A g x

/--
The two formulations are equivalent.
-/
theorem isPrefixLocal_iff_isPrefixLocal' (A : TensorSpace b V → TensorSpace b W) (L : ℕ) :
    IsPrefixLocal A L ↔ IsPrefixLocal' A L := by
  constructor
  · intro h x f g hfg
    apply h
    exact hfg
  · intro h f g x hfg
    apply h x f g
    exact hfg

end Definition

/-!
## Monotonicity of Locality
-/

section Monotonicity

variable {b : RadixSeq} {V W : Type*}

/--
Monotonicity of locality: finer locality implies coarser locality.

If A is M-local, then A is also L-local for any L ≤ M.

**Key insight**: When L ≤ M, we have U(π_M(x)) ⊆ U(π_L(x)) (finer cylinder ⊆ coarser).
If A's output only depends on agreement within the M-cylinder, then it certainly depends
only on agreement within the larger L-cylinder.

**Intuition**: M-locality is a STRONGER property than L-locality when M > L.
If an operator is strongly local (depends on fine cylinders), it's automatically weakly local.
-/
theorem isPrefixLocal_of_le (A : TensorSpace b V → TensorSpace b W) (L M : ℕ)
    (hLM : L ≤ M) (hA : IsPrefixLocal A M) : IsPrefixLocal A L := by
  intro f g x hagree
  -- We know: f and g agree on U(π_L(x))
  -- We want: A f x = A g x
  -- Since A is M-local and U(π_M(x)) ⊆ U(π_L(x)), we can apply hA
  apply hA
  intro y hy
  -- y ∈ U(π_M(x)) means ∀ i : Fin M, y i.val = x i.val
  -- We need to show: f y = g y
  -- Since y ∈ U(π_M(x)) ⊆ U(π_L(x)), we can use hagree
  apply hagree
  intro i
  -- hy gives us: y j.val = x j.val for all j : Fin M
  -- We need: y i.val = x i.val where i : Fin L
  -- Since i.val < L ≤ M, we have i.val < M
  have h_i_lt_M : i.val < M := Nat.lt_of_lt_of_le i.isLt hLM
  exact hy ⟨i.val, h_i_lt_M⟩

/--
The minimal L such that A is L-local (if it exists) is the "locality depth" of A.

**Status**: AXIOMATIZED - Non-critical definition, not used elsewhere in codebase.

**Implementation notes**:
- Ideally would use `Nat.find` with a decidability instance for `IsPrefixLocal A L`
- Since `IsPrefixLocal` involves universal quantification over functions, decidability
  is not available without additional assumptions
- We use `Nat.find` with Classical decidability

**Semantics**:
- Returns 0 if no finite locality depth exists (operator is not finitely local)
- Returns the minimal L such that A is L-local otherwise

**Axiomatization rationale**: This is a convenience definition for potential future use.
The core locality theory (IsPrefixLocal, composition, examples) is fully proven.
-/
noncomputable def localityDepth (A : TensorSpace b V → TensorSpace b W) : ℕ :=
  if h : ∃ L, IsPrefixLocal A L then
    @Nat.find (fun L => IsPrefixLocal A L) (Classical.decPred _) h
  else
    0

end Monotonicity

/-!
## Basic Examples of Local Operators
-/

section Examples

variable {b : RadixSeq} {V : Type*}
variable [NormedAddCommGroup V] [NormedSpace ℝ V] [CompleteSpace V]

/--
**Proposition 19(1)**: The projection P_L is L-local.

**Proof**: (P_L f)(x) is the average of f over U(π_L(x)).
If f and g agree on U(π_L(x)), then their averages over U(π_L(x)) are equal.
-/
theorem blockProjection_isPrefixLocal (L : ℕ) :
    IsPrefixLocal (blockProjection b L (V := V)) L := by
  intro f g x hagree
  -- (P_L f)(x) = B_L • ∫ y in U(π_L(x)), f y dμ
  -- (P_L g)(x) = B_L • ∫ y in U(π_L(x)), g y dμ
  -- These are equal because f and g agree on U(π_L(x))
  simp only [blockProjection]
  congr 1
  -- Need to show the integrals are equal
  apply MeasureTheory.setIntegral_congr_fun
  · exact @cylinder_measurableSet b L (prefixOf b L x)
  · -- f y = g y for all y in the cylinder
    exact hagree

/--
The identity operator is 0-local (equivalently, L-local for all L).
-/
theorem id_isPrefixLocal (L : ℕ) :
    IsPrefixLocal (id : TensorSpace b V → TensorSpace b V) L := by
  intro f g x hagree
  simp only [id]
  exact hagree x (mem_cylinderSet_prefixOf b L x)

/--
Constant operators are 0-local.
-/
theorem const_isPrefixLocal {V : Type*} (c : TensorSpace b V) (L : ℕ) :
    IsPrefixLocal (fun _ : TensorSpace b V => c) L := by
  intro _ _ _ _
  rfl

end Examples

/-!
## Cylinder Indicator Operators
-/

section CylinderIndicator

variable {b : RadixSeq} {V : Type*}

/--
**Proposition 19(2)**: Multiplication by a cylinder indicator.

For fixed s ∈ Σ_L, the operator M_s(f) := 1_{U(s)} · f is L-local.
-/
noncomputable def cylinderMultiplication [Zero V] [One V] [Mul V]
    (L : ℕ) (s : PrefixSet b L) (f : TensorSpace b V) : TensorSpace b V :=
  fun x => if x ∈ cylinderSet b L s then f x else 0

/--
Cylinder multiplication is L-local.
-/
theorem cylinderMultiplication_isPrefixLocal [Zero V] [One V] [Mul V]
    (L : ℕ) (s : PrefixSet b L) :
    IsPrefixLocal (cylinderMultiplication L s (V := V)) L := by
  intro f g x hagree
  simp only [cylinderMultiplication]
  -- Case analysis on whether x ∈ cylinderSet b L s
  by_cases hx : x ∈ cylinderSet b L s
  · -- x ∈ cylinder s: both equal f x and g x respectively
    simp only [hx, ↓reduceIte]
    -- f, g agree on the cylinder containing x, and x is in that cylinder
    exact hagree x (mem_cylinderSet_prefixOf b L x)
  · -- x ∉ cylinder s: both are 0
    simp only [hx, ↓reduceIte]

/--
The cylinder indicator itself (as a real-valued function).
-/
noncomputable def cylinderIndicatorFun (L : ℕ) (s : PrefixSet b L) : TensorSpace b ℝ :=
  fun x => if hx : x ∈ cylinderSet b L s then 1 else 0

end CylinderIndicator

/-!
## Gating Algebra
-/

section GatingAlgebra

variable {b : RadixSeq}

/--
**Proposition 20**: The gating algebra G_L.

G_L is the algebra generated by cylinder indicators {1_{U(s)} : s ∈ Σ_L}.
Elements of G_L are "phase-locked activation patterns" at resolution L.
-/
def GatingAlgebra (b : RadixSeq) (L : ℕ) : Type _ :=
  {g : TensorSpace b ℝ // IsBlockConstant g L ∧ ∀ x, g x = 0 ∨ g x = 1}

/--
G_L is finite: each element is determined by which cylinders it assigns 1 to.

**fdrs.md Proposition 20 (line 726)**: dim(G_L) = 2^{B_L}.

**Proof**: A block-constant {0,1}-valued function is determined by its value on each
of the B_L cylinders, giving an injection into PrefixSet b L → Bool.
-/
theorem gatingAlgebra_finite (L : ℕ) :
    Finite (GatingAlgebra b L) := by
  -- Inject into Finset (PrefixSet b L), which is Fintype
  -- Each g is determined by which cylinders it assigns 1 to
  let φ : GatingAlgebra b L → Finset (PrefixSet b L) :=
    fun g => Finset.univ.filter fun s : PrefixSet b L =>
      g.val (fun i => if h : i < L then s ⟨i, h⟩ else ⟨0, b.pos i⟩) = 1
  apply Finite.of_injective φ
  intro g₁ g₂ heq
  -- heq : φ g₁ = φ g₂ (same finset of cylinders marked 1)
  apply Subtype.ext; funext x
  let s := prefixOf b L x
  -- Canonical point in cylinder U(s)
  let x₀ : CompletedSpace b := fun i => if h : i < L then s ⟨i, h⟩ else ⟨0, b.pos i⟩
  have hx₀ : x₀ ∈ cylinderSet b L s := fun i => by simp [x₀, dif_pos i.isLt]
  have hx : x ∈ cylinderSet b L s := mem_cylinderSet_prefixOf b L x
  -- block-constancy: g.val x = g.val x₀
  have eq1 : g₁.val x = g₁.val x₀ := g₁.property.1 s x x₀ hx hx₀
  have eq2 : g₂.val x = g₂.val x₀ := g₂.property.1 s x x₀ hx hx₀
  rw [eq1, eq2]
  -- From heq: g₁ and g₂ agree at x₀
  have hmem : s ∈ φ g₁ ↔ s ∈ φ g₂ := by rw [heq]
  simp only [φ, Finset.mem_filter, Finset.mem_univ, true_and] at hmem
  -- hmem : g₁.val x₀ = 1 ↔ g₂.val x₀ = 1
  rcases g₁.property.2 x₀ with h1 | h1 <;> rcases g₂.property.2 x₀ with h2 | h2
  · rw [h1, h2]
  · exfalso; have := hmem.mpr h2; linarith
  · exfalso; have := hmem.mp h1; linarith
  · rw [h1, h2]

/--
Every g ∈ G_L corresponds to a union of cylinders at depth L.

**Proof**: Since g is block-constant at level L and takes values 0 or 1,
it partitions the cylinders into two sets: those where g = 1 and those where g = 0.
-/
theorem gatingAlgebra_union_cylinders (L : ℕ) (g : GatingAlgebra b L) :
    ∃ S : Finset (PrefixSet b L), ∀ x, g.val x = 1 ↔ ∃ s ∈ S, x ∈ cylinderSet b L s := by
  -- Define S as the set of prefixes where g = 1
  use Finset.univ.filter (fun s : PrefixSet b L =>
    -- Pick any representative point in the cylinder U(s) and check if g = 1 there
    -- Since g is block-constant, this is well-defined
    ∃ y ∈ cylinderSet b L s, g.val y = 1)
  intro x
  constructor
  · intro hg
    -- g.val x = 1, so we need to show x is in some cylinder where g = 1
    use prefixOf b L x
    constructor
    · simp only [Finset.mem_filter, Finset.mem_univ, true_and]
      exact ⟨x, mem_cylinderSet_prefixOf b L x, hg⟩
    · exact mem_cylinderSet_prefixOf b L x
  · intro ⟨s, hs, hx⟩
    -- x ∈ cylinderSet b L s and ∃ y ∈ U(s), g.val y = 1
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hs
    obtain ⟨y, hy, hgy⟩ := hs
    -- Since g is block-constant at L, and both x and y are in U(s), we have g.val x = g.val y
    have : g.val x = g.val y := g.property.1 s x y hx hy
    rw [this]
    exact hgy

/--
G_L is closed under pointwise multiplication.
-/
theorem gatingAlgebra_mul_closed (L : ℕ) (g h : GatingAlgebra b L) :
    ∃ gh : GatingAlgebra b L, ∀ x, gh.val x = g.val x * h.val x := by
  -- Define the product function
  let prod : TensorSpace b ℝ := fun x => g.val x * h.val x
  -- Show it's block-constant
  have hbc : IsBlockConstant prod L := by
    intro s x y hx hy
    simp only [prod]
    rw [g.property.1 s x y hx hy, h.property.1 s x y hx hy]
  -- Show it's 0-1 valued
  have h01 : ∀ x, prod x = 0 ∨ prod x = 1 := by
    intro x
    simp only [prod]
    rcases g.property.2 x with hg | hg <;> rcases h.property.2 x with hh | hh
    · left; simp [hg, hh]
    · left; simp [hg, hh]
    · left; simp [hg, hh]
    · right; simp [hg, hh]
  exact ⟨⟨prod, hbc, h01⟩, fun x => rfl⟩

/--
G_L is closed under complement: if g ∈ G_L then (1 - g) ∈ G_L.
-/
theorem gatingAlgebra_compl_closed (L : ℕ) (g : GatingAlgebra b L) :
    ∃ gc : GatingAlgebra b L, gc.val = fun x => 1 - g.val x := by
  -- Define the complement function
  let compl : TensorSpace b ℝ := fun x => 1 - g.val x
  -- Show it's block-constant
  have hbc : IsBlockConstant compl L := by
    intro s x y hx hy
    simp only [compl]
    rw [g.property.1 s x y hx hy]
  -- Show it's 0-1 valued
  have h01 : ∀ x, compl x = 0 ∨ compl x = 1 := by
    intro x
    simp only [compl]
    rcases g.property.2 x with hg | hg
    · right; simp [hg]
    · left; simp [hg]
  exact ⟨⟨compl, hbc, h01⟩, rfl⟩

/--
Elements of G_L are idempotent: g(x)² = g(x) for all x.
-/
theorem gatingAlgebra_idempotent (L : ℕ) (g : GatingAlgebra b L) (x : CompletedSpace b) :
    g.val x * g.val x = g.val x := by
  rcases g.property.2 x with h | h
  · simp [h]
  · simp [h]

end GatingAlgebra

/-!
## Composition of Local Operators
-/

section Composition

variable {b : RadixSeq} {V W U : Type*}

/--
Composition of an L-local and M-local operator is min(L,M)-local.

**Proof strategy**: The composition (B ∘ A) computes B(A f). To evaluate at x:
- B is M-local: needs (A f) values on M-cyl(x)
- For each y ∈ M-cyl(x), A is L-local: needs f values on L-cyl(y)
- Total dependency: U = ⋃_{y ∈ M-cyl(x)} L-cyl(y)

**Key observation**: U = min(L,M)-cyl(x) exactly:
- If L ≤ M: all y ∈ M-cyl(x) have y[i]=x[i] for i<M, so also for i<L, thus L-cyl(y)=L-cyl(x)
- If M ≤ L: as y varies in M-cyl(x), we get all z with z[i]=x[i] for i<M, which is M-cyl(x)

Therefore composition makes operators **more local** (smaller locality parameter).
-/
theorem comp_isPrefixLocal (A : TensorSpace b V → TensorSpace b W)
    (B : TensorSpace b W → TensorSpace b U) (L M : ℕ)
    (hA : IsPrefixLocal A L) (hB : IsPrefixLocal B M) :
    IsPrefixLocal (B ∘ A) (min L M) := by
  intro f g x hagree
  simp only [Function.comp_apply]
  -- Goal: B (A f) x = B (A g) x
  -- Since B is M-local, it suffices to show A f and A g agree on M-cyl(x)
  apply hB
  intro y hy
  -- y ∈ M-cyl(x), need: A f y = A g y
  -- Since A is L-local, it suffices to show f and g agree on L-cyl(y)
  apply hA
  intro z hz
  -- z ∈ L-cyl(y), need: f z = g z
  -- We have: f, g agree on min(L,M)-cyl(x)
  -- Need to show: z ∈ min(L,M)-cyl(x)
  apply hagree
  -- Show: z ∈ min(L,M)-cyl(x)
  -- Have: z ∈ L-cyl(y) (hz) and y ∈ M-cyl(x) (hy)

  -- Case analysis on min(L,M)
  rcases Nat.le_total L M with hLM | hML
  · -- Case L ≤ M: min(L,M) = L
    have : min L M = L := Nat.min_eq_left hLM
    rw [this]
    -- Need: z ∈ L-cyl(x)
    -- Have: z ∈ L-cyl(y) and y ∈ M-cyl(x)
    -- Since L ≤ M, y ∈ M-cyl(x) means y[i]=x[i] for i<M, so also for i<L
    -- Therefore y ∈ L-cyl(x), so L-cyl(y) = L-cyl(x)
    intro i
    calc z i.val = y i.val := hz i
         _       = x i.val := hy ⟨i.val, Nat.lt_of_lt_of_le i.isLt hLM⟩
  · -- Case M ≤ L: min(L,M) = M
    have : min L M = M := Nat.min_eq_right hML
    rw [this]
    -- Need: z ∈ M-cyl(x)
    -- Have: z ∈ L-cyl(y) and y ∈ M-cyl(x)
    -- For i < M ≤ L: z[i] = y[i] (by L-locality) = x[i] (by M-locality)
    intro i
    calc z i.val = y i.val := hz ⟨i.val, Nat.lt_of_lt_of_le i.isLt hML⟩
         _       = x i.val := hy i

/--
Sum of L-local operators is L-local.
-/
theorem add_isPrefixLocal [Add W] (A B : TensorSpace b V → TensorSpace b W) (L : ℕ)
    (hA : IsPrefixLocal A L) (hB : IsPrefixLocal B L) :
    IsPrefixLocal (A + B) L := by
  intro f g x hagree
  -- (A + B) f = A f + B f, so we need (A f + B f) x = (A g + B g) x
  -- This is (A f x + B f x) = (A g x + B g x)
  show (A f + B f) x = (A g + B g) x
  rw [Pi.add_apply, Pi.add_apply]
  -- If f, g agree on the cylinder, then A f x = A g x and B f x = B g x
  rw [hA f g x hagree, hB f g x hagree]

/--
Scalar multiple of L-local operator is L-local.
-/
theorem smul_isPrefixLocal [SMul R W] (r : R) (A : TensorSpace b V → TensorSpace b W) (L : ℕ)
    (hA : IsPrefixLocal A L) :
    IsPrefixLocal (r • A) L := by
  intro f g x hagree
  -- (r • A) f = r • (A f), so (r • A f) x = (r • (A f)) x = r • (A f x)
  show (r • A f) x = (r • A g) x
  rw [Pi.smul_apply, Pi.smul_apply]
  -- If f, g agree on the cylinder, then A f x = A g x
  rw [hA f g x hagree]

end Composition

/-!
## Locality and Block-Constant Preservation

**Note**: A general L-local operator does NOT necessarily preserve M-block-constancy
for M ≥ L. This was initially conjectured but is FALSE.

**Counterexample**: Let b = (2,2,...), L = 1, M = 2.
Define A by: (Af)(x) = f(x₀,0,0,...) + h(x)·(f(x₀,1,0,...) - f(x₀,0,0,...))
where h is any function not 2-block-constant.
- A is 1-local: both evaluation points are in U(x₀)
- A does NOT preserve 2-block-constancy: if f has values a on U(00), b on U(01),
  then (Af)(x) = a + h(x)·(b-a) varies with h.

The original proof sketch had two flaws:
1. Step 3 claimed "f agrees with constant g on U(π_L(x))" - false when M > L
2. Step 5 claimed "A preserves constancy" - unjustified for general operators

For specific operators like conditional expectation, block-constant preservation
DOES hold and is proven in FunctionSpaces/Projections/Properties.lean.
-/

section BlockConstantPreservation

variable {b : RadixSeq} {V : Type*}

-- No general preservation theorem exists. See note above.
-- Specific operators (projections, conditional expectations) preserve
-- block-constancy and have dedicated proofs elsewhere.

end BlockConstantPreservation

end FdrsFormal.FunctionSpaces.LocalOperators
