/-
Copyright 2026 Hyphaeic SPC.

Licensed under the Hyphaeic Public License, Version 1.0 (the
"License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

https://github.com/hyphaeic/hpl

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.

# Residual Payload as Junction Accumulation

This file characterizes residual payload in routed systems.

## Mathematical Content (fdrs.md lines 6447-6458)

**Theorem 57 (Residual payload as junction accumulation)**:

In a routed observer complex, the residual payload from A to B is:
  payload_{A → B}(t) = ∑_{(A, s_A, B, s_B) ∈ 𝒥} undelivered(A, s_A, t)

where undelivered(A, s_A, t) is residue at A-to-B junction s_A not yet processed by B.

**Proof**: Payload exists when A generates overflow but injection queue at B
hasn't processed it yet. Sum over all A-to-B junctions gives total undelivered.

**Interpretation**: Residual is precisely "in-flight" information between timelines.

## References

- fdrs.md, Phase 8, Section 8.9 (lines 6447-6458)
-/

import FdrsFormal.Composition.ObserverIntegration.RoutedObserver
import FdrsFormal.Composition.Injection.Queue
import FdrsFormal.Composition.Verification.Specification

namespace FdrsFormal.Composition.ObserverIntegration

open Injection
open FdrsFormal.Composition.Verification

/-!
## Residual Payload Characterization
-/

/--
Undelivered residue at an A→B junction at time `t`.

**fdrs.md line 6451**: residue generated by A at cylinder `s_A` but not yet
processed by B. Parametric in the junction-queue state `residue`, which reports
the outstanding residue at junction `(sourceTimeline, sourceCylinder) →
targetTimeline` at time `t`.
-/
def undeliveredResidue (residue : ℕ → ℕ → ℕ → ℕ → ℕ)
    (sourceTimeline sourceCylinder targetTimeline time : ℕ) : ℕ :=
  residue sourceTimeline sourceCylinder targetTimeline time

/-- The A→B junctions of `G_ρ`: routing rules from timeline `A` to timeline `B`. -/
def aToBJunctions (spec : RoutingSpecification) (sourceTimeline targetTimeline : ℕ) :
    List RoutingRule :=
  spec.rules.filter (fun r =>
    decide (r.sourceTimeline = sourceTimeline ∧ r.targetTimeline = targetTimeline))

/--
Total in-flight payload from A to B at time `t` — Theorem 57's right-hand side:
the accumulation of undelivered residue over all A→B junctions.
-/
def residualPayload (spec : RoutingSpecification) (residue : ℕ → ℕ → ℕ → ℕ → ℕ)
    (sourceTimeline targetTimeline time : ℕ) : ℕ :=
  ((aToBJunctions spec sourceTimeline targetTimeline).map
    (fun r => undeliveredResidue residue r.sourceTimeline r.sourceCylinder
      r.targetTimeline time)).sum

/--
**fdrs.md**: Theorem 57 (Residual payload as junction accumulation) [§8.9 · Phase 8] (lines 6448-6456)

The residual payload from A to B is exactly the accumulation of undelivered
residue over all A→B junctions:
  `payload_{A→B}(t) = Σ_{(A,s_A,B,s_B) ∈ 𝒥} undelivered(A, s_A, t)`.

Payload exists precisely when A has overflowed to B but B's injection queue has
not yet processed it; summing over all A→B junctions gives the total in flight.
-/
theorem residualPayload_as_junction_sum (spec : RoutingSpecification)
    (residue : ℕ → ℕ → ℕ → ℕ → ℕ) (sourceTimeline targetTimeline time : ℕ) :
    residualPayload spec residue sourceTimeline targetTimeline time
      = ((aToBJunctions spec sourceTimeline targetTimeline).map
          (fun r => undeliveredResidue residue r.sourceTimeline r.sourceCylinder
            r.targetTimeline time)).sum :=
  rfl

/--
Residual represents in-flight information: when the junction-queue state is
everywhere clear, the total residual payload is zero — all information has been
delivered.

**fdrs.md line 6457**: Payload = information in flight between timelines.
-/
theorem residual_is_in_flight_information (spec : RoutingSpecification)
    (residue : ℕ → ℕ → ℕ → ℕ → ℕ) (sourceTimeline targetTimeline time : ℕ)
    (hclear : ∀ a b c d, residue a b c d = 0) :
    residualPayload spec residue sourceTimeline targetTimeline time = 0 := by
  simp [residualPayload, undeliveredResidue, hclear]

end FdrsFormal.Composition.ObserverIntegration
