/-
Copyright 2026 Hyphaeic SPC.

Licensed under the Hyphaeic Public License, Version 1.0 (the
"License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

https://github.com/hyphaeic/hpl

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.

# The carry quotient of a wrapped ring (Phase 1 addendum, §3.12)

Close the ring of §3.11: a carry out of the top place re-enters place `0` with an integer
**wrap gain** `c`. Integer states `x : Fin (n+1) → ℤ` modulo the carry moves (forward and
backward) form a group; this file computes it. With `B = ∏ ρ_i` the lap value,

  `ℤ^{n+1} / ⟨carries⟩ ≅ ℤ / (B − c)`,

cyclic, generated by the unit at place `0`, and two states are carry-equivalent iff their
place values agree modulo `B − c`. The wrap gain chooses the arithmetic: `c = 1` is
end-around-carry arithmetic modulo `B − 1` (cyclic convolution), `c = −1` is arithmetic
modulo `B + 1` (negacyclic convolution, §1.14), and the 25519 ring with `c = 19` is
`𝔽_p`. The loop is balanced exactly when `B = c`; then the quotient is `ℤ` itself.
Frustration is torsion.

On a constant ring (`ρ_i = r`) the quotient is a ring whose product is the
**wrapped convolution** (Definition 231): limb multiplication is wrapped convolution
followed by carries.

Reuses `RingUnrolling.lean` (the ring, its periodic schedule, the 25519 ring and its lap),
`placeValue` (Core), `cycConv` (§1.13) and `negConv` (§1.14).

- **Definition 230** (`cell`, `wrap`, `carryVec`, `carryLattice`, `weight`, `lapValue`,
  `value`, `modulus`): the carry lattice of a wrapped ring and its value map.
- **Theorem 147** (`ker_ev`, `carry_equiv_iff`, `carryQuotient`, `class_eq`): the carry
  quotient is `ℤ / (B − c)`, cyclic on the unit at place `0`.
- **Proposition 176** (`card_carryQuotient`, `balancedQuotient`): `|B − c|` classes;
  a balanced ring (`B = c`) has quotient `ℤ`.
- **Definition 231 / Theorem 148** (`wrapConv`, `evalAt`, `evalAt_wrapConv`): if
  `X^N = c`, evaluation at `X` turns wrapped convolution into multiplication.
- **Corollary 51** (`ev_wrapConv`): on a constant ring, the carry class of the wrapped
  convolution of two states is the product of their classes.
- **Proposition 177** (`cycConv_eq_wrapConv`, `negConv_eq_wrapConv`,
  `field25519_modulus`, `field25519_carry_quotient`, `field25519_carry_equiv_iff`):
  `c = 1` is cyclic convolution, `c = −1` is negacyclic convolution, and the 25519 ring
  with wrap gain `19` has carry quotient `ℤ/p`.

**Honest scope.** Classical: the quotient is the cokernel of a cyclic bidiagonal matrix
(its determinant is `±(B − c)`), and the wrapped-convolution identity is the arithmetic of
`R[X]/(X^N − c)`. The corpus contributes the reading of carry-equivalence on its digit
rings as this cokernel, the wrap gain as the choice of modulus, and the 25519 instance.
General carry networks (several loops; invariant factors) are not covered.
-/

import FdrsFormal.Modes.SyntheticPlace.RingUnrolling
import FdrsFormal.NumberTheory.Characters.Negacyclic
import Mathlib.Tactic.Module

namespace FdrsFormal.Modes.SyntheticPlace.CarryQuotient

open FdrsFormal.Core.Primitives FdrsFormal.Modes.SyntheticPlace.RingUnrolling

/-! ## Definition 230: the carry lattice of a wrapped ring -/

section Ring

variable {n : ℕ} (ρ : Fin (n + 1) → ℕ) (hρ : ∀ i, 2 ≤ ρ i) (c : ℤ)

/-- The unit state at place `i`. -/
def cell (i : Fin (n + 1)) : Fin (n + 1) → ℤ := Pi.single i 1

/-- The gain with which a carry out of place `i` enters place `i + 1`: `1`, except `c`
on the wrap out of the top place. -/
def wrap (i : Fin (n + 1)) : ℤ := if i = Fin.last n then c else 1

/-- The carry move at place `i`: `ρ_i` units leave place `i`, `wrap i` units enter place
`i + 1 (mod n+1)`.

**fdrs.md**: Definition 230 (the carry lattice of a wrapped ring). -/
def carryVec (i : Fin (n + 1)) : Fin (n + 1) → ℤ :=
  wrap c i • cell (i + 1) - (ρ i : ℤ) • cell i

/-- The carry lattice: all integer combinations of carry moves (forward and backward).

**fdrs.md**: Definition 230 (the carry lattice of a wrapped ring). -/
def carryLattice : AddSubgroup (Fin (n + 1) → ℤ) :=
  AddSubgroup.closure (Set.range (carryVec ρ c))

/-- The weight of place `k`: the place value of the periodic schedule (Definition 229). -/
def weight (k : ℕ) : ℤ := placeValue (ringSchedule ρ hρ) k

/-- The lap value `B = ∏ ρ_i`, the weight one lap up the helix. -/
def lapValue : ℤ := weight ρ hρ (n + 1)

/-- The value of a state: `Σ_i x_i B_i`.

**fdrs.md**: Definition 230 (the carry lattice of a wrapped ring). -/
def value : (Fin (n + 1) → ℤ) →+ ℤ :=
  AddMonoidHom.mk' (fun x => ∑ i, x i * weight ρ hρ i)
    (by intro x y; simp [add_mul, Finset.sum_add_distrib])

/-- The modulus `|B − c|`. -/
def modulus : ℕ := (lapValue ρ hρ - c).natAbs

/-- The value modulo `B − c`. -/
def ev : (Fin (n + 1) → ℤ) →+ ZMod (modulus ρ hρ c) :=
  (Int.castAddHom (ZMod (modulus ρ hρ c))).comp (value ρ hρ)

theorem ringSchedule_lt {k : ℕ} (hk : k < n + 1) : ringSchedule ρ hρ k = ρ ⟨k, hk⟩ := by
  show ρ (placeOf k) = ρ ⟨k, hk⟩
  exact congrArg ρ (Fin.ext (Nat.mod_eq_of_lt hk))

theorem weight_zero : weight ρ hρ 0 = 1 := by simp [weight]

theorem weight_succ {k : ℕ} (hk : k < n + 1) :
    weight ρ hρ (k + 1) = weight ρ hρ k * ρ ⟨k, hk⟩ := by
  simp [weight, placeValue.succ, ringSchedule_lt ρ hρ hk]

theorem value_apply (x : Fin (n + 1) → ℤ) : value ρ hρ x = ∑ i, x i * weight ρ hρ i := rfl

theorem value_cell (i : Fin (n + 1)) : value ρ hρ (cell i) = weight ρ hρ i := by
  simp [value_apply, cell, Pi.single_apply]

theorem value_carryVec (i : Fin (n + 1)) :
    value ρ hρ (carryVec ρ c i) = if i = Fin.last n then c - lapValue ρ hρ else 0 := by
  simp only [carryVec, map_sub, map_zsmul, value_cell, smul_eq_mul, wrap]
  split_ifs with h
  · subst h
    rw [Fin.last_add_one, Fin.val_zero, weight_zero, lapValue,
      weight_succ ρ hρ (Nat.lt_succ_self n)]
    simp only [Fin.last]
    ring
  · rw [Fin.val_add_one_of_lt (Fin.lt_last_iff_ne_last.mpr h), weight_succ ρ hρ i.isLt]
    ring

theorem ev_apply (x : Fin (n + 1) → ℤ) :
    ev ρ hρ c x = ((value ρ hρ x : ℤ) : ZMod (modulus ρ hρ c)) := rfl

theorem ev_eq_zero_iff (x : Fin (n + 1) → ℤ) :
    ev ρ hρ c x = 0 ↔ lapValue ρ hρ - c ∣ value ρ hρ x := by
  rw [ev_apply, CharP.intCast_eq_zero_iff (ZMod (modulus ρ hρ c)) (modulus ρ hρ c),
    modulus, Int.natAbs_dvd]

/-! ## Theorem 147: the carry quotient -/

/-- Carrying down: the unit at place `k` is carry-equivalent to `B_k` units at place `0`. -/
theorem cell_sub_mem : ∀ (k : ℕ) (hk : k < n + 1),
    cell ⟨k, hk⟩ - weight ρ hρ k • cell 0 ∈ carryLattice ρ c
  | 0, _ => by
    rw [weight_zero, one_smul, show (⟨0, _⟩ : Fin (n + 1)) = 0 from rfl, sub_self]
    exact (carryLattice ρ c).zero_mem
  | k + 1, hk => by
    have hk' : k < n + 1 := by omega
    have hne : (⟨k, hk'⟩ : Fin (n + 1)) ≠ Fin.last n := by
      intro h; have := congrArg Fin.val h; simp at this; omega
    have hv : carryVec ρ c ⟨k, hk'⟩ = cell ⟨k + 1, hk⟩ - (ρ ⟨k, hk'⟩ : ℤ) • cell ⟨k, hk'⟩ := by
      rw [carryVec, wrap, if_neg hne, one_smul]
      congr 2
      exact Fin.ext (by rw [Fin.val_add_one_of_lt (Fin.lt_last_iff_ne_last.mpr hne)])
    have hmem : carryVec ρ c ⟨k, hk'⟩ ∈ carryLattice ρ c :=
      AddSubgroup.subset_closure ⟨_, rfl⟩
    have h2 := (carryLattice ρ c).zsmul_mem (cell_sub_mem k hk') (ρ ⟨k, hk'⟩ : ℤ)
    have h3 := (carryLattice ρ c).add_mem hmem h2
    rw [hv, weight_succ ρ hρ hk'] at *
    convert h3 using 1
    rw [smul_sub, mul_comm, mul_smul]
    abel

/-- One lap: `B − c` units at place `0` are carry-equivalent to nothing. -/
theorem lap_mem : (lapValue ρ hρ - c) • cell 0 ∈ carryLattice ρ c := by
  have hmem : carryVec ρ c (Fin.last n) ∈ carryLattice ρ c :=
    AddSubgroup.subset_closure ⟨_, rfl⟩
  have h1 := cell_sub_mem ρ hρ c n (Nat.lt_succ_self n)
  have h2 := (carryLattice ρ c).sub_mem
    ((carryLattice ρ c).zsmul_mem h1 (-(ρ (Fin.last n) : ℤ))) hmem
  convert h2 using 1
  rw [carryVec, wrap, if_pos rfl, Fin.last_add_one, lapValue,
    weight_succ ρ hρ (Nat.lt_succ_self n)]
  have : (⟨n, Nat.lt_succ_self n⟩ : Fin (n + 1)) = Fin.last n := rfl
  rw [this]
  module

/-- Every state is carry-equivalent to its value, placed at place `0`. -/
theorem sub_value_mem (x : Fin (n + 1) → ℤ) :
    x - value ρ hρ x • cell 0 ∈ carryLattice ρ c := by
  have hx : x - value ρ hρ x • cell 0 =
      ∑ i, x i • (cell i - weight ρ hρ i • cell 0) := by
    simp only [smul_sub, Finset.sum_sub_distrib, smul_smul, value_apply, Finset.sum_smul]
    congr 1
    funext j
    simp [cell, Finset.sum_apply, Pi.single_apply]
  rw [hx]
  refine AddSubgroup.sum_mem _ fun i _ => AddSubgroup.zsmul_mem _ ?_ _
  exact cell_sub_mem ρ hρ c i i.isLt

/-- **Theorem 147 (the carry kernel).** A state is a combination of carry moves iff its
value is divisible by `B − c`.

**fdrs.md**: Theorem 147 (the carry quotient). -/
theorem ker_ev : (ev ρ hρ c).ker = carryLattice ρ c := by
  apply le_antisymm
  · intro x hx
    rw [AddMonoidHom.mem_ker, ev_eq_zero_iff] at hx
    obtain ⟨t, ht⟩ := hx
    have h := (carryLattice ρ c).add_mem (sub_value_mem ρ hρ c x)
      ((carryLattice ρ c).zsmul_mem (lap_mem ρ hρ c) t)
    convert h using 1
    rw [ht, smul_smul, mul_comm]
    abel
  · rw [carryLattice, AddSubgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    rw [SetLike.mem_coe, AddMonoidHom.mem_ker, ev_eq_zero_iff, value_carryVec]
    split_ifs
    · exact ⟨-1, by ring⟩
    · exact dvd_zero _

/-- **Theorem 147 (carry-equivalence).** Two states differ by carry moves iff their values
agree modulo `B − c`.

**fdrs.md**: Theorem 147 (the carry quotient). -/
theorem carry_equiv_iff (x y : Fin (n + 1) → ℤ) :
    x - y ∈ carryLattice ρ c ↔ lapValue ρ hρ - c ∣ value ρ hρ x - value ρ hρ y := by
  rw [← ker_ev ρ hρ c, AddMonoidHom.mem_ker, ev_eq_zero_iff, map_sub]

theorem ev_surjective : Function.Surjective (ev ρ hρ c) := by
  intro z
  obtain ⟨k, rfl⟩ := ZMod.intCast_surjective z
  refine ⟨k • cell 0, ?_⟩
  rw [ev_apply, map_zsmul, value_cell, Fin.val_zero, weight_zero, smul_eq_mul, mul_one]

/-- **Theorem 147 (the carry quotient).** `ℤ^{n+1}` modulo carry moves is `ℤ / (B − c)`.

**fdrs.md**: Theorem 147 (the carry quotient). -/
noncomputable def carryQuotient :
    (Fin (n + 1) → ℤ) ⧸ carryLattice ρ c ≃+ ZMod (modulus ρ hρ c) :=
  (QuotientAddGroup.quotientAddEquivOfEq (ker_ev ρ hρ c).symm).trans
    (QuotientAddGroup.quotientKerEquivOfSurjective _ (ev_surjective ρ hρ c))

theorem carryQuotient_mk (x : Fin (n + 1) → ℤ) :
    carryQuotient ρ hρ c (x : (Fin (n + 1) → ℤ) ⧸ carryLattice ρ c) = ev ρ hρ c x := rfl

/-- **Theorem 147 (the quotient is cyclic).** The class of every state is `value x` times
the class of the unit at place `0`.

**fdrs.md**: Theorem 147 (the carry quotient). -/
theorem class_eq (x : Fin (n + 1) → ℤ) :
    (x : (Fin (n + 1) → ℤ) ⧸ carryLattice ρ c) =
      value ρ hρ x • ((cell 0 : Fin (n + 1) → ℤ) : (Fin (n + 1) → ℤ) ⧸ carryLattice ρ c) := by
  rw [← QuotientAddGroup.mk_zsmul, QuotientAddGroup.eq]
  have := (carryLattice ρ c).neg_mem (sub_value_mem ρ hρ c x)
  convert this using 1
  abel

/-! ## Proposition 176: frustration is torsion -/

/-- **Proposition 176 (the number of carry classes).** The carry quotient has `|B − c|`
classes (`Nat.card = 0` meaning infinitely many).

**fdrs.md**: Proposition 176 (frustration is torsion). -/
theorem card_carryQuotient :
    Nat.card ((Fin (n + 1) → ℤ) ⧸ carryLattice ρ c) = (lapValue ρ hρ - c).natAbs :=
  (Nat.card_congr (carryQuotient ρ hρ c).toEquiv).trans (Nat.card_zmod _)

/-- **Proposition 176 (a balanced ring keeps the integers).** If the wrap gain equals the
lap value (`B = c`, holonomy `1`), carry classes are exactly integer values.

**fdrs.md**: Proposition 176 (frustration is torsion). -/
noncomputable def balancedQuotient (h : lapValue ρ hρ = c) :
    (Fin (n + 1) → ℤ) ⧸ carryLattice ρ c ≃+ ℤ :=
  (carryQuotient ρ hρ c).trans
    (ZMod.ringEquivCongr (show modulus ρ hρ c = 0 by simp [modulus, h])).toAddEquiv

end Ring

/-! ## Definition 231 and Theorem 148: wrapped convolution -/

section Wrapped

variable {R : Type*} [CommRing R] {N : ℕ}

/-- **Wrapped convolution** with gain `c`: products that pass the top place re-enter
multiplied by `c`. `c = 1` is cyclic, `c = −1` negacyclic.

**fdrs.md**: Definition 231 (wrapped convolution). -/
def wrapConv [NeZero N] (c : R) (f g : Fin N → R) (k : Fin N) : R :=
  ∑ m, (if m ≤ k then 1 else c) * (f m * g (k - m))

/-- Evaluation of a state at `X`: `Σ_k f_k X^k`. -/
def evalAt (X : R) (f : Fin N → R) : R := ∑ k, f k * X ^ (k : ℕ)

theorem wrap_pow [NeZero N] {X c : R} (hX : X ^ N = c) (m k : Fin N) :
    (if m ≤ k then 1 else c) * X ^ (k : ℕ) = X ^ (m : ℕ) * X ^ ((k - m : Fin N) : ℕ) := by
  rw [← pow_add]
  split_ifs with h
  · rw [one_mul, Fin.sub_val_of_le h, Nat.add_sub_cancel' (Fin.le_iff_val_le_val.mp h)]
  · rw [← hX, ← pow_add, Fin.val_sub]
    have hm := m.isLt
    have hk : (k : ℕ) < m := Fin.lt_def.mp (not_le.mp h)
    rw [Nat.mod_eq_of_lt (by omega)]
    congr 1
    omega

/-- **Theorem 148 (wrapped convolution is multiplication).** If `X^N = c`, evaluation at
`X` turns wrapped convolution into the product.

**fdrs.md**: Theorem 148 (wrapped convolution is multiplication modulo (X^N-c)). -/
theorem evalAt_wrapConv [NeZero N] {X c : R} (hX : X ^ N = c) (f g : Fin N → R) :
    evalAt X (wrapConv c f g) = evalAt X f * evalAt X g := by
  simp only [evalAt, wrapConv, Finset.sum_mul, Finset.mul_sum]
  conv_lhs => rw [Finset.sum_comm]
  conv_rhs => rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun m _ => ?_
  calc ∑ k, (if m ≤ k then 1 else c) * (f m * g (k - m)) * X ^ (k : ℕ)
      = ∑ k, f m * X ^ (m : ℕ) * (g (k - m) * X ^ ((k - m : Fin N) : ℕ)) := by
        refine Finset.sum_congr rfl fun k _ => ?_
        calc (if m ≤ k then 1 else c) * (f m * g (k - m)) * X ^ (k : ℕ)
            = f m * g (k - m) * ((if m ≤ k then 1 else c) * X ^ (k : ℕ)) := by ring
          _ = _ := by rw [wrap_pow hX]; ring
    _ = ∑ j, f m * X ^ (m : ℕ) * (g j * X ^ (j : ℕ)) :=
        Equiv.sum_comp (Equiv.subRight m) (fun j => f m * X ^ (m : ℕ) * (g j * X ^ (j : ℕ)))

end Wrapped

/-! ## Corollary 51: multiplication on the carry quotient of a constant ring -/

section Constant

variable {n r : ℕ} (hr : 2 ≤ r) (c : ℤ)

theorem weight_const : ∀ k, weight (fun _ : Fin (n + 1) => r) (fun _ => hr) k = (r : ℤ) ^ k
  | 0 => by simp [weight]
  | k + 1 => by
    have := weight_const k
    simp only [weight] at this ⊢
    rw [placeValue.succ, Nat.cast_mul, this, pow_succ]
    rfl

theorem ev_const (x : Fin (n + 1) → ℤ) :
    ev (fun _ => r) (fun _ => hr) c x =
      evalAt (r : ZMod (modulus (fun _ : Fin (n + 1) => r) (fun _ => hr) c))
        (fun i => (x i : ZMod _)) := by
  simp [ev_apply, value_apply, evalAt, weight_const hr]

theorem pow_eq_wrap :
    (r : ZMod (modulus (fun _ : Fin (n + 1) => r) (fun _ => hr) c)) ^ (n + 1) = (c : ZMod _) := by
  have h := (ev_eq_zero_iff (fun _ : Fin (n + 1) => r) (fun _ => hr) c
    ((lapValue (fun _ : Fin (n + 1) => r) (fun _ => hr) - c) • cell 0)).mpr
    ⟨1, by rw [map_zsmul, value_cell, Fin.val_zero, weight_zero, smul_eq_mul, mul_one]⟩
  rw [ev_apply, map_zsmul, value_cell, Fin.val_zero, weight_zero, smul_eq_mul, mul_one, lapValue,
    weight_const hr] at h
  push_cast at h
  exact sub_eq_zero.mp h

/-- **Corollary 51 (multiplication on the carry quotient).** On a constant ring of radix
`r` with wrap gain `c`, the carry class of the wrapped convolution of two states is the
product of their classes: limb multiplication is wrapped convolution followed by carries.

**fdrs.md**: Corollary 51 (multiplication on the carry quotient). -/
theorem ev_wrapConv (a b : Fin (n + 1) → ℤ) :
    ev (fun _ => r) (fun _ => hr) c (wrapConv c a b) =
      ev (fun _ => r) (fun _ => hr) c a * ev (fun _ => r) (fun _ => hr) c b := by
  rw [ev_const, ev_const, ev_const, ← evalAt_wrapConv (pow_eq_wrap hr c)]
  congr 1
  funext k
  simp [wrapConv, apply_ite]

end Constant

/-! ## Proposition 177: the instances -/

section Instances

variable {R : Type*} [CommRing R] {n : ℕ}

/-- **Proposition 177 (`c = 1` is cyclic convolution).**

**fdrs.md**: Proposition 177 (cyclic, negacyclic, and 25519). -/
theorem cycConv_eq_wrapConv (f g : ℕ → R) {k : ℕ} (hk : k < n + 1) :
    FdrsFormal.NumberTheory.Characters.MixedRadixFFT.cycConv (n + 1) f g k =
      wrapConv 1 (fun i : Fin (n + 1) => f i) (fun i => g i) ⟨k, hk⟩ := by
  rw [FdrsFormal.NumberTheory.Characters.MixedRadixFFT.cycConv, Finset.sum_range, wrapConv]
  refine Finset.sum_congr rfl fun m _ => ?_
  rw [ite_self, one_mul, Fin.val_sub]
  have := m.isLt
  have he : n + 1 - (m : ℕ) + k = k + (n + 1) - m := by omega
  simp only [he]

/-- **Proposition 177 (`c = −1` is negacyclic convolution).**

**fdrs.md**: Proposition 177 (cyclic, negacyclic, and 25519). -/
theorem negConv_eq_wrapConv (f g : ℕ → R) {k : ℕ} (hk : k < n + 1) :
    FdrsFormal.NumberTheory.Characters.MixedRadixFFT.negConv (n + 1) f g k =
      wrapConv (-1) (fun i : Fin (n + 1) => f i) (fun i => g i) ⟨k, hk⟩ := by
  rw [FdrsFormal.NumberTheory.Characters.MixedRadixFFT.negConv, Finset.sum_range, wrapConv]
  refine Finset.sum_congr rfl fun m _ => ?_
  have hm := m.isLt
  by_cases h : (m : ℕ) ≤ k
  · have h' : m ≤ (⟨k, hk⟩ : Fin (n + 1)) := Fin.le_iff_val_le_val.mpr h
    rw [if_pos h, if_pos h', one_mul, Fin.sub_val_of_le h']
  · have h' : ¬ m ≤ (⟨k, hk⟩ : Fin (n + 1)) := fun h' => h (Fin.le_iff_val_le_val.mp h')
    rw [if_neg h, if_neg h', Fin.val_sub, Nat.mod_eq_of_lt (by simp; omega)]
    have he : n + 1 - (m : ℕ) + k = k + (n + 1) - m := by omega
    simp only [neg_one_mul, he]

end Instances

section Field25519

open FdrsFormal.Applications.Field25519

/-- **Proposition 177 (the 25519 modulus).** The 25519 ring with wrap gain `19` has
modulus `|2^255 − 19| = p`.

**fdrs.md**: Proposition 177 (cyclic, negacyclic, and 25519). -/
theorem field25519_gap : lapValue ring25519 ring25519_ge_two - 19 = (p : ℤ) := by
  have h := field25519_lap_holonomy.1
  rw [lapValue, weight, h, p]
  norm_num

theorem field25519_modulus : modulus ring25519 ring25519_ge_two 19 = p := by
  rw [modulus, field25519_gap, Int.natAbs_natCast]

/-- **Proposition 177 (the 25519 carry quotient is `ℤ/p`).** Ten-limb integer states on
the 25519 ring, modulo carries that wrap with gain `19`, are exactly the residues mod `p`.

**fdrs.md**: Proposition 177 (cyclic, negacyclic, and 25519). -/
noncomputable def field25519_carry_quotient :
    (Fin 10 → ℤ) ⧸ carryLattice ring25519 19 ≃+ ZMod p :=
  (carryQuotient ring25519 ring25519_ge_two 19).trans
    (ZMod.ringEquivCongr field25519_modulus).toAddEquiv

theorem field25519_card : Nat.card ((Fin 10 → ℤ) ⧸ carryLattice ring25519 19) = p := by
  rw [card_carryQuotient ring25519 ring25519_ge_two, field25519_gap, Int.natAbs_natCast]

/-- **Proposition 177 (25519 carry-equivalence).** Two ten-limb states differ by carries
(wrapping with gain `19`) iff `Σ_i (x_i − y_i) 2^{W_i} ≡ 0 (mod p)`.

**fdrs.md**: Proposition 177 (cyclic, negacyclic, and 25519). -/
theorem field25519_carry_equiv_iff (x y : Fin 10 → ℤ) :
    x - y ∈ carryLattice ring25519 19 ↔
      (p : ℤ) ∣ ∑ i, (x i - y i) * 2 ^ weightBits i := by
  rw [carry_equiv_iff ring25519 ring25519_ge_two, field25519_gap, ← map_sub]
  simp [value_apply, weight, field25519_unrolls]

end Field25519

end FdrsFormal.Modes.SyntheticPlace.CarryQuotient
