/-
Copyright 2026 Hyphaeic SPC.

Licensed under the Hyphaeic Public License, Version 1.0 (the
"License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

https://github.com/hyphaeic/hpl

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.

# The dimension of a designed gauge (§14.15)

Hausdorff dimension as the tree↔gauge exchange rate. A *position gauge* is a
monotone unbounded weight `g : ℕ → ℕ`; the gauged distance
`δ_g(x,y) = g(firstDiff x y)⁻¹` remetrizes the completed mixed-radix space
`R̂ = ∏ᵢ Fin(bᵢ)` (the position-only instance of Definition 192's prefix
gauge). This file proves the Moran frame for such spaces and computes:

- **Theorem 117** (`dimH_completedSpace_eq_one`): under the *canonical* gauge
  `g = placeValue` — any radix schedule — `dimH R̂ = 1`. Being a number line
  pins the dimension.
- **Theorem 116** (`GaugedSpace.dimH_univ_le` / `GaugedSpace.le_dimH_univ`):
  the generic cover/mass pair — `dimH` is squeezed by the count/gauge ratio.
- **Theorem 118** (`dimH_designedGauge`): on the binary tree the schedule
  `g(n) = 2^⌈n/r⌉` realizes `dimH = r` for every `r > 0` — the gauge
  *programs* the dimension.
- **Proposition 153** (`dimH_factorialGauge_eq_zero`, `dimH_polyGauge_eq_top`):
  §6.4.3's growth regimes computed — factorial gauge ⇒ dimension 0,
  polynomial gauge ⇒ dimension ∞.

Supporting infrastructure (corpus-valuable beyond this file): the Borel
bridge `pi_eq_borel_completedSpace` welding the product σ-algebra (where
`uniformProductMeasure` lives) to the Borel σ-algebra of the ultrametric.

The mathematics is classical (Moran 1946; Falconer ch. 4; Billingsley-style
dimension on sequence spaces). Design record:
`docs/synthetic-place/05-dimension.md`.
-/

import FdrsFormal.Topology.Filtration.Definition
import FdrsFormal.FunctionSpaces.Measure.ProductMeasure
import Mathlib.Topology.MetricSpace.HausdorffDimension
import Mathlib.Topology.Algebra.Order.Floor
import Mathlib.Analysis.SpecificLimits.Normed

namespace FdrsFormal.Modes.SyntheticPlace.Dimension

open FdrsFormal.Core.Primitives FdrsFormal.Core.Infinite
open FdrsFormal.Topology.Ultrametric FdrsFormal.Topology.Filtration
open FdrsFormal.FunctionSpaces.Basic FdrsFormal.FunctionSpaces.Measure
open MeasureTheory
open scoped ENNReal NNReal Topology Nat

variable {b : RadixSeq}

/-! ## The two cylinder families are one family

`Topology.Ultrametric.cylinder` (metric side) and
`FunctionSpaces.Basic.cylinderSet` (measure side) are the same sets. -/

theorem cylinderSet_eq_cylinder (L : ℕ) (s : PrefixSet b L) :
    cylinderSet b L s = cylinder b L s := rfl

/-! ## R1: the Borel bridge

The corpus measure (`uniformProductMeasure`) lives on the product σ-algebra
`MeasurableSpace.pi`; the metric results live on the Borel σ-algebra of the
ultrametric. They are equal: cylinders generate both. -/

/-- The coordinate-evaluation preimage of a single digit value is a finite
union of depth-`(j+1)` cylinders. -/
theorem eval_preimage_singleton_eq (j : ℕ) (d : Fin (b j)) :
    {x : CompletedSpace b | x j = d} =
      ⋃ t : {t : PrefixSet b (j + 1) // t ⟨j, Nat.lt_succ_self j⟩ = d},
        cylinderSet b (j + 1) t.1 := by
  ext x
  simp only [Set.mem_setOf_eq, Set.mem_iUnion]
  constructor
  · intro hx
    refine ⟨⟨CompletedSpace.take x (j + 1), hx⟩, fun i => rfl⟩
  · rintro ⟨⟨t, ht⟩, hx⟩
    have := hx ⟨j, Nat.lt_succ_self j⟩
    simpa [ht] using this

/-- The product σ-algebra is generated by cylinders. -/
theorem pi_eq_generateFrom_cylinderSets (b : RadixSeq) :
    (instMeasurableSpaceCompletedSpace : MeasurableSpace (CompletedSpace b)) =
      MeasurableSpace.generateFrom
        {S | ∃ L : ℕ, ∃ s : PrefixSet b L, S = cylinderSet b L s} := by
  apply le_antisymm
  · show (MeasurableSpace.pi : MeasurableSpace (CompletedSpace b)) ≤ _
    rw [MeasurableSpace.pi]
    refine iSup_le fun j => ?_
    intro S hS
    obtain ⟨T, -, rfl⟩ := hS
    show MeasurableSet[MeasurableSpace.generateFrom
        {S | ∃ L : ℕ, ∃ s : PrefixSet b L, S = cylinderSet b L s}]
      ((fun x : CompletedSpace b => x j) ⁻¹' T)
    have hT : (fun x : CompletedSpace b => x j) ⁻¹' T =
        ⋃ d ∈ T, {x : CompletedSpace b | x j = d} := by
      ext x; simp
    rw [hT]
    refine MeasurableSet.biUnion T.to_countable fun d _ => ?_
    rw [eval_preimage_singleton_eq]
    exact MeasurableSet.iUnion fun t =>
      MeasurableSpace.measurableSet_generateFrom ⟨j + 1, t.1, rfl⟩
  · refine MeasurableSpace.generateFrom_le ?_
    rintro S ⟨L, s, rfl⟩
    exact cylinder_measurableSet L s

/-- The two generator families coincide as set families. -/
theorem cylinderSets_eq_cylinders (b : RadixSeq) :
    {S | ∃ L : ℕ, ∃ s : PrefixSet b L, S = cylinderSet b L s} =
      {S | ∃ L : ℕ, ∃ s : (i : Fin L) → Fin (b i), S = cylinder b L s} := rfl

/-- **The Borel bridge**: the product σ-algebra equals the Borel σ-algebra of
the canonical ultrametric. -/
theorem pi_eq_borel_completedSpace (b : RadixSeq) :
    (instMeasurableSpaceCompletedSpace : MeasurableSpace (CompletedSpace b)) =
      borel (CompletedSpace b) := by
  rw [pi_eq_generateFrom_cylinderSets b, cylinderSets_eq_cylinders b,
    cylinder_generateFrom_eq_borel b]

instance : BorelSpace (CompletedSpace b) := ⟨pi_eq_borel_completedSpace b⟩

/-! ## R2: the position gauge and the gauged remetrization

A position gauge is the position-only instance of Definition 192's prefix
gauge: a monotone, unbounded, positive weight on depths. `GaugedSpace b G` is
the completed space re-metrized by `δ_g(x,y) = g(firstDiff x y)⁻¹`. -/

/-- A designed resolution schedule: positive, monotone, unbounded.

**fdrs.md**: Definition 213 (position gauge; the gauged completion). -/
structure PositionGauge where
  /-- The weight at each depth. -/
  g : ℕ → ℕ
  /-- Positivity. -/
  one_le : ∀ n, 1 ≤ g n
  /-- Deeper prefixes resolve at least as finely. -/
  mono : Monotone g
  /-- The resolution is unbounded (radii vanish). -/
  unbounded : ∀ M : ℕ, ∃ n, M < g n

namespace PositionGauge

theorem pos (G : PositionGauge) (n : ℕ) : 0 < G.g n := G.one_le n

theorem pos_real (G : PositionGauge) (n : ℕ) : (0 : ℝ) < (G.g n : ℝ) :=
  Nat.cast_pos.mpr (G.pos n)

/-- Monotone + unbounded: eventually above any bound. -/
theorem eventually_lt (G : PositionGauge) (M : ℕ) : ∃ N, ∀ n, N ≤ n → M < G.g n := by
  obtain ⟨N, hN⟩ := G.unbounded M
  exact ⟨N, fun n hn => lt_of_lt_of_le hN (G.mono hn)⟩

/-- The gauge reciprocals vanish: the designed radii tend to zero. -/
theorem tendsto_inv_zero (G : PositionGauge) :
    Filter.Tendsto (fun L => ((G.g L : ℝ≥0∞))⁻¹) Filter.atTop (nhds 0) := by
  rw [ENNReal.tendsto_nhds_zero]
  intro ε hε
  obtain ⟨n, hn⟩ := ENNReal.exists_nat_gt (ENNReal.inv_ne_top.mpr (ne_of_gt hε))
  obtain ⟨N, hN⟩ := G.eventually_lt n
  refine Filter.eventually_atTop.mpr ⟨N, fun L hL => ?_⟩
  rw [ENNReal.inv_le_iff_inv_le]
  calc ε⁻¹ ≤ (n : ℝ≥0∞) := le_of_lt hn
    _ ≤ (G.g L : ℝ≥0∞) := by exact_mod_cast le_of_lt (hN L hL)

end PositionGauge

/-- The canonical gauge: the place value itself. -/
def placeValueGauge (b : RadixSeq) : PositionGauge where
  g := placeValue b
  one_le := fun n => placeValue.one_le n
  mono := placeValue.mono
  unbounded := fun M =>
    ⟨M + 1, lt_of_lt_of_le (Nat.lt_succ_self M) placeValue.strictMono.le_apply⟩

/-- The completed space re-metrized by a designed position gauge (a type
synonym; the canonical metric on `CompletedSpace` is untouched).

**fdrs.md**: Definition 213 (position gauge; the gauged completion). -/
def GaugedSpace (b : RadixSeq) (_G : PositionGauge) : Type := CompletedSpace b

namespace GaugedSpace

variable {G : PositionGauge}

instance : Inhabited (GaugedSpace b G) := ⟨(default : CompletedSpace b)⟩

noncomputable instance : MeasurableSpace (GaugedSpace b G) :=
  (instMeasurableSpaceCompletedSpace : MeasurableSpace (CompletedSpace b))

open Classical in
/-- The designed distance `δ_g(x,y) = g(firstDiff x y)⁻¹`. -/
noncomputable def gaugedDist (b : RadixSeq) (G : PositionGauge) (x y : GaugedSpace b G) : ℝ :=
  if x = y then 0 else ((G.g (firstDiff b x y) : ℝ))⁻¹

theorem firstDiff_self (x : CompletedSpace b) : firstDiff b x x = 0 := by
  simp [firstDiff]

theorem firstDiff_comm' (x y : CompletedSpace b) : firstDiff b x y = firstDiff b y x := by
  unfold firstDiff
  by_cases h : x = y
  · simp [h]
  · have h' : y ≠ x := fun e => h e.symm
    rw [dif_pos h, dif_pos h']
    congr 1
    funext m
    simp only [eq_iff_iff]
    exact ⟨Ne.symm, Ne.symm⟩

/-- The ultrametric heart: the first difference of `x, z` is at least the
smaller of the first differences through any midpoint `y`. -/
theorem min_firstDiff_le (x y z : CompletedSpace b) (hxz : x ≠ z) :
    min (firstDiff b x y) (firstDiff b y z) ≤ firstDiff b x z := by
  by_contra hcon
  push_neg at hcon
  have h1 : firstDiff b x z < firstDiff b x y := lt_of_lt_of_le hcon (min_le_left _ _)
  have h2 : firstDiff b x z < firstDiff b y z := lt_of_lt_of_le hcon (min_le_right _ _)
  have hxy : x ≠ y := by
    rintro rfl
    rw [firstDiff_self] at h1
    exact Nat.not_lt_zero _ h1
  have hyz : y ≠ z := by
    rintro rfl
    rw [firstDiff_self] at h2
    exact Nat.not_lt_zero _ h2
  exact firstDiff_spec hxz
    ((eq_of_lt_firstDiff hxy h1).trans (eq_of_lt_firstDiff hyz h2))

theorem gaugedDist_nonneg (x y : GaugedSpace b G) : 0 ≤ gaugedDist b G x y := by
  unfold gaugedDist
  split_ifs
  · exact le_refl 0
  · positivity

/-- Agreement on a prefix bounds the gauged distance by the gauge reciprocal. -/
theorem gaugedDist_le_of_agree {x y : GaugedSpace b G} {L : ℕ}
    (h : ∀ i, i < L → x i = y i) : gaugedDist b G x y ≤ ((G.g L : ℝ))⁻¹ := by
  unfold gaugedDist
  split_ifs with heq
  · positivity
  · have hfd : L ≤ firstDiff b x y := by
      by_contra hlt
      push_neg at hlt
      exact firstDiff_spec heq (h _ hlt)
    rw [inv_le_inv₀ (G.pos_real _) (G.pos_real _)]
    exact_mod_cast G.mono hfd

/-- A gauged distance below `g(L)⁻¹` forces agreement **through** position `L`
(monotone gauges only ever need this direction). -/
theorem agree_of_gaugedDist_lt {x y : GaugedSpace b G} {L : ℕ}
    (h : gaugedDist b G x y < ((G.g L : ℝ))⁻¹) : ∀ i, i ≤ L → x i = y i := by
  intro i hi
  by_cases heq : x = y
  · rw [heq]
  · unfold gaugedDist at h
    rw [if_neg heq] at h
    rw [inv_lt_inv₀ (G.pos_real _) (G.pos_real _)] at h
    have hg : G.g L < G.g (firstDiff b x y) := by exact_mod_cast h
    have hLfd : L < firstDiff b x y := by
      by_contra hle
      push_neg at hle
      exact absurd (G.mono hle) (not_le.mpr hg)
    exact eq_of_lt_firstDiff heq (lt_of_le_of_lt hi hLfd)

/-- The strong (ultrametric) triangle inequality for the gauged distance. -/
theorem gaugedDist_triangle_max (x y z : GaugedSpace b G) :
    gaugedDist b G x z ≤ max (gaugedDist b G x y) (gaugedDist b G y z) := by
  by_cases hxy : x = y
  · subst hxy; exact le_max_right _ _
  by_cases hyz : y = z
  · subst hyz; exact le_max_left _ _
  by_cases hxz : x = z
  · calc gaugedDist b G x z = 0 := by unfold gaugedDist; rw [if_pos hxz]
      _ ≤ gaugedDist b G x y := gaugedDist_nonneg x y
      _ ≤ _ := le_max_left _ _
  · have hmin := min_firstDiff_le x y z hxz
    unfold gaugedDist
    rw [if_neg hxz, if_neg hxy, if_neg hyz]
    rcases le_total (firstDiff b x y) (firstDiff b y z) with hle | hle
    · rw [min_eq_left hle] at hmin
      refine le_trans ?_ (le_max_left _ _)
      rw [inv_le_inv₀ (G.pos_real _) (G.pos_real _)]
      exact_mod_cast G.mono hmin
    · rw [min_eq_right hle] at hmin
      refine le_trans ?_ (le_max_right _ _)
      rw [inv_le_inv₀ (G.pos_real _) (G.pos_real _)]
      exact_mod_cast G.mono hmin

noncomputable instance : MetricSpace (GaugedSpace b G) where
  dist := gaugedDist b G
  dist_self := fun x => by unfold gaugedDist; simp
  dist_comm := fun x y => by
    unfold gaugedDist
    by_cases h : x = y
    · rw [if_pos h, if_pos h.symm]
    · rw [if_neg h, if_neg (fun e => h e.symm), firstDiff_comm']
  dist_triangle := fun x y z =>
    le_trans (gaugedDist_triangle_max x y z)
      (max_le_add_of_nonneg (gaugedDist_nonneg x y) (gaugedDist_nonneg y z))
  eq_of_dist_eq_zero := fun {x y} h => by
    by_contra hne
    unfold gaugedDist at h
    rw [if_neg hne] at h
    exact absurd h (ne_of_gt (inv_pos.mpr (G.pos_real _)))

instance : IsUltrametricDist (GaugedSpace b G) :=
  ⟨gaugedDist_triangle_max⟩

/-! ### Balls are cylinders; the cylinder basis; separability; Borel

The gauged cylinder `gCyl` is `cylinder` with its type pinned to the gauged
space, so instance resolution sees the designed topology, not the canonical
one. -/

/-- A cylinder, read as a subset of the gauged space. -/
def gCyl (b : RadixSeq) (G : PositionGauge) (L : ℕ) (s : (i : Fin L) → Fin (b i)) :
    Set (GaugedSpace b G) :=
  cylinder b L s

theorem mem_gCyl {L : ℕ} {s : (i : Fin L) → Fin (b i)} {x : GaugedSpace b G} :
    x ∈ gCyl b G L s ↔ ∀ i : Fin L, x i = s i := Iff.rfl

theorem isOpen_gCyl (L : ℕ) (s : (i : Fin L) → Fin (b i)) :
    IsOpen (gCyl b G L s) := by
  rw [Metric.isOpen_iff]
  intro x hx
  refine ⟨((G.g L : ℝ))⁻¹, inv_pos.mpr (G.pos_real L), fun y hy => ?_⟩
  rw [Metric.mem_ball] at hy
  have hagree : ∀ i, i ≤ L → y i = x i :=
    agree_of_gaugedDist_lt (x := y) (y := x) hy
  intro i
  exact (hagree i.val (le_of_lt i.isLt)).trans (hx i)

theorem isTopologicalBasis_gCyls :
    TopologicalSpace.IsTopologicalBasis
      {S : Set (GaugedSpace b G) |
        ∃ L : ℕ, ∃ s : (i : Fin L) → Fin (b i), S = gCyl b G L s} := by
  refine TopologicalSpace.isTopologicalBasis_of_isOpen_of_nhds ?_ ?_
  · rintro S ⟨L, s, rfl⟩
    exact isOpen_gCyl L s
  · intro x U hxU hU
    rw [Metric.isOpen_iff] at hU
    obtain ⟨ε, hε, hball⟩ := hU x hxU
    obtain ⟨n0, hn0⟩ := G.unbounded (Nat.ceil ε⁻¹)
    have hLε : ((G.g n0 : ℝ))⁻¹ < ε := by
      rw [inv_lt_comm₀ (G.pos_real n0) hε]
      calc ε⁻¹ ≤ (Nat.ceil ε⁻¹ : ℝ) := Nat.le_ceil _
        _ < (G.g n0 : ℝ) := by exact_mod_cast hn0
    refine ⟨gCyl b G n0 (CompletedSpace.take x n0), ⟨n0, _, rfl⟩, fun i => rfl, ?_⟩
    intro y hy
    apply hball
    rw [Metric.mem_ball]
    calc dist y x ≤ ((G.g n0 : ℝ))⁻¹ :=
          gaugedDist_le_of_agree (fun i hi => hy ⟨i, hi⟩)
      _ < ε := hLε

/-- Completion of a finite prefix by zeros. -/
def ofPrefix {L : ℕ} (s : PrefixSet b L) : CompletedSpace b :=
  fun i => if h : i < L then s ⟨i, h⟩ else ⟨0, b.pos i⟩

/-- The countable set of eventually-zero points, in the gauged space. -/
def gPadded (b : RadixSeq) (G : PositionGauge) : Set (GaugedSpace b G) :=
  ⋃ L : ℕ, Set.range (ofPrefix (b := b) (L := L))

theorem countable_gPadded (b : RadixSeq) (G : PositionGauge) :
    (gPadded b G).Countable :=
  Set.countable_iUnion fun _ => (Set.finite_range _).countable

theorem dense_gPadded : Dense (gPadded b G) := by
  rw [Metric.dense_iff]
  intro x r hr
  obtain ⟨n0, hn0⟩ := G.unbounded (Nat.ceil r⁻¹)
  have hLr : ((G.g n0 : ℝ))⁻¹ < r := by
    rw [inv_lt_comm₀ (G.pos_real n0) hr]
    calc r⁻¹ ≤ (Nat.ceil r⁻¹ : ℝ) := Nat.le_ceil _
      _ < (G.g n0 : ℝ) := by exact_mod_cast hn0
  refine ⟨ofPrefix (CompletedSpace.take x n0), ⟨?_, ?_⟩⟩
  · rw [Metric.mem_ball]
    refine lt_of_le_of_lt (gaugedDist_le_of_agree ?_) hLr
    exact fun i hi => dif_pos hi
  · exact Set.mem_iUnion.mpr ⟨n0, Set.mem_range_self _⟩

instance : TopologicalSpace.SeparableSpace (GaugedSpace b G) :=
  ⟨⟨gPadded b G, countable_gPadded b G, dense_gPadded⟩⟩

instance : SecondCountableTopology (GaugedSpace b G) :=
  UniformSpace.secondCountable_of_separable (GaugedSpace b G)

theorem generateFrom_gCyls_eq_borel :
    MeasurableSpace.generateFrom
      {S : Set (GaugedSpace b G) |
        ∃ L : ℕ, ∃ s : (i : Fin L) → Fin (b i), S = gCyl b G L s} =
    borel (GaugedSpace b G) := by
  apply le_antisymm
  · refine MeasurableSpace.generateFrom_le ?_
    rintro S ⟨L, s, rfl⟩
    exact MeasurableSpace.measurableSet_generateFrom (isOpen_gCyl L s)
  · rw [isTopologicalBasis_gCyls.borel_eq_generateFrom]

instance : BorelSpace (GaugedSpace b G) := by
  constructor
  show (instMeasurableSpaceCompletedSpace : MeasurableSpace (CompletedSpace b)) =
    borel (GaugedSpace b G)
  rw [pi_eq_generateFrom_cylinderSets b]
  exact generateFrom_gCyls_eq_borel

/-! ### The uniform measure rides along -/

/-- The corpus's uniform product measure, carried to the gauged space (the
measurable structure is literally the same instance). -/
noncomputable def gaugedMeasure (b : RadixSeq) (G : PositionGauge) :
    Measure (GaugedSpace b G) :=
  uniformProductMeasure b

instance : IsProbabilityMeasure (gaugedMeasure b G) :=
  uniformProductMeasure_isProbability b

theorem gaugedMeasure_gCyl (L : ℕ) (s : PrefixSet b L) :
    gaugedMeasure b G (gCyl b G L s) = ((placeValue b L : ℝ≥0∞))⁻¹ :=
  cylinder_measure L s

/-! ## R3: the Moran frame — the cover bound and the mass bound

`dimH` of a gauged space is squeezed by the count/gauge ratio: covers by
depth-`L` cylinders (each of `ediam ≤ g(L)⁻¹`, `placeValue L` of them) give
the upper criterion; the corpus's uniform product measure through the mass
distribution principle gives the lower criterion. -/

open Filter in
theorem ediam_gCyl_le (L : ℕ) (s : (i : Fin L) → Fin (b i)) :
    Metric.ediam (gCyl b G L s) ≤ ((G.g L : ℝ≥0∞))⁻¹ := by
  apply Metric.ediam_le
  intro x hx y hy
  rw [edist_dist]
  have hd : dist x y ≤ ((G.g L : ℝ))⁻¹ :=
    gaugedDist_le_of_agree (fun i hi => (hx ⟨i, hi⟩).trans (hy ⟨i, hi⟩).symm)
  calc ENNReal.ofReal (dist x y) ≤ ENNReal.ofReal ((G.g L : ℝ))⁻¹ :=
        ENNReal.ofReal_le_ofReal hd
    _ = ((G.g L : ℝ≥0∞))⁻¹ := by
        rw [ENNReal.ofReal_inv_of_pos (G.pos_real L), ENNReal.ofReal_natCast]

open Filter in
/-- **The cover half of the Moran frame.** If the count-times-radius-power
`B_L · g(L)^{-d}` vanishes, the `d`-dimensional Hausdorff measure of the
gauged space is zero.

**fdrs.md**: Theorem 116 (the Moran frame). -/
theorem hausdorffMeasure_univ_eq_zero {d : ℝ} (hd : 0 ≤ d)
    (h : Tendsto (fun L => (placeValue b L : ℝ≥0∞) * ((G.g L : ℝ≥0∞))⁻¹ ^ d)
      atTop (nhds 0)) :
    μH[d] (Set.univ : Set (GaugedSpace b G)) = 0 := by
  have hcov := Measure.hausdorffMeasure_le_liminf_sum d (Set.univ : Set (GaugedSpace b G))
    (fun L => ((G.g L : ℝ≥0∞))⁻¹) G.tendsto_inv_zero
    (fun L (s : PrefixSet b L) => gCyl b G L s)
    (Eventually.of_forall fun L s => ediam_gCyl_le L s)
    (Eventually.of_forall fun L x _ =>
      Set.mem_iUnion.mpr ⟨CompletedSpace.take x L, fun i => rfl⟩)
  refine le_antisymm (le_trans hcov ?_) (zero_le _)
  have hbound : ∀ L, (∑ s : PrefixSet b L, Metric.ediam (gCyl b G L s) ^ d)
      ≤ (placeValue b L : ℝ≥0∞) * ((G.g L : ℝ≥0∞))⁻¹ ^ d := by
    intro L
    calc ∑ s : PrefixSet b L, Metric.ediam (gCyl b G L s) ^ d
        ≤ ∑ _s : PrefixSet b L, ((G.g L : ℝ≥0∞))⁻¹ ^ d :=
          Finset.sum_le_sum fun s _ => ENNReal.rpow_le_rpow (ediam_gCyl_le L s) hd
      _ = (Fintype.card (PrefixSet b L) : ℝ≥0∞) * ((G.g L : ℝ≥0∞))⁻¹ ^ d := by
          rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul]
      _ = (placeValue b L : ℝ≥0∞) * ((G.g L : ℝ≥0∞))⁻¹ ^ d := by
          rw [prefixSet_card]
  calc liminf (fun L => ∑ s : PrefixSet b L, Metric.ediam (gCyl b G L s) ^ d) atTop
      ≤ liminf (fun L => (placeValue b L : ℝ≥0∞) * ((G.g L : ℝ≥0∞))⁻¹ ^ d) atTop :=
        liminf_le_liminf (Eventually.of_forall hbound)
    _ = 0 := h.liminf_eq

open Filter in
/-- The `dimH` form of the cover bound.

**fdrs.md**: Theorem 116 (the Moran frame — cover half). -/
theorem dimH_univ_le (d : ℝ≥0)
    (h : Tendsto (fun L => (placeValue b L : ℝ≥0∞) * ((G.g L : ℝ≥0∞))⁻¹ ^ (d : ℝ))
      atTop (nhds 0)) :
    dimH (Set.univ : Set (GaugedSpace b G)) ≤ d :=
  dimH_le_of_hausdorffMeasure_ne_top
    (by rw [hausdorffMeasure_univ_eq_zero d.coe_nonneg h]; exact ENNReal.zero_ne_top)

open Filter in
/-- **The mass half of the Moran frame.** If the uniform cylinder mass
`B_L⁻¹` is eventually dominated by the radius power `g(L)^{-d}`, then the
uniform product measure is dominated by `μH[d]` (the mass distribution
principle, with the corpus measure as the mass). -/
theorem gaugedMeasure_le_hausdorff {d : ℝ} (hd : 0 < d) (N : ℕ)
    (h : ∀ L, N ≤ L → (placeValue b L : ℝ≥0∞)⁻¹ ≤ (((G.g L : ℝ≥0∞))⁻¹) ^ d) :
    gaugedMeasure b G ≤ μH[d] := by
  refine Measure.le_hausdorffMeasure d _ ((2 * (G.g N : ℝ≥0∞)))⁻¹
    (ENNReal.inv_pos.mpr (ENNReal.mul_ne_top (by norm_num) (ENNReal.natCast_ne_top _))) ?_
  intro s hs
  rcases Set.eq_empty_or_nonempty s with rfl | ⟨x₀, hx₀⟩
  · simp
  by_cases hdiam : Metric.ediam s = 0
  · -- a null-diameter set is a subsingleton: it sits in every cylinder chain
    have hsub : ∀ L : ℕ, s ⊆ gCyl b G L (CompletedSpace.take x₀ L) := by
      intro L y hy
      have hyx : y = x₀ := by
        have hle := Metric.edist_le_ediam_of_mem hy hx₀
        rw [hdiam] at hle
        exact edist_le_zero.mp hle
      rw [hyx]
      exact fun i => rfl
    have hb : ∀ L : ℕ, gaugedMeasure b G s ≤ (placeValue b L : ℝ≥0∞)⁻¹ := fun L =>
      le_trans (measure_mono (hsub L)) (le_of_eq (gaugedMeasure_gCyl L _))
    have hμ : gaugedMeasure b G s = 0 :=
      le_antisymm (ge_of_tendsto' (PositionGauge.tendsto_inv_zero (placeValueGauge b)) hb)
        (zero_le _)
    rw [hμ]
    exact zero_le _
  · -- positive diameter: locate the critical depth by minimality
    have hex : ∃ L, ((G.g L : ℝ≥0∞))⁻¹ ≤ Metric.ediam s := by
      obtain ⟨n, hn⟩ := ENNReal.exists_nat_gt (ENNReal.inv_ne_top.mpr hdiam)
      obtain ⟨L, hL⟩ := G.unbounded n
      refine ⟨L, ?_⟩
      rw [ENNReal.inv_le_iff_inv_le]
      calc (Metric.ediam s)⁻¹ ≤ (n : ℝ≥0∞) := le_of_lt hn
        _ ≤ (G.g L : ℝ≥0∞) := by exact_mod_cast le_of_lt hL
    classical
    have hspec : ((G.g (Nat.find hex) : ℝ≥0∞))⁻¹ ≤ Metric.ediam s := Nat.find_spec hex
    have hNlt : N < Nat.find hex := by
      rw [Nat.lt_find_iff]
      intro k hk hcon
      have h1 : ((G.g N : ℝ≥0∞))⁻¹ ≤ ((G.g k : ℝ≥0∞))⁻¹ :=
        ENNReal.inv_le_inv' (by exact_mod_cast G.mono hk)
      have h2 : ((2 : ℝ≥0∞) * (G.g N : ℝ≥0∞))⁻¹ < ((G.g N : ℝ≥0∞))⁻¹ := by
        apply ENNReal.inv_lt_inv'
        calc (G.g N : ℝ≥0∞) < (G.g N : ℝ≥0∞) + (G.g N : ℝ≥0∞) :=
              ENNReal.lt_add_right (ENNReal.natCast_ne_top _)
                (by exact_mod_cast (G.pos N).ne')
          _ = 2 * (G.g N : ℝ≥0∞) := (two_mul _).symm
      exact absurd (le_trans h1 (le_trans hcon hs)) (not_le.mpr h2)
    have hpos : 0 < Nat.find hex := lt_of_le_of_lt (Nat.zero_le N) hNlt
    have hmin : Metric.ediam s < ((G.g (Nat.find hex - 1) : ℝ≥0∞))⁻¹ :=
      not_le.mp (Nat.find_min hex (Nat.sub_lt hpos Nat.one_pos))
    have hsub : s ⊆ gCyl b G (Nat.find hex) (CompletedSpace.take x₀ (Nat.find hex)) := by
      intro y hy i
      have hdist : edist y x₀ < ((G.g (Nat.find hex - 1) : ℝ≥0∞))⁻¹ :=
        lt_of_le_of_lt (Metric.edist_le_ediam_of_mem hy hx₀) hmin
      have hreal : dist y x₀ < ((G.g (Nat.find hex - 1) : ℝ))⁻¹ := by
        rw [edist_dist] at hdist
        have := hdist
        rw [show ((G.g (Nat.find hex - 1) : ℝ≥0∞))⁻¹
            = ENNReal.ofReal ((G.g (Nat.find hex - 1) : ℝ))⁻¹ by
          rw [ENNReal.ofReal_inv_of_pos (G.pos_real _), ENNReal.ofReal_natCast]] at this
        exact (ENNReal.ofReal_lt_ofReal_iff_of_nonneg dist_nonneg).mp this
      exact agree_of_gaugedDist_lt (x := y) (y := x₀) hreal i.val
        (Nat.le_pred_of_lt i.isLt)
    calc gaugedMeasure b G s
        ≤ gaugedMeasure b G (gCyl b G (Nat.find hex) (CompletedSpace.take x₀ (Nat.find hex))) :=
          measure_mono hsub
      _ = (placeValue b (Nat.find hex) : ℝ≥0∞)⁻¹ := gaugedMeasure_gCyl _ _
      _ ≤ ((G.g (Nat.find hex) : ℝ≥0∞))⁻¹ ^ d := h _ (le_of_lt hNlt)
      _ ≤ Metric.ediam s ^ d := ENNReal.rpow_le_rpow hspec (le_of_lt hd)

open Filter in
/-- The `dimH` form of the mass bound.

**fdrs.md**: Theorem 116 (the Moran frame — mass half). -/
theorem le_dimH_univ (d : ℝ≥0) (N : ℕ)
    (h : ∀ L, N ≤ L →
      (placeValue b L : ℝ≥0∞)⁻¹ ≤ (((G.g L : ℝ≥0∞))⁻¹) ^ (d : ℝ)) :
    (d : ℝ≥0∞) ≤ dimH (Set.univ : Set (GaugedSpace b G)) := by
  rcases eq_or_ne d 0 with rfl | hne
  · simp
  have hd : (0 : ℝ) < (d : ℝ) := by exact_mod_cast pos_of_ne_zero hne
  refine le_dimH_of_hausdorffMeasure_ne_zero (fun h0 => ?_)
  have h1 : gaugedMeasure b G Set.univ ≤ μH[(d : ℝ)] (Set.univ : Set (GaugedSpace b G)) :=
    Measure.le_iff'.mp (gaugedMeasure_le_hausdorff hd N h) Set.univ
  rw [h0, measure_univ] at h1
  exact absurd h1 (by norm_num)

end GaugedSpace

/-! ## R4: every number line is one-dimensional -/

theorem two_pow_le_placeValue (b : RadixSeq) (L : ℕ) : 2 ^ L ≤ placeValue b L := by
  induction L with
  | zero => simp [placeValue.zero]
  | succ n ih =>
    rw [pow_succ, placeValue.succ]
    exact Nat.mul_le_mul ih (b.ge_two n)

/-- The identity is an isometry between the place-value-gauged space and the
canonical completed space: the designed distance at the canonical gauge *is*
Definition 9's ultrametric. -/
noncomputable def canonicalIsometry (b : RadixSeq) :
    GaugedSpace b (placeValueGauge b) ≃ᵢ CompletedSpace b where
  toEquiv := Equiv.refl _
  isometry_toFun := Isometry.of_dist_eq fun _ _ => rfl

/-- **Every number line is one-dimensional.** Under the canonical gauge —
condition (C4) of Theorem 43, the gauge locked to the tree — the completed
mixed-radix space has Hausdorff dimension exactly `1`, for *every* radix
schedule. Being realizable as a number system pins the dimension.

**fdrs.md**: Theorem 117 (every number line is one-dimensional). -/
theorem dimH_completedSpace_eq_one (b : RadixSeq) :
    dimH (Set.univ : Set (CompletedSpace b)) = 1 := by
  rw [← IsometryEquiv.dimH_univ (canonicalIsometry b)]
  apply le_antisymm
  · -- cover half: for every d > 1 the count-radius product vanishes
    by_contra hlt
    push_neg at hlt
    obtain ⟨d, hd1, hdd⟩ := ENNReal.lt_iff_exists_nnreal_btwn.mp hlt
    refine absurd hdd (not_lt.mpr (GaugedSpace.dimH_univ_le d ?_))
    have hd1' : (1 : ℝ) < (d : ℝ) := by exact_mod_cast hd1
    have hgeo : ((2 : ℝ≥0∞) ^ ((1 : ℝ) - (d : ℝ))) < 1 :=
      ENNReal.rpow_lt_one_of_one_lt_of_neg (by norm_num) (by linarith)
    have key : ∀ L, (placeValue b L : ℝ≥0∞) * ((placeValue b L : ℝ≥0∞))⁻¹ ^ (d : ℝ)
        ≤ ((2 : ℝ≥0∞) ^ ((1 : ℝ) - (d : ℝ))) ^ L := by
      intro L
      have hB0 : (placeValue b L : ℝ≥0∞) ≠ 0 :=
        Nat.cast_ne_zero.mpr (placeValue.ne_zero L)
      have hBtop : (placeValue b L : ℝ≥0∞) ≠ ⊤ := ENNReal.natCast_ne_top _
      have hform : (placeValue b L : ℝ≥0∞) * ((placeValue b L : ℝ≥0∞))⁻¹ ^ (d : ℝ)
          = (placeValue b L : ℝ≥0∞) ^ ((1 : ℝ) - (d : ℝ)) := by
        rw [show (1 : ℝ) - (d : ℝ) = 1 + -(d : ℝ) by ring,
          ENNReal.rpow_add 1 (-(d : ℝ)) hB0 hBtop, ENNReal.rpow_one,
          ENNReal.rpow_neg, ← ENNReal.inv_rpow]
      have hcast : ((2 : ℝ≥0∞)) ^ L ≤ (placeValue b L : ℝ≥0∞) := by
        calc ((2 : ℝ≥0∞)) ^ L = ((2 ^ L : ℕ) : ℝ≥0∞) := by push_cast; rfl
          _ ≤ _ := Nat.cast_le.mpr (two_pow_le_placeValue b L)
      have hflip : (placeValue b L : ℝ≥0∞) ^ ((1 : ℝ) - (d : ℝ))
          ≤ ((2 : ℝ≥0∞) ^ L) ^ ((1 : ℝ) - (d : ℝ)) := by
        rw [show (1 : ℝ) - (d : ℝ) = -((d : ℝ) - 1) by ring,
          ENNReal.rpow_neg, ENNReal.rpow_neg]
        exact ENNReal.inv_le_inv'
          (ENNReal.rpow_le_rpow hcast (by linarith))
      calc (placeValue b L : ℝ≥0∞) * ((placeValue b L : ℝ≥0∞))⁻¹ ^ (d : ℝ)
          = (placeValue b L : ℝ≥0∞) ^ ((1 : ℝ) - (d : ℝ)) := hform
        _ ≤ ((2 : ℝ≥0∞) ^ L) ^ ((1 : ℝ) - (d : ℝ)) := hflip
        _ = ((2 : ℝ≥0∞) ^ ((1 : ℝ) - (d : ℝ))) ^ L := by
            rw [← ENNReal.rpow_natCast (2 : ℝ≥0∞) L,
              ← ENNReal.rpow_natCast ((2 : ℝ≥0∞) ^ ((1 : ℝ) - (d : ℝ))) L,
              ← ENNReal.rpow_mul, ← ENNReal.rpow_mul,
              mul_comm ((L : ℕ) : ℝ) ((1 : ℝ) - (d : ℝ))]
    exact tendsto_of_tendsto_of_tendsto_of_le_of_le' tendsto_const_nhds
      (ENNReal.tendsto_pow_atTop_nhds_zero_of_lt_one hgeo)
      (Filter.Eventually.of_forall fun L => zero_le _)
      (Filter.Eventually.of_forall key)
  · have h1 := GaugedSpace.le_dimH_univ (b := b) (G := placeValueGauge b) 1 0 ?_
    · simpa using h1
    · intro L _
      simp only [NNReal.coe_one, ENNReal.rpow_one]
      exact le_refl _

/-! ## R5: the gauge programs the dimension

On the binary tree (counts fixed at `2^L`), designing the gauge schedule
moves the dimension anywhere in `[0, ∞]`: `2^⌈L/r⌉` realizes `r`; the
factorial gauge (§6.4.3(3)) collapses to `0`; the polynomial gauge
(§6.4.3(2)) blows up to `∞`. -/

/-- The binary radix sequence. -/
def binarySeq : RadixSeq := ⟨fun _ => 2, fun _ => le_rfl⟩

theorem placeValue_binary (L : ℕ) : placeValue binarySeq L = 2 ^ L := by
  induction L with
  | zero => rfl
  | succ n ih => rw [placeValue.succ, ih, pow_succ]; rfl

/-! ### ENNReal power-of-two bookkeeping -/

theorem two_ne_top : (2 : ℝ≥0∞) ≠ ⊤ := by norm_num

theorem natCast_two_pow (a : ℕ) :
    ((2 ^ a : ℕ) : ℝ≥0∞) = (2 : ℝ≥0∞) ^ ((a : ℕ) : ℝ) := by
  push_cast
  rw [ENNReal.rpow_natCast]

theorem two_pow_inv (a : ℕ) :
    (((2 ^ a : ℕ) : ℝ≥0∞))⁻¹ = (2 : ℝ≥0∞) ^ (-((a : ℕ) : ℝ)) := by
  rw [natCast_two_pow, ← ENNReal.rpow_neg]

theorem two_pow_inv_rpow (a : ℕ) (d : ℝ) :
    (((2 ^ a : ℕ) : ℝ≥0∞))⁻¹ ^ d = (2 : ℝ≥0∞) ^ (-(d * ((a : ℕ) : ℝ))) := by
  rw [two_pow_inv, ← ENNReal.rpow_mul]
  congr 1
  ring

theorem two_rpow_le (x y : ℝ) (h : x ≤ y) : (2 : ℝ≥0∞) ^ x ≤ (2 : ℝ≥0∞) ^ y :=
  ENNReal.rpow_le_rpow_of_exponent_le (by norm_num) h

theorem two_rpow_add (x y : ℝ) :
    (2 : ℝ≥0∞) ^ (x + y) = (2 : ℝ≥0∞) ^ x * (2 : ℝ≥0∞) ^ y :=
  ENNReal.rpow_add x y (by norm_num) two_ne_top

/-! ### The designed gauge `2^⌈L/r⌉` -/

/-- The binary gauge schedule realizing a prescribed dimension `r`. -/
noncomputable def designedGauge (r : ℝ≥0) (hr : 0 < r) : PositionGauge where
  g := fun n => 2 ^ (Nat.ceil ((n : ℝ≥0) / r))
  one_le := fun _ => Nat.one_le_two_pow
  mono := fun m n hmn =>
    Nat.pow_le_pow_right (by norm_num)
      (Nat.ceil_mono (by gcongr))
  unbounded := fun M => by
    obtain ⟨n, hn⟩ := exists_nat_ge ((M : ℝ≥0) * r)
    refine ⟨n + 1, ?_⟩
    have h1 : (M : ℝ≥0) < ((n + 1 : ℕ) : ℝ≥0) / r := by
      rw [lt_div_iff₀ hr]
      calc (M : ℝ≥0) * r ≤ (n : ℝ≥0) := hn
        _ < ((n + 1 : ℕ) : ℝ≥0) := by exact_mod_cast Nat.lt_succ_self n
    have h2 : M < Nat.ceil (((n + 1 : ℕ) : ℝ≥0) / r) := by
      have h3 : (M : ℝ≥0) < (Nat.ceil (((n + 1 : ℕ) : ℝ≥0) / r) : ℝ≥0) :=
        lt_of_lt_of_le h1 (Nat.le_ceil _)
      exact_mod_cast h3
    calc M < Nat.ceil (((n + 1 : ℕ) : ℝ≥0) / r) := h2
      _ < 2 ^ Nat.ceil (((n + 1 : ℕ) : ℝ≥0) / r) := Nat.lt_two_pow_self

theorem designedGauge_g (r : ℝ≥0) (hr : 0 < r) (n : ℕ) :
    (designedGauge r hr).g n = 2 ^ (Nat.ceil ((n : ℝ≥0) / r)) := rfl

/-- The ceiling schedule dominates `L/r` … -/
theorem le_ceil_div_real (r : ℝ≥0) (L : ℕ) :
    (L : ℝ) / (r : ℝ) ≤ (Nat.ceil ((L : ℝ≥0) / r) : ℝ) := by
  have h := Nat.le_ceil ((L : ℝ≥0) / r)
  rw [← NNReal.coe_le_coe] at h
  push_cast at h
  exact h

/-- … and stays within one unit of it. -/
theorem ceil_div_real_lt (r : ℝ≥0) (L : ℕ) :
    (Nat.ceil ((L : ℝ≥0) / r) : ℝ) < (L : ℝ) / (r : ℝ) + 1 := by
  have h := Nat.ceil_lt_add_one (zero_le ((L : ℝ≥0) / r))
  rw [← NNReal.coe_lt_coe] at h
  push_cast at h
  exact h

/-- **The gauge programs the dimension**: on the binary tree the designed
schedule `g(L) = 2^⌈L/r⌉` realizes Hausdorff dimension exactly `r`, for
every prescribed `r > 0`. The "r" of the space lives on the gauge axis.

**fdrs.md**: Theorem 118 (the gauge programs the dimension). -/
theorem dimH_designedGauge (r : ℝ≥0) (hr : 0 < r) :
    dimH (Set.univ : Set (GaugedSpace binarySeq (designedGauge r hr))) = (r : ℝ≥0∞) := by
  have hrR : (0 : ℝ) < (r : ℝ) := hr
  apply le_antisymm
  · -- cover half: for every d > r the count-radius product vanishes
    by_contra hlt
    push_neg at hlt
    obtain ⟨d, hd1, hdd⟩ := ENNReal.lt_iff_exists_nnreal_btwn.mp hlt
    refine absurd hdd (not_lt.mpr (GaugedSpace.dimH_univ_le d ?_))
    have hrd : (r : ℝ) < (d : ℝ) := by exact_mod_cast hd1
    have hdpos : (0 : ℝ) < (d : ℝ) := lt_trans hrR hrd
    have hexp_neg : (1 : ℝ) - (d : ℝ) / (r : ℝ) < 0 := by
      rw [sub_neg, lt_div_iff₀ hrR]
      linarith
    have hgeo : ((2 : ℝ≥0∞) ^ ((1 : ℝ) - (d : ℝ) / (r : ℝ))) < 1 :=
      ENNReal.rpow_lt_one_of_one_lt_of_neg (by norm_num) hexp_neg
    have key : ∀ L, (placeValue binarySeq L : ℝ≥0∞) *
        (((designedGauge r hr).g L : ℝ≥0∞))⁻¹ ^ (d : ℝ)
        ≤ ((2 : ℝ≥0∞) ^ ((1 : ℝ) - (d : ℝ) / (r : ℝ))) ^ L := by
      intro L
      have hle : (L : ℝ) / (r : ℝ) ≤ ((Nat.ceil ((L : ℝ≥0) / r) : ℕ) : ℝ) :=
        le_ceil_div_real r L
      have h1 : (d : ℝ) / (r : ℝ) * (L : ℝ)
          ≤ (d : ℝ) * ((Nat.ceil ((L : ℝ≥0) / r) : ℕ) : ℝ) := by
        have := mul_le_mul_of_nonneg_left hle (le_of_lt hdpos)
        calc (d : ℝ) / (r : ℝ) * (L : ℝ) = (d : ℝ) * ((L : ℝ) / (r : ℝ)) := by ring
          _ ≤ _ := this
      have hexp : (L : ℝ) + -((d : ℝ) * ((Nat.ceil ((L : ℝ≥0) / r) : ℕ) : ℝ))
          ≤ ((1 : ℝ) - (d : ℝ) / (r : ℝ)) * (L : ℝ) := by nlinarith [h1]
      calc (placeValue binarySeq L : ℝ≥0∞) *
            (((designedGauge r hr).g L : ℝ≥0∞))⁻¹ ^ (d : ℝ)
          = ((2 ^ L : ℕ) : ℝ≥0∞) *
            (2 : ℝ≥0∞) ^ (-((d : ℝ) * ((Nat.ceil ((L : ℝ≥0) / r) : ℕ) : ℝ))) := by
            rw [placeValue_binary, designedGauge_g, two_pow_inv_rpow]
        _ = (2 : ℝ≥0∞) ^ ((L : ℕ) : ℝ) *
            (2 : ℝ≥0∞) ^ (-((d : ℝ) * ((Nat.ceil ((L : ℝ≥0) / r) : ℕ) : ℝ))) := by
            rw [natCast_two_pow]
        _ = (2 : ℝ≥0∞) ^ (((L : ℕ) : ℝ) +
            -((d : ℝ) * ((Nat.ceil ((L : ℝ≥0) / r) : ℕ) : ℝ))) := (two_rpow_add _ _).symm
        _ ≤ (2 : ℝ≥0∞) ^ (((1 : ℝ) - (d : ℝ) / (r : ℝ)) * (L : ℝ)) := two_rpow_le _ _ hexp
        _ = ((2 : ℝ≥0∞) ^ ((1 : ℝ) - (d : ℝ) / (r : ℝ))) ^ L := by
            rw [ENNReal.rpow_mul, ENNReal.rpow_natCast]
    exact tendsto_of_tendsto_of_tendsto_of_le_of_le' tendsto_const_nhds
      (ENNReal.tendsto_pow_atTop_nhds_zero_of_lt_one hgeo)
      (Filter.Eventually.of_forall fun L => zero_le _)
      (Filter.Eventually.of_forall key)
  · -- mass half: for every d < r the cylinder mass is eventually dominated
    by_contra hlt
    obtain ⟨d, hd1, hd2⟩ := ENNReal.lt_iff_exists_nnreal_btwn.mp (not_le.mp hlt)
    have hdr : (d : ℝ) < (r : ℝ) := by exact_mod_cast hd2
    have hdnn : (0 : ℝ) ≤ (d : ℝ) := d.coe_nonneg
    have hden : (0 : ℝ) < 1 - (d : ℝ) / (r : ℝ) := by
      rw [sub_pos, div_lt_iff₀ hrR]
      linarith
    obtain ⟨N, hN⟩ := exists_nat_ge ((d : ℝ) / (1 - (d : ℝ) / (r : ℝ)))
    have hmass : ∀ L, N ≤ L → (placeValue binarySeq L : ℝ≥0∞)⁻¹
        ≤ ((((designedGauge r hr).g L : ℝ≥0∞))⁻¹) ^ ((d : ℝ≥0) : ℝ) := by
      intro L hL
      have hLR : ((d : ℝ) / (1 - (d : ℝ) / (r : ℝ))) ≤ (L : ℝ) :=
        le_trans hN (by exact_mod_cast hL)
      have hceil : ((Nat.ceil ((L : ℝ≥0) / r) : ℕ) : ℝ) < (L : ℝ) / (r : ℝ) + 1 :=
        ceil_div_real_lt r L
      have hkey : (d : ℝ) * ((Nat.ceil ((L : ℝ≥0) / r) : ℕ) : ℝ) ≤ (L : ℝ) := by
        have h1 : (d : ℝ) * ((Nat.ceil ((L : ℝ≥0) / r) : ℕ) : ℝ)
            ≤ (d : ℝ) / (r : ℝ) * (L : ℝ) + (d : ℝ) := by
          calc (d : ℝ) * ((Nat.ceil ((L : ℝ≥0) / r) : ℕ) : ℝ)
              ≤ (d : ℝ) * ((L : ℝ) / (r : ℝ) + 1) :=
                mul_le_mul_of_nonneg_left (le_of_lt hceil) hdnn
            _ = (d : ℝ) / (r : ℝ) * (L : ℝ) + (d : ℝ) := by ring
        have h2 : (d : ℝ) ≤ (1 - (d : ℝ) / (r : ℝ)) * (L : ℝ) :=
          (div_le_iff₀' hden).mp hLR
        have hexpand : (1 - (d : ℝ) / (r : ℝ)) * (L : ℝ)
            = (L : ℝ) - (d : ℝ) / (r : ℝ) * (L : ℝ) := by ring
        linarith [h1, h2, hexpand]
      rw [placeValue_binary, designedGauge_g, two_pow_inv, two_pow_inv_rpow]
      exact two_rpow_le _ _ (by linarith)
    exact absurd (GaugedSpace.le_dimH_univ d N hmass) (not_le.mpr hd1)

/-! ### The factorial gauge — §6.4.3(3): the dimension collapses to `0` -/

/-- The factorial gauge. -/
def factorialGauge : PositionGauge where
  g := fun n => Nat.factorial n
  one_le := fun n => Nat.factorial_pos n
  mono := fun _ _ h => Nat.factorial_le h
  unbounded := fun M =>
    ⟨M + 1, lt_of_lt_of_le (Nat.lt_succ_self M) (Nat.self_le_factorial _)⟩

theorem factorialGauge_g (n : ℕ) : factorialGauge.g n = Nat.factorial n := rfl

/-- **Super-exponential gauges kill the dimension**: the factorial schedule
over the binary tree has Hausdorff dimension `0` (Example 6.4.3(3)).

**fdrs.md**: Proposition 153 (the §6.4.3 growth regimes, computed). -/
theorem dimH_factorialGauge_eq_zero :
    dimH (Set.univ : Set (GaugedSpace binarySeq factorialGauge)) = 0 := by
  refine le_antisymm ?_ (zero_le _)
  by_contra hlt
  push_neg at hlt
  obtain ⟨d, hd0, hdd⟩ := ENNReal.lt_iff_exists_nnreal_btwn.mp hlt
  refine absurd hdd (not_lt.mpr (GaugedSpace.dimH_univ_le d ?_))
  have hd0' : (0 : ℝ) < (d : ℝ) := by exact_mod_cast hd0
  set c : ℝ := (2 : ℝ) ^ ((1 : ℝ) / (d : ℝ)) with hc
  have hcpos : (0 : ℝ) < c := Real.rpow_pos_of_pos (by norm_num) _
  have hreal : Filter.Tendsto (fun L : ℕ => (c ^ L / (Nat.factorial L : ℝ)) ^ (d : ℝ))
      Filter.atTop (nhds 0) := by
    have h0 := FloorSemiring.tendsto_pow_div_factorial_atTop (K := ℝ) c
    have h1 := h0.rpow_const (Or.inr (le_of_lt hd0'))
    rwa [Real.zero_rpow (ne_of_gt hd0')] at h1
  have henn := ENNReal.tendsto_ofReal hreal
  rw [ENNReal.ofReal_zero] at henn
  refine henn.congr fun L => ?_
  have hfacpos : (0 : ℝ) < (Nat.factorial L : ℝ) := by exact_mod_cast Nat.factorial_pos L
  have hcLpos : (0 : ℝ) < c ^ L := pow_pos hcpos L
  have hnum : (c ^ L) ^ (d : ℝ) = (2 : ℝ) ^ L := by
    rw [← Real.rpow_natCast c L, ← Real.rpow_mul (le_of_lt hcpos), hc,
      ← Real.rpow_mul (by norm_num : (0 : ℝ) ≤ 2),
      show (1 : ℝ) / (d : ℝ) * ((L : ℝ) * (d : ℝ)) = (L : ℝ) by
        rw [mul_comm (L : ℝ) (d : ℝ), ← mul_assoc, one_div,
          inv_mul_cancel₀ (ne_of_gt hd0'), one_mul],
      Real.rpow_natCast]
  rw [Real.div_rpow (le_of_lt hcLpos) (le_of_lt hfacpos), hnum,
    ENNReal.ofReal_div_of_pos (Real.rpow_pos_of_pos hfacpos _),
    ← ENNReal.ofReal_rpow_of_pos hfacpos, ENNReal.ofReal_natCast,
    placeValue_binary, factorialGauge_g, ENNReal.inv_rpow, div_eq_mul_inv]
  congr 1
  rw [← ENNReal.ofReal_natCast (2 ^ L)]
  congr 1
  push_cast
  ring

/-! ### The polynomial gauge — §6.4.3(2): the dimension blows up to `∞` -/

/-- The polynomial (linear) gauge `g(n) = n + 1` — Example 6.4.3(2) with
`ω(s) = |s| + 1`. -/
def polyGauge : PositionGauge where
  g := fun n => n + 1
  one_le := fun n => Nat.succ_le_succ (Nat.zero_le n)
  mono := fun _ _ h => Nat.succ_le_succ h
  unbounded := fun M => ⟨M, Nat.lt_succ_self M⟩

theorem polyGauge_g (n : ℕ) : polyGauge.g n = n + 1 := rfl

/-- Eventually `(L+1)^k ≤ 2^L`: every polynomial loses to the binary count. -/
theorem eventually_pow_le_two_pow (k : ℕ) :
    ∃ N, ∀ L, N ≤ L → (L + 1) ^ k ≤ 2 ^ L := by
  have hsum : Summable (fun n : ℕ => ‖((n : ℝ) ^ k * (1 / 2 : ℝ) ^ n)‖) :=
    summable_norm_pow_mul_geometric_of_norm_lt_one k
      (by rw [Real.norm_eq_abs, abs_of_pos (by norm_num : (0:ℝ) < 1/2)]; norm_num)
  have htend : Filter.Tendsto (fun n : ℕ => (n : ℝ) ^ k * (1 / 2 : ℝ) ^ n)
      Filter.atTop (nhds 0) := hsum.of_norm.tendsto_atTop_zero
  have hpos : (0 : ℝ) < ((1 : ℝ) / 2) ^ k := by positivity
  have hev := htend.eventually_lt_const hpos
  rw [Filter.eventually_atTop] at hev
  obtain ⟨N₀, hN₀⟩ := hev
  refine ⟨max N₀ 1, fun L hL => ?_⟩
  have hL0 : N₀ ≤ L := le_trans (le_max_left _ _) hL
  have hL1 : (1 : ℝ) ≤ (L : ℝ) := by
    exact_mod_cast le_trans (le_max_right N₀ 1) hL
  have hp2L : (0 : ℝ) < 2 ^ L := by positivity
  have hp2k : (0 : ℝ) < 2 ^ k := by positivity
  have h1 : ((L : ℝ)) ^ k * (1 / 2 : ℝ) ^ L < (1 / 2 : ℝ) ^ k := hN₀ L hL0
  rw [div_pow, div_pow, one_pow, one_pow] at h1
  have h2 : ((L : ℝ)) ^ k * 2 ^ k < 2 ^ L := by
    rw [mul_one_div, div_lt_div_iff₀ hp2L hp2k, one_mul] at h1
    exact h1
  have h4 : ((L + 1 : ℕ) : ℝ) ^ k < (2 : ℝ) ^ L := by
    calc ((L + 1 : ℕ) : ℝ) ^ k ≤ ((2 : ℝ) * (L : ℝ)) ^ k := by
          apply pow_le_pow_left₀ (by positivity)
          push_cast
          linarith
      _ = 2 ^ k * (L : ℝ) ^ k := by rw [mul_pow]
      _ < 2 ^ L := by nlinarith [h2]
  exact_mod_cast h4.le

/-- **Sub-exponential gauges blow the dimension up**: the polynomial schedule
over the binary tree has Hausdorff dimension `∞` (Example 6.4.3(2)).

**fdrs.md**: Proposition 153 (the §6.4.3 growth regimes, computed). -/
theorem dimH_polyGauge_eq_top :
    dimH (Set.univ : Set (GaugedSpace binarySeq polyGauge)) = ⊤ := by
  refine top_unique ?_
  by_contra hlt
  push_neg at hlt
  obtain ⟨d, hd1, -⟩ := ENNReal.lt_iff_exists_nnreal_btwn.mp hlt
  obtain ⟨N, hN⟩ := eventually_pow_le_two_pow (Nat.ceil d)
  have hmass : ∀ L, N ≤ L → (placeValue binarySeq L : ℝ≥0∞)⁻¹
      ≤ (((polyGauge.g L : ℝ≥0∞))⁻¹) ^ ((d : ℝ≥0) : ℝ) := by
    intro L hL
    have hbase : ((polyGauge.g L : ℝ≥0∞))⁻¹ ≤ 1 :=
      ENNReal.inv_le_one.mpr (by exact_mod_cast polyGauge.one_le L)
    have hdk : ((d : ℝ≥0) : ℝ) ≤ ((Nat.ceil d : ℕ) : ℝ) := by
      exact_mod_cast Nat.le_ceil d
    refine le_trans ?_ (ENNReal.rpow_le_rpow_of_exponent_ge hbase hdk)
    rw [placeValue_binary, ENNReal.inv_rpow, ENNReal.rpow_natCast]
    apply ENNReal.inv_le_inv'
    calc ((polyGauge.g L : ℕ) : ℝ≥0∞) ^ (Nat.ceil d)
        = (((L + 1) ^ (Nat.ceil d) : ℕ) : ℝ≥0∞) := by rw [polyGauge_g]; push_cast; rfl
      _ ≤ ((2 ^ L : ℕ) : ℝ≥0∞) := Nat.cast_le.mpr (hN L hL)
  exact absurd (GaugedSpace.le_dimH_univ d N hmass) (not_le.mpr hd1)

end FdrsFormal.Modes.SyntheticPlace.Dimension
