/-
Copyright 2026 Hyphaeic SPC.

Licensed under the Hyphaeic Public License, Version 1.0 (the
"License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

https://github.com/hyphaeic/hpl

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.

# Extended search certificates (generated)

Generated by `tools/radix-circuit-search --lean-ext` (`--max 512`). For every length
`2 ≤ N ≤ 512` where the extended plan (with Rader and Bluestein) beats the grammar,
the plan is checked by Corollary 38 (`XPlan.certify`): validity (including the
primality of every Rader length), length and cost are evaluated by the kernel
(`decide +kernel`), so the reported gate count is a theorem. Lengths not listed
are covered by `SearchCertificates.lean`. Do not edit by hand; regenerate with the
tool.
-/

import FdrsFormal.NumberTheory.Characters.RaderBluestein

namespace FdrsFormal.NumberTheory.Characters.FourierCircuit.SearchCertificatesExt

open FdrsFormal.NumberTheory.Characters.FourierCircuit

theorem xdft_13 : ∃ C : Circuit 13, C.Computes (fourierMatrix 13) ∧ C.size = 143 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.ct .two .two))) 13 143
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_17 : ∃ C : Circuit 17, C.Computes (fourierMatrix 17) ∧ C.size = 195 :=
  XPlan.certify (.rader (.ct .two (.ct .two (.ct .two .two)))) 17 195
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_19 : ∃ C : Circuit 19, C.Computes (fourierMatrix 19) ∧ C.size = 281 :=
  XPlan.certify (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))) 19 281
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_26 : ∃ C : Circuit 26, C.Computes (fourierMatrix 26) ∧ C.size = 312 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.pair 1) (.ct .two .two)))) 26 312
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_29 : ∃ C : Circuit 29, C.Computes (fourierMatrix 29) ∧ C.size = 567 :=
  XPlan.certify (.rader (.pfa (.ct .two .two) (.pair 3))) 29 567
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_31 : ∃ C : Circuit 31, C.Computes (fourierMatrix 31) ∧ C.size = 569 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.pair 2)))) 31 569
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_34 : ∃ C : Circuit 34, C.Computes (fourierMatrix 34) ∧ C.size = 424 :=
  XPlan.certify (.pfa .two (.rader (.ct .two (.ct .two (.ct .two .two))))) 34 424
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_37 : ∃ C : Circuit 37, C.Computes (fourierMatrix 37) ∧ C.size = 651 :=
  XPlan.certify (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1)))) 37 651
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_38 : ∃ C : Circuit 38, C.Computes (fourierMatrix 38) ∧ C.size = 600 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 38 600
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_39 : ∃ C : Circuit 39, C.Computes (fourierMatrix 39) ∧ C.size = 533 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.ct .two .two)))) 39 533
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_41 : ∃ C : Circuit 41, C.Computes (fourierMatrix 41) ∧ C.size = 755 :=
  XPlan.certify (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two)))) 41 755
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_43 : ∃ C : Circuit 43, C.Computes (fourierMatrix 43) ∧ C.size = 969 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.pair 3)))) 43 969
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_47 : ∃ C : Circuit 47, C.Computes (fourierMatrix 47) ∧ C.size = 1954 :=
  XPlan.certify (.bluestein 47 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two)))))) 47 1954
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_51 : ∃ C : Circuit 51, C.Computes (fourierMatrix 51) ∧ C.size = 721 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.ct .two (.ct .two (.ct .two .two))))) 51 721
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_52 : ∃ C : Circuit 52, C.Computes (fourierMatrix 52) ∧ C.size = 689 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two)))) 52 689
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_53 : ∃ C : Circuit 53, C.Computes (fourierMatrix 53) ∧ C.size = 1483 :=
  XPlan.certify (.rader (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two))))) 53 1483
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_57 : ∃ C : Circuit 57, C.Computes (fourierMatrix 57) ∧ C.size = 995 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 57 995
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_58 : ∃ C : Circuit 58, C.Computes (fourierMatrix 58) ∧ C.size = 1192 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.ct .two .two) (.pair 3)))) 58 1192
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_59 : ∃ C : Circuit 59, C.Computes (fourierMatrix 59) ∧ C.size = 2501 :=
  XPlan.certify (.rader (.pfa .two (.rader (.pfa (.ct .two .two) (.pair 3))))) 59 2501
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_61 : ∃ C : Circuit 61, C.Computes (fourierMatrix 61) ∧ C.size = 1287 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pair 2)))) 61 1287
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_62 : ∃ C : Circuit 62, C.Computes (fourierMatrix 62) ∧ C.size = 1200 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))) 62 1200
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_65 : ∃ C : Circuit 65, C.Computes (fourierMatrix 65) ∧ C.size = 1027 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa (.pair 1) (.ct .two .two)))) 65 1027
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_67 : ∃ C : Circuit 67, C.Computes (fourierMatrix 67) ∧ C.size = 2057 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.pair 5)))) 67 2057
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_68 : ∃ C : Circuit 68, C.Computes (fourierMatrix 68) ∧ C.size = 933 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.ct .two (.ct .two (.ct .two .two))))) 68 933
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_71 : ∃ C : Circuit 71, C.Computes (fourierMatrix 71) ∧ C.size = 1913 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 2) (.pair 3)))) 71 1913
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_73 : ∃ C : Circuit 73, C.Computes (fourierMatrix 73) ∧ C.size = 1491 :=
  XPlan.certify (.rader (.ct (.pfa .two (.pair 1)) (.pfa (.pair 1) (.ct .two .two)))) 73 1491
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_74 : ∃ C : Circuit 74, C.Computes (fourierMatrix 74) ∧ C.size = 1376 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))) 74 1376
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_76 : ∃ C : Circuit 76, C.Computes (fourierMatrix 76) ∧ C.size = 1295 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 76 1295
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_78 : ∃ C : Circuit 78, C.Computes (fourierMatrix 78) ∧ C.size = 1144 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.ct .two .two))))) 78 1144
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_79 : ∃ C : Circuit 79, C.Computes (fourierMatrix 79) ∧ C.size = 2445 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 79 2445
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_82 : ∃ C : Circuit 82, C.Computes (fourierMatrix 82) ∧ C.size = 1592 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))) 82 1592
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_83 : ∃ C : Circuit 83, C.Computes (fourierMatrix 83) ∧ C.size = 3349 :=
  XPlan.certify (.rader (.pfa .two (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two)))))) 83 3349
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_85 : ∃ C : Circuit 85, C.Computes (fourierMatrix 85) ∧ C.size = 1383 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.ct .two (.ct .two (.ct .two .two))))) 85 1383
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_86 : ∃ C : Circuit 86, C.Computes (fourierMatrix 86) ∧ C.size = 2024 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 1) (.pair 3))))) 86 2024
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_87 : ∃ C : Circuit 87, C.Computes (fourierMatrix 87) ∧ C.size = 1933 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.ct .two .two) (.pair 3)))) 87 1933
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_89 : ∃ C : Circuit 89, C.Computes (fourierMatrix 89) ∧ C.size = 2735 :=
  XPlan.certify (.rader (.pfa (.ct .two (.ct .two .two)) (.pair 5))) 89 2735
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_91 : ∃ C : Circuit 91, C.Computes (fourierMatrix 91) ∧ C.size = 1625 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa (.pair 1) (.ct .two .two)))) 91 1625
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_93 : ∃ C : Circuit 93, C.Computes (fourierMatrix 93) ∧ C.size = 1955 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))) 93 1955
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_94 : ∃ C : Circuit 94, C.Computes (fourierMatrix 94) ∧ C.size = 4002 :=
  XPlan.certify (.pfa .two (.bluestein 47 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 94 4002
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_95 : ∃ C : Circuit 95, C.Computes (fourierMatrix 95) ∧ C.size = 1861 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 95 1861
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_97 : ∃ C : Circuit 97, C.Computes (fourierMatrix 97) ∧ C.size = 1959 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two)))))) 97 1959
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_101 : ∃ C : Circuit 101, C.Computes (fourierMatrix 101) ∧ C.size = 2683 :=
  XPlan.certify (.rader (.ct (.pfa .two (.pair 2)) (.pfa .two (.pair 2)))) 101 2683
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_102 : ∃ C : Circuit 102, C.Computes (fourierMatrix 102) ∧ C.size = 1544 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 102 1544
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_103 : ∃ C : Circuit 103, C.Computes (fourierMatrix 103) ∧ C.size = 3293 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.rader (.ct .two (.ct .two (.ct .two .two))))))) 103 3293
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_104 : ∃ C : Circuit 104, C.Computes (fourierMatrix 104) ∧ C.size = 1521 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa (.pair 1) (.ct .two .two)))) 104 1521
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_106 : ∃ C : Circuit 106, C.Computes (fourierMatrix 106) ∧ C.size = 3072 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 106 3072
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_107 : ∃ C : Circuit 107, C.Computes (fourierMatrix 107) ∧ C.size = 5830 :=
  XPlan.certify (.bluestein 107 (.ct (.pfa .two (.pair 1)) (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))) 107 5830
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_109 : ∃ C : Circuit 109, C.Computes (fourierMatrix 109) ∧ C.size = 2643 :=
  XPlan.certify (.rader (.ct (.pfa .two (.pair 1)) (.pfa .two (.ct (.pair 1) (.pair 1))))) 109 2643
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_111 : ∃ C : Circuit 111, C.Computes (fourierMatrix 111) ∧ C.size = 2249 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))) 111 2249
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_113 : ∃ C : Circuit 113, C.Computes (fourierMatrix 113) ∧ C.size = 2895 :=
  XPlan.certify (.rader (.pfa (.pair 3) (.ct .two (.ct .two (.ct .two .two))))) 113 2895
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_114 : ∃ C : Circuit 114, C.Computes (fourierMatrix 114) ∧ C.size = 2104 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 114 2104
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_116 : ∃ C : Circuit 116, C.Computes (fourierMatrix 116) ∧ C.size = 2529 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa (.ct .two .two) (.pair 3)))) 116 2529
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_117 : ∃ C : Circuit 117, C.Computes (fourierMatrix 117) ∧ C.size = 1963 :=
  XPlan.certify (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa (.pair 1) (.ct .two .two)))) 117 1963
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_118 : ∃ C : Circuit 118, C.Computes (fourierMatrix 118) ∧ C.size = 5120 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.rader (.pfa (.ct .two .two) (.pair 3)))))) 118 5120
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_119 : ∃ C : Circuit 119, C.Computes (fourierMatrix 119) ∧ C.size = 2181 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.ct .two (.ct .two (.ct .two .two))))) 119 2181
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_122 : ∃ C : Circuit 122, C.Computes (fourierMatrix 122) ∧ C.size = 2696 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pair 2))))) 122 2696
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_123 : ∃ C : Circuit 123, C.Computes (fourierMatrix 123) ∧ C.size = 2593 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))) 123 2593
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_124 : ∃ C : Circuit 124, C.Computes (fourierMatrix 124) ∧ C.size = 2555 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))) 124 2555
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_127 : ∃ C : Circuit 127, C.Computes (fourierMatrix 127) ∧ C.size = 3689 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 3) (.ct (.pair 1) (.pair 1))))) 127 3689
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_129 : ∃ C : Circuit 129, C.Computes (fourierMatrix 129) ∧ C.size = 3251 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3))))) 129 3251
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_130 : ∃ C : Circuit 130, C.Computes (fourierMatrix 130) ∧ C.size = 2184 :=
  XPlan.certify (.pfa .two (.pfa (.pair 2) (.rader (.pfa (.pair 1) (.ct .two .two))))) 130 2184
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_131 : ∃ C : Circuit 131, C.Computes (fourierMatrix 131) ∧ C.size = 4629 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 2) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 131 4629
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_133 : ∃ C : Circuit 133, C.Computes (fourierMatrix 133) ∧ C.size = 2879 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 133 2879
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_134 : ∃ C : Circuit 134, C.Computes (fourierMatrix 134) ∧ C.size = 4248 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 1) (.pair 5))))) 134 4248
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_136 : ∃ C : Circuit 136, C.Computes (fourierMatrix 136) ∧ C.size = 2053 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.ct .two (.ct .two (.ct .two .two))))) 136 2053
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_137 : ∃ C : Circuit 137, C.Computes (fourierMatrix 137) ∧ C.size = 4379 :=
  XPlan.certify (.rader (.pfa (.ct .two (.ct .two .two)) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 137 4379
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_139 : ∃ C : Circuit 139, C.Computes (fourierMatrix 139) ∧ C.size = 7526 :=
  XPlan.certify (.bluestein 139 (.ct (.pfa (.pair 1) (.ct .two .two)) (.pfa (.pair 1) (.ct .two (.ct .two .two))))) 139 7526
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_141 : ∃ C : Circuit 141, C.Computes (fourierMatrix 141) ∧ C.size = 6238 :=
  XPlan.certify (.pfa (.pair 1) (.bluestein 47 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 141 6238
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_142 : ∃ C : Circuit 142, C.Computes (fourierMatrix 142) ∧ C.size = 3968 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 2) (.pair 3))))) 142 3968
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_143 : ∃ C : Circuit 143, C.Computes (fourierMatrix 143) ∧ C.size = 3133 :=
  XPlan.certify (.pfa (.pair 5) (.rader (.pfa (.pair 1) (.ct .two .two)))) 143 3133
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_145 : ∃ C : Circuit 145, C.Computes (fourierMatrix 145) ∧ C.size = 3531 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa (.ct .two .two) (.pair 3)))) 145 3531
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_146 : ∃ C : Circuit 146, C.Computes (fourierMatrix 146) ∧ C.size = 3128 :=
  XPlan.certify (.pfa .two (.rader (.ct (.pfa .two (.pair 1)) (.pfa (.pair 1) (.ct .two .two))))) 146 3128
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_148 : ∃ C : Circuit 148, C.Computes (fourierMatrix 148) ∧ C.size = 2937 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))) 148 2937
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_149 : ∃ C : Circuit 149, C.Computes (fourierMatrix 149) ∧ C.size = 6171 :=
  XPlan.certify (.rader (.pfa (.ct .two .two) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1)))))) 149 6171
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_151 : ∃ C : Circuit 151, C.Computes (fourierMatrix 151) ∧ C.size = 4473 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.ct (.pair 2) (.pair 2))))) 151 4473
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_152 : ∃ C : Circuit 152, C.Computes (fourierMatrix 152) ∧ C.size = 2799 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 152 2799
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_153 : ∃ C : Circuit 153, C.Computes (fourierMatrix 153) ∧ C.size = 2639 :=
  XPlan.certify (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.ct .two (.ct .two (.ct .two .two))))) 153 2639
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_155 : ∃ C : Circuit 155, C.Computes (fourierMatrix 155) ∧ C.size = 3589 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))) 155 3589
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_156 : ∃ C : Circuit 156, C.Computes (fourierMatrix 156) ∧ C.size = 2483 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two))))) 156 2483
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_157 : ∃ C : Circuit 157, C.Computes (fourierMatrix 157) ∧ C.size = 5279 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 157 5279
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_158 : ∃ C : Circuit 158, C.Computes (fourierMatrix 158) ∧ C.size = 5048 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.ct .two .two))))))) 158 5048
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_159 : ∃ C : Circuit 159, C.Computes (fourierMatrix 159) ∧ C.size = 4873 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 159 4873
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_163 : ∃ C : Circuit 163, C.Computes (fourierMatrix 163) ∧ C.size = 4649 :=
  XPlan.certify (.rader (.pfa .two (.ct (.pair 1) (.ct (.pair 1) (.ct (.pair 1) (.pair 1)))))) 163 4649
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_164 : ∃ C : Circuit 164, C.Computes (fourierMatrix 164) ∧ C.size = 3389 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))) 164 3389
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_166 : ∃ C : Circuit 166, C.Computes (fourierMatrix 166) ∧ C.size = 6864 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))))) 166 6864
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_167 : ∃ C : Circuit 167, C.Computes (fourierMatrix 167) ∧ C.size = 10066 :=
  XPlan.certify (.bluestein 167 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))) 167 10066
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_169 : ∃ C : Circuit 169, C.Computes (fourierMatrix 169) ∧ C.size = 3862 :=
  XPlan.certify (.ct (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.pfa (.pair 1) (.ct .two .two)))) 169 3862
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_170 : ∃ C : Circuit 170, C.Computes (fourierMatrix 170) ∧ C.size = 2936 :=
  XPlan.certify (.pfa .two (.pfa (.pair 2) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 170 2936
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_171 : ∃ C : Circuit 171, C.Computes (fourierMatrix 171) ∧ C.size = 3517 :=
  XPlan.certify (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 171 3517
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_172 : ∃ C : Circuit 172, C.Computes (fourierMatrix 172) ∧ C.size = 4263 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3))))) 172 4263
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_173 : ∃ C : Circuit 173, C.Computes (fourierMatrix 173) ∧ C.size = 8871 :=
  XPlan.certify (.rader (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3)))))) 173 8871
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_174 : ∃ C : Circuit 174, C.Computes (fourierMatrix 174) ∧ C.size = 4040 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.ct .two .two) (.pair 3))))) 174 4040
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_177 : ∃ C : Circuit 177, C.Computes (fourierMatrix 177) ∧ C.size = 7975 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.rader (.pfa (.ct .two .two) (.pair 3)))))) 177 7975
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_178 : ∃ C : Circuit 178, C.Computes (fourierMatrix 178) ∧ C.size = 5648 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.ct .two (.ct .two .two)) (.pair 5)))) 178 5648
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_179 : ∃ C : Circuit 179, C.Computes (fourierMatrix 179) ∧ C.size = 10090 :=
  XPlan.certify (.bluestein 179 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))) 179 10090
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_181 : ∃ C : Circuit 181, C.Computes (fourierMatrix 181) ∧ C.size = 4979 :=
  XPlan.certify (.rader (.pfa (.ct .two .two) (.pfa (.pair 2) (.ct (.pair 1) (.pair 1))))) 181 4979
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_182 : ∃ C : Circuit 182, C.Computes (fourierMatrix 182) ∧ C.size = 3432 :=
  XPlan.certify (.pfa .two (.pfa (.pair 3) (.rader (.pfa (.pair 1) (.ct .two .two))))) 182 3432
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_183 : ∃ C : Circuit 183, C.Computes (fourierMatrix 183) ∧ C.size = 4349 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pair 2))))) 183 4349
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_185 : ∃ C : Circuit 185, C.Computes (fourierMatrix 185) ∧ C.size = 4143 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))) 185 4143
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_186 : ∃ C : Circuit 186, C.Computes (fourierMatrix 186) ∧ C.size = 4096 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2)))))) 186 4096
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_187 : ∃ C : Circuit 187, C.Computes (fourierMatrix 187) ∧ C.size = 4185 :=
  XPlan.certify (.pfa (.pair 5) (.rader (.ct .two (.ct .two (.ct .two .two))))) 187 4185
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_188 : ∃ C : Circuit 188, C.Computes (fourierMatrix 188) ∧ C.size = 8239 :=
  XPlan.certify (.pfa (.ct .two .two) (.bluestein 47 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 188 8239
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_190 : ∃ C : Circuit 190, C.Computes (fourierMatrix 190) ∧ C.size = 3912 :=
  XPlan.certify (.pfa .two (.pfa (.pair 2) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 190 3912
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_191 : ∃ C : Circuit 191, C.Computes (fourierMatrix 191) ∧ C.size = 8205 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 2) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))))) 191 8205
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_193 : ∃ C : Circuit 193, C.Computes (fourierMatrix 193) ∧ C.size = 4487 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 193 4487
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_194 : ∃ C : Circuit 194, C.Computes (fourierMatrix 194) ∧ C.size = 4112 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 194 4112
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_195 : ∃ C : Circuit 195, C.Computes (fourierMatrix 195) ∧ C.size = 3601 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.pair 2) (.rader (.pfa (.pair 1) (.ct .two .two))))) 195 3601
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_197 : ∃ C : Circuit 197, C.Computes (fourierMatrix 197) ∧ C.size = 6891 :=
  XPlan.certify (.rader (.ct (.pfa .two (.pair 3)) (.pfa .two (.pair 3)))) 197 6891
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_199 : ∃ C : Circuit 199, C.Computes (fourierMatrix 199) ∧ C.size = 7401 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.ct (.pair 1) (.pair 1)) (.pair 5)))) 199 7401
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_201 : ∃ C : Circuit 201, C.Computes (fourierMatrix 201) ∧ C.size = 6707 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 1) (.pair 5))))) 201 6707
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_202 : ∃ C : Circuit 202, C.Computes (fourierMatrix 202) ∧ C.size = 5568 :=
  XPlan.certify (.pfa .two (.rader (.ct (.pfa .two (.pair 2)) (.pfa .two (.pair 2))))) 202 5568
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_203 : ∃ C : Circuit 203, C.Computes (fourierMatrix 203) ∧ C.size = 5361 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa (.ct .two .two) (.pair 3)))) 203 5361
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_204 : ∃ C : Circuit 204, C.Computes (fourierMatrix 204) ∧ C.size = 3343 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 204 3343
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_205 : ∃ C : Circuit 205, C.Computes (fourierMatrix 205) ∧ C.size = 4759 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))) 205 4759
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_206 : ∃ C : Circuit 206, C.Computes (fourierMatrix 206) ∧ C.size = 6792 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 1) (.rader (.ct .two (.ct .two (.ct .two .two)))))))) 206 6792
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_208 : ∃ C : Circuit 208, C.Computes (fourierMatrix 208) ∧ C.size = 3341 :=
  XPlan.certify (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.ct .two (.ct .two (.ct .two .two)))) 208 3341
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_209 : ∃ C : Circuit 209, C.Computes (fourierMatrix 209) ∧ C.size = 5371 :=
  XPlan.certify (.pfa (.pair 5) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 209 5371
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_211 : ∃ C : Circuit 211, C.Computes (fourierMatrix 211) ∧ C.size = 6857 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.pfa (.pair 2) (.pair 3))))) 211 6857
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_212 : ∃ C : Circuit 212, C.Computes (fourierMatrix 212) ∧ C.size = 6409 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 212 6409
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_213 : ∃ C : Circuit 213, C.Computes (fourierMatrix 213) ∧ C.size = 6307 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 2) (.pair 3))))) 213 6307
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_214 : ∃ C : Circuit 214, C.Computes (fourierMatrix 214) ∧ C.size = 11874 :=
  XPlan.certify (.pfa .two (.bluestein 107 (.ct (.pfa .two (.pair 1)) (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1)))))) 214 11874
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_215 : ∃ C : Circuit 215, C.Computes (fourierMatrix 215) ∧ C.size = 5877 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3))))) 215 5877
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_217 : ∃ C : Circuit 217, C.Computes (fourierMatrix 217) ∧ C.size = 5471 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))) 217 5471
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_218 : ∃ C : Circuit 218, C.Computes (fourierMatrix 218) ∧ C.size = 5504 :=
  XPlan.certify (.pfa .two (.rader (.ct (.pfa .two (.pair 1)) (.pfa .two (.ct (.pair 1) (.pair 1)))))) 218 5504
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_219 : ∃ C : Circuit 219, C.Computes (fourierMatrix 219) ∧ C.size = 5057 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.ct (.pfa .two (.pair 1)) (.pfa (.pair 1) (.ct .two .two))))) 219 5057
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_221 : ∃ C : Circuit 221, C.Computes (fourierMatrix 221) ∧ C.size = 4966 :=
  XPlan.certify (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.ct .two (.ct .two (.ct .two .two))))) 221 4966
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_222 : ∃ C : Circuit 222, C.Computes (fourierMatrix 222) ∧ C.size = 4720 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1)))))) 222 4720
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_223 : ∃ C : Circuit 223, C.Computes (fourierMatrix 223) ∧ C.size = 9885 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))))) 223 9885
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_226 : ∃ C : Circuit 226, C.Computes (fourierMatrix 226) ∧ C.size = 6016 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.pair 3) (.ct .two (.ct .two (.ct .two .two)))))) 226 6016
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_227 : ∃ C : Circuit 227, C.Computes (fourierMatrix 227) ∧ C.size = 12485 :=
  XPlan.certify (.rader (.pfa .two (.rader (.pfa (.pair 3) (.ct .two (.ct .two (.ct .two .two))))))) 227 12485
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_228 : ∃ C : Circuit 228, C.Computes (fourierMatrix 228) ∧ C.size = 4493 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 228 4493
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_229 : ∃ C : Circuit 229, C.Computes (fourierMatrix 229) ∧ C.size = 9443 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))))) 229 9443
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_232 : ∃ C : Circuit 232, C.Computes (fourierMatrix 232) ∧ C.size = 5377 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa (.ct .two .two) (.pair 3)))) 232 5377
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_233 : ∃ C : Circuit 233, C.Computes (fourierMatrix 233) ∧ C.size = 11219 :=
  XPlan.certify (.rader (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa (.ct .two .two) (.pair 3))))) 233 11219
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_234 : ∃ C : Circuit 234, C.Computes (fourierMatrix 234) ∧ C.size = 4160 :=
  XPlan.certify (.pfa .two (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa (.pair 1) (.ct .two .two))))) 234 4160
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_235 : ∃ C : Circuit 235, C.Computes (fourierMatrix 235) ∧ C.size = 10898 :=
  XPlan.certify (.pfa (.pair 2) (.bluestein 47 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 235 10898
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_236 : ∃ C : Circuit 236, C.Computes (fourierMatrix 236) ∧ C.size = 10535 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa .two (.rader (.pfa (.ct .two .two) (.pair 3)))))) 236 10535
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_237 : ∃ C : Circuit 237, C.Computes (fourierMatrix 237) ∧ C.size = 7967 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.ct .two .two))))))) 237 7967
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_238 : ∃ C : Circuit 238, C.Computes (fourierMatrix 238) ∧ C.size = 4600 :=
  XPlan.certify (.pfa .two (.pfa (.pair 3) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 238 4600
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_239 : ∃ C : Circuit 239, C.Computes (fourierMatrix 239) ∧ C.size = 9677 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 3) (.rader (.ct .two (.ct .two (.ct .two .two))))))) 239 9677
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_241 : ∃ C : Circuit 241, C.Computes (fourierMatrix 241) ∧ C.size = 6495 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.pair 2) (.ct .two (.ct .two (.ct .two .two)))))) 241 6495
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_244 : ∃ C : Circuit 244, C.Computes (fourierMatrix 244) ∧ C.size = 5697 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pair 2))))) 244 5697
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_246 : ∃ C : Circuit 246, C.Computes (fourierMatrix 246) ∧ C.size = 5432 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two)))))) 246 5432
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_247 : ∃ C : Circuit 247, C.Computes (fourierMatrix 247) ∧ C.size = 6370 :=
  XPlan.certify (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 247 6370
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_248 : ∃ C : Circuit 248, C.Computes (fourierMatrix 248) ∧ C.size = 5451 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))) 248 5451
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_249 : ∃ C : Circuit 249, C.Computes (fourierMatrix 249) ∧ C.size = 10711 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))))) 249 10711
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_251 : ∃ C : Circuit 251, C.Computes (fourierMatrix 251) ∧ C.size = 8905 :=
  XPlan.certify (.rader (.pfa .two (.ct (.pair 2) (.ct (.pair 2) (.pair 2))))) 251 8905
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_254 : ∃ C : Circuit 254, C.Computes (fourierMatrix 254) ∧ C.size = 7632 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 3) (.ct (.pair 1) (.pair 1)))))) 254 7632
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_255 : ∃ C : Circuit 255, C.Computes (fourierMatrix 255) ∧ C.size = 4829 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.pair 2) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 255 4829
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_257 : ∃ C : Circuit 257, C.Computes (fourierMatrix 257) ∧ C.size = 6147 :=
  XPlan.certify (.rader (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))) 257 6147
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_258 : ∃ C : Circuit 258, C.Computes (fourierMatrix 258) ∧ C.size = 6760 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3)))))) 258 6760
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_259 : ∃ C : Circuit 259, C.Computes (fourierMatrix 259) ∧ C.size = 6333 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))) 259 6333
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_260 : ∃ C : Circuit 260, C.Computes (fourierMatrix 260) ∧ C.size = 4693 :=
  XPlan.certify (.pfa (.ct .two .two) (.pfa (.pair 2) (.rader (.pfa (.pair 1) (.ct .two .two))))) 260 4693
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_261 : ∃ C : Circuit 261, C.Computes (fourierMatrix 261) ∧ C.size = 6611 :=
  XPlan.certify (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa (.ct .two .two) (.pair 3)))) 261 6611
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_262 : ∃ C : Circuit 262, C.Computes (fourierMatrix 262) ∧ C.size = 9520 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 2) (.rader (.pfa (.pair 1) (.ct .two .two))))))) 262 9520
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_263 : ∃ C : Circuit 263, C.Computes (fourierMatrix 263) ∧ C.size = 16654 :=
  XPlan.certify (.bluestein 263 (.ct (.pfa (.pair 1) (.ct .two (.ct .two .two))) (.pfa (.pair 1) (.ct .two (.ct .two .two))))) 263 16654
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_265 : ∃ C : Circuit 265, C.Computes (fourierMatrix 265) ∧ C.size = 8687 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 265 8687
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_266 : ∃ C : Circuit 266, C.Computes (fourierMatrix 266) ∧ C.size = 6024 :=
  XPlan.certify (.pfa .two (.pfa (.pair 3) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 266 6024
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_267 : ∃ C : Circuit 267, C.Computes (fourierMatrix 267) ∧ C.size = 8917 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.ct .two (.ct .two .two)) (.pair 5)))) 267 8917
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_268 : ∃ C : Circuit 268, C.Computes (fourierMatrix 268) ∧ C.size = 8831 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 1) (.pair 5))))) 268 8831
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_269 : ∃ C : Circuit 269, C.Computes (fourierMatrix 269) ∧ C.size = 16666 :=
  XPlan.certify (.bluestein 269 (.ct (.pfa (.pair 1) (.ct .two (.ct .two .two))) (.pfa (.pair 1) (.ct .two (.ct .two .two))))) 269 16666
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_271 : ∃ C : Circuit 271, C.Computes (fourierMatrix 271) ∧ C.size = 8553 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 2) (.ct (.pair 1) (.ct (.pair 1) (.pair 1)))))) 271 8553
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_272 : ∃ C : Circuit 272, C.Computes (fourierMatrix 272) ∧ C.size = 4497 :=
  XPlan.certify (.pfa (.ct .two (.ct .two (.ct .two .two))) (.rader (.ct .two (.ct .two (.ct .two .two))))) 272 4497
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_273 : ∃ C : Circuit 273, C.Computes (fourierMatrix 273) ∧ C.size = 5603 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.pair 3) (.rader (.pfa (.pair 1) (.ct .two .two))))) 273 5603
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_274 : ∃ C : Circuit 274, C.Computes (fourierMatrix 274) ∧ C.size = 9032 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.ct .two (.ct .two .two)) (.rader (.ct .two (.ct .two (.ct .two .two))))))) 274 9032
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_277 : ∃ C : Circuit 277, C.Computes (fourierMatrix 277) ∧ C.size = 15939 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pair 11)))) 277 15939
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_278 : ∃ C : Circuit 278, C.Computes (fourierMatrix 278) ∧ C.size = 15330 :=
  XPlan.certify (.pfa .two (.bluestein 139 (.ct (.pfa (.pair 1) (.ct .two .two)) (.pfa (.pair 1) (.ct .two (.ct .two .two)))))) 278 15330
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_279 : ∃ C : Circuit 279, C.Computes (fourierMatrix 279) ∧ C.size = 6733 :=
  XPlan.certify (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))) 279 6733
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_281 : ∃ C : Circuit 281, C.Computes (fourierMatrix 281) ∧ C.size = 9119 :=
  XPlan.certify (.rader (.pfa (.pair 2) (.pfa (.pair 3) (.ct .two (.ct .two .two))))) 281 9119
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_282 : ∃ C : Circuit 282, C.Computes (fourierMatrix 282) ∧ C.size = 12758 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.bluestein 47 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))) 282 12758
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_283 : ∃ C : Circuit 283, C.Computes (fourierMatrix 283) ∧ C.size = 16694 :=
  XPlan.certify (.bluestein 283 (.ct (.pfa (.pair 1) (.ct .two (.ct .two .two))) (.pfa (.pair 1) (.ct .two (.ct .two .two))))) 283 16694
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_284 : ∃ C : Circuit 284, C.Computes (fourierMatrix 284) ∧ C.size = 8291 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 2) (.pair 3))))) 284 8291
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_285 : ∃ C : Circuit 285, C.Computes (fourierMatrix 285) ∧ C.size = 6343 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.pair 2) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 285 6343
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_286 : ∃ C : Circuit 286, C.Computes (fourierMatrix 286) ∧ C.size = 6552 :=
  XPlan.certify (.pfa .two (.pfa (.pair 5) (.rader (.pfa (.pair 1) (.ct .two .two))))) 286 6552
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_287 : ∃ C : Circuit 287, C.Computes (fourierMatrix 287) ∧ C.size = 7253 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))) 287 7253
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_289 : ∃ C : Circuit 289, C.Computes (fourierMatrix 289) ∧ C.size = 6886 :=
  XPlan.certify (.ct (.rader (.ct .two (.ct .two (.ct .two .two)))) (.rader (.ct .two (.ct .two (.ct .two .two))))) 289 6886
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_290 : ∃ C : Circuit 290, C.Computes (fourierMatrix 290) ∧ C.size = 7352 :=
  XPlan.certify (.pfa .two (.pfa (.pair 2) (.rader (.pfa (.ct .two .two) (.pair 3))))) 290 7352
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_291 : ∃ C : Circuit 291, C.Computes (fourierMatrix 291) ∧ C.size = 6653 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 291 6653
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_292 : ∃ C : Circuit 292, C.Computes (fourierMatrix 292) ∧ C.size = 6621 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.ct (.pfa .two (.pair 1)) (.pfa (.pair 1) (.ct .two .two))))) 292 6621
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_293 : ∃ C : Circuit 293, C.Computes (fourierMatrix 293) ∧ C.size = 13827 :=
  XPlan.certify (.rader (.pfa (.ct .two .two) (.rader (.ct (.pfa .two (.pair 1)) (.pfa (.pair 1) (.ct .two .two)))))) 293 13827
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_295 : ∃ C : Circuit 295, C.Computes (fourierMatrix 295) ∧ C.size = 13921 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa .two (.rader (.pfa (.ct .two .two) (.pair 3)))))) 295 13921
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_296 : ∃ C : Circuit 296, C.Computes (fourierMatrix 296) ∧ C.size = 6281 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))) 296 6281
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_298 : ∃ C : Circuit 298, C.Computes (fourierMatrix 298) ∧ C.size = 12640 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.ct .two .two) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))))) 298 12640
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_299 : ∃ C : Circuit 299, C.Computes (fourierMatrix 299) ∧ C.size = 10153 :=
  XPlan.certify (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.pair 11)) 299 10153
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_301 : ∃ C : Circuit 301, C.Computes (fourierMatrix 301) ∧ C.size = 8847 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3))))) 301 8847
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_302 : ∃ C : Circuit 302, C.Computes (fourierMatrix 302) ∧ C.size = 9248 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 1) (.ct (.pair 2) (.pair 2)))))) 302 9248
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_303 : ∃ C : Circuit 303, C.Computes (fourierMatrix 303) ∧ C.size = 8857 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.ct (.pfa .two (.pair 2)) (.pfa .two (.pair 2))))) 303 8857
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_304 : ∃ C : Circuit 304, C.Computes (fourierMatrix 304) ∧ C.size = 6035 :=
  XPlan.certify (.pfa (.ct .two (.ct .two (.ct .two .two))) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 304 6035
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_305 : ∃ C : Circuit 305, C.Computes (fourierMatrix 305) ∧ C.size = 7899 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pair 2))))) 305 7899
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_306 : ∃ C : Circuit 306, C.Computes (fourierMatrix 306) ∧ C.size = 5584 :=
  XPlan.certify (.pfa .two (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 306 5584
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_307 : ∃ C : Circuit 307, C.Computes (fourierMatrix 307) ∧ C.size = 11781 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.ct .two (.ct .two (.ct .two .two))))))) 307 11781
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_309 : ∃ C : Circuit 309, C.Computes (fourierMatrix 309) ∧ C.size = 10703 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 1) (.rader (.ct .two (.ct .two (.ct .two .two)))))))) 309 10703
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_310 : ∃ C : Circuit 310, C.Computes (fourierMatrix 310) ∧ C.size = 7488 :=
  XPlan.certify (.pfa .two (.pfa (.pair 2) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2)))))) 310 7488
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_311 : ∃ C : Circuit 311, C.Computes (fourierMatrix 311) ∧ C.size = 15597 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 2) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))))) 311 15597
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_312 : ∃ C : Circuit 312, C.Computes (fourierMatrix 312) ∧ C.size = 5395 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa (.pair 1) (.ct .two .two))))) 312 5395
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_313 : ∃ C : Circuit 313, C.Computes (fourierMatrix 313) ∧ C.size = 11415 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 313 11415
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_314 : ∃ C : Circuit 314, C.Computes (fourierMatrix 314) ∧ C.size = 10872 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two))))))) 314 10872
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_316 : ∃ C : Circuit 316, C.Computes (fourierMatrix 316) ∧ C.size = 10491 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.ct .two .two))))))) 316 10491
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_317 : ∃ C : Circuit 317, C.Computes (fourierMatrix 317) ∧ C.size = 19586 :=
  XPlan.certify (.bluestein 317 (.pfa (.pair 2) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))) 317 19586
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_318 : ∃ C : Circuit 318, C.Computes (fourierMatrix 318) ∧ C.size = 10064 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two))))))) 318 10064
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_319 : ∃ C : Circuit 319, C.Computes (fourierMatrix 319) ∧ C.size = 9717 :=
  XPlan.certify (.pfa (.pair 5) (.rader (.pfa (.ct .two .two) (.pair 3)))) 319 9717
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_321 : ∃ C : Circuit 321, C.Computes (fourierMatrix 321) ∧ C.size = 18346 :=
  XPlan.certify (.pfa (.pair 1) (.bluestein 107 (.ct (.pfa .two (.pair 1)) (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1)))))) 321 18346
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_323 : ∃ C : Circuit 323, C.Computes (fourierMatrix 323) ∧ C.size = 8482 :=
  XPlan.certify (.pfa (.rader (.ct .two (.ct .two (.ct .two .two)))) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 323 8482
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_325 : ∃ C : Circuit 325, C.Computes (fourierMatrix 325) ∧ C.size = 6903 :=
  XPlan.certify (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.ct (.pair 2) (.pair 2))) 325 6903
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_326 : ∃ C : Circuit 326, C.Computes (fourierMatrix 326) ∧ C.size = 9624 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.ct (.pair 1) (.ct (.pair 1) (.ct (.pair 1) (.pair 1))))))) 326 9624
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_327 : ∃ C : Circuit 327, C.Computes (fourierMatrix 327) ∧ C.size = 8801 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.ct (.pfa .two (.pair 1)) (.pfa .two (.ct (.pair 1) (.pair 1)))))) 327 8801
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_328 : ∃ C : Circuit 328, C.Computes (fourierMatrix 328) ∧ C.size = 7229 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))) 328 7229
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_329 : ∃ C : Circuit 329, C.Computes (fourierMatrix 329) ∧ C.size = 15934 :=
  XPlan.certify (.pfa (.pair 3) (.bluestein 47 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 329 15934
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_331 : ∃ C : Circuit 331, C.Computes (fourierMatrix 331) ∧ C.size = 13449 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.pfa (.pair 2) (.pair 5))))) 331 13449
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_332 : ∃ C : Circuit 332, C.Computes (fourierMatrix 332) ∧ C.size = 14143 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa .two (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))))) 332 14143
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_333 : ∃ C : Circuit 333, C.Computes (fourierMatrix 333) ∧ C.size = 7783 :=
  XPlan.certify (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))) 333 7783
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_334 : ∃ C : Circuit 334, C.Computes (fourierMatrix 334) ∧ C.size = 20466 :=
  XPlan.certify (.pfa .two (.bluestein 167 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two))))))))) 334 20466
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_335 : ∃ C : Circuit 335, C.Computes (fourierMatrix 335) ∧ C.size = 11893 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa .two (.pfa (.pair 1) (.pair 5))))) 335 11893
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_337 : ∃ C : Circuit 337, C.Computes (fourierMatrix 337) ∧ C.size = 10475 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.pair 3) (.ct .two (.ct .two (.ct .two .two)))))) 337 10475
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_338 : ∃ C : Circuit 338, C.Computes (fourierMatrix 338) ∧ C.size = 8062 :=
  XPlan.certify (.pfa .two (.ct (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.pfa (.pair 1) (.ct .two .two))))) 338 8062
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_339 : ∃ C : Circuit 339, C.Computes (fourierMatrix 339) ∧ C.size = 9589 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.pair 3) (.ct .two (.ct .two (.ct .two .two)))))) 339 9589
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_340 : ∃ C : Circuit 340, C.Computes (fourierMatrix 340) ∧ C.size = 6297 :=
  XPlan.certify (.pfa (.ct .two .two) (.pfa (.pair 2) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 340 6297
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_341 : ∃ C : Circuit 341, C.Computes (fourierMatrix 341) ∧ C.size = 9979 :=
  XPlan.certify (.pfa (.pair 5) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))) 341 9979
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_342 : ∃ C : Circuit 342, C.Computes (fourierMatrix 342) ∧ C.size = 7376 :=
  XPlan.certify (.pfa .two (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 342 7376
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_344 : ∃ C : Circuit 344, C.Computes (fourierMatrix 344) ∧ C.size = 8999 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3))))) 344 8999
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_346 : ∃ C : Circuit 346, C.Computes (fourierMatrix 346) ∧ C.size = 18088 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3))))))) 346 18088
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_347 : ∃ C : Circuit 347, C.Computes (fourierMatrix 347) ∧ C.size = 22458 :=
  XPlan.certify (.bluestein 347 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two))))))))) 347 22458
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_348 : ∃ C : Circuit 348, C.Computes (fourierMatrix 348) ∧ C.size = 8515 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa (.ct .two .two) (.pair 3))))) 348 8515
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_349 : ∃ C : Circuit 349, C.Computes (fourierMatrix 349) ∧ C.size = 17727 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa (.ct .two .two) (.pair 3)))))) 349 17727
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_351 : ∃ C : Circuit 351, C.Computes (fourierMatrix 351) ∧ C.size = 7033 :=
  XPlan.certify (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.ct (.pair 1) (.ct (.pair 1) (.pair 1)))) 351 7033
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_353 : ∃ C : Circuit 353, C.Computes (fourierMatrix 353) ∧ C.size = 12983 :=
  XPlan.certify (.rader (.pfa (.pair 5) (.ct .two (.ct .two (.ct .two (.ct .two .two)))))) 353 12983
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_354 : ∃ C : Circuit 354, C.Computes (fourierMatrix 354) ∧ C.size = 16304 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa .two (.rader (.pfa (.ct .two .two) (.pair 3))))))) 354 16304
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_355 : ∃ C : Circuit 355, C.Computes (fourierMatrix 355) ∧ C.size = 11269 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa .two (.pfa (.pair 2) (.pair 3))))) 355 11269
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_356 : ∃ C : Circuit 356, C.Computes (fourierMatrix 356) ∧ C.size = 11741 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa (.ct .two (.ct .two .two)) (.pair 5)))) 356 11741
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_357 : ∃ C : Circuit 357, C.Computes (fourierMatrix 357) ∧ C.size = 7495 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.pair 3) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 357 7495
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_358 : ∃ C : Circuit 358, C.Computes (fourierMatrix 358) ∧ C.size = 20538 :=
  XPlan.certify (.pfa .two (.bluestein 179 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two))))))))) 358 20538
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_359 : ∃ C : Circuit 359, C.Computes (fourierMatrix 359) ∧ C.size = 22482 :=
  XPlan.certify (.bluestein 359 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two))))))))) 359 22482
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_361 : ∃ C : Circuit 361, C.Computes (fourierMatrix 361) ∧ C.size = 11002 :=
  XPlan.certify (.ct (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))) 361 11002
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_362 : ∃ C : Circuit 362, C.Computes (fourierMatrix 362) ∧ C.size = 10320 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.ct .two .two) (.pfa (.pair 2) (.ct (.pair 1) (.pair 1)))))) 362 10320
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_364 : ∃ C : Circuit 364, C.Computes (fourierMatrix 364) ∧ C.size = 7319 :=
  XPlan.certify (.pfa (.ct .two .two) (.pfa (.pair 3) (.rader (.pfa (.pair 1) (.ct .two .two))))) 364 7319
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_365 : ∃ C : Circuit 365, C.Computes (fourierMatrix 365) ∧ C.size = 9207 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.ct (.pfa .two (.pair 1)) (.pfa (.pair 1) (.ct .two .two))))) 365 9207
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_366 : ∃ C : Circuit 366, C.Computes (fourierMatrix 366) ∧ C.size = 9064 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pair 2)))))) 366 9064
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_367 : ∃ C : Circuit 367, C.Computes (fourierMatrix 367) ∧ C.size = 18861 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pair 2))))))) 367 18861
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_369 : ∃ C : Circuit 369, C.Computes (fourierMatrix 369) ∧ C.size = 8927 :=
  XPlan.certify (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))) 369 8927
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_370 : ∃ C : Circuit 370, C.Computes (fourierMatrix 370) ∧ C.size = 8656 :=
  XPlan.certify (.pfa .two (.pfa (.pair 2) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1)))))) 370 8656
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_371 : ∃ C : Circuit 371, C.Computes (fourierMatrix 371) ∧ C.size = 12925 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 371 12925
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_372 : ∃ C : Circuit 372, C.Computes (fourierMatrix 372) ∧ C.size = 8657 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2)))))) 372 8657
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_373 : ∃ C : Circuit 373, C.Computes (fourierMatrix 373) ∧ C.size = 18059 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))))) 373 18059
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_374 : ∃ C : Circuit 374, C.Computes (fourierMatrix 374) ∧ C.size = 8744 :=
  XPlan.certify (.pfa .two (.pfa (.pair 5) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 374 8744
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_376 : ∃ C : Circuit 376, C.Computes (fourierMatrix 376) ∧ C.size = 16995 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.bluestein 47 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 376 16995
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_377 : ∃ C : Circuit 377, C.Computes (fourierMatrix 377) ∧ C.size = 11518 :=
  XPlan.certify (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.pfa (.ct .two .two) (.pair 3)))) 377 11518
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_379 : ∃ C : Circuit 379, C.Computes (fourierMatrix 379) ∧ C.size = 13529 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 3) (.ct (.pair 1) (.ct (.pair 1) (.pair 1)))))) 379 13529
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_380 : ∃ C : Circuit 380, C.Computes (fourierMatrix 380) ∧ C.size = 8299 :=
  XPlan.certify (.pfa (.ct .two .two) (.pfa (.pair 2) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 380 8299
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_381 : ∃ C : Circuit 381, C.Computes (fourierMatrix 381) ∧ C.size = 12083 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 3) (.ct (.pair 1) (.pair 1)))))) 381 12083
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_382 : ∃ C : Circuit 382, C.Computes (fourierMatrix 382) ∧ C.size = 16792 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 2) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))))) 382 16792
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_383 : ∃ C : Circuit 383, C.Computes (fourierMatrix 383) ∧ C.size = 22530 :=
  XPlan.certify (.bluestein 383 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two))))))))) 383 22530
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_386 : ∃ C : Circuit 386, C.Computes (fourierMatrix 386) ∧ C.size = 9360 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))) 386 9360
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_387 : ∃ C : Circuit 387, C.Computes (fourierMatrix 387) ∧ C.size = 10957 :=
  XPlan.certify (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3))))) 387 10957
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_388 : ∃ C : Circuit 388, C.Computes (fourierMatrix 388) ∧ C.size = 8709 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 388 8709
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_389 : ∃ C : Circuit 389, C.Computes (fourierMatrix 389) ∧ C.size = 18195 :=
  XPlan.certify (.rader (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))) 389 18195
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_390 : ∃ C : Circuit 390, C.Computes (fourierMatrix 390) ∧ C.size = 7592 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.pfa (.pair 2) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 390 7592
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_391 : ∃ C : Circuit 391, C.Computes (fourierMatrix 391) ∧ C.size = 13461 :=
  XPlan.certify (.pfa (.rader (.ct .two (.ct .two (.ct .two .two)))) (.pair 11)) 391 13461
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_393 : ∃ C : Circuit 393, C.Computes (fourierMatrix 393) ∧ C.size = 14935 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 2) (.rader (.pfa (.pair 1) (.ct .two .two))))))) 393 14935
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_394 : ∃ C : Circuit 394, C.Computes (fourierMatrix 394) ∧ C.size = 14176 :=
  XPlan.certify (.pfa .two (.rader (.ct (.pfa .two (.pair 3)) (.pfa .two (.pair 3))))) 394 14176
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_395 : ∃ C : Circuit 395, C.Computes (fourierMatrix 395) ∧ C.size = 14121 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.ct .two .two))))))) 395 14121
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_397 : ∃ C : Circuit 397, C.Computes (fourierMatrix 397) ∧ C.size = 15791 :=
  XPlan.certify (.rader (.pfa (.ct .two .two) (.pfa (.ct (.pair 1) (.pair 1)) (.pair 5)))) 397 15791
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_398 : ∃ C : Circuit 398, C.Computes (fourierMatrix 398) ∧ C.size = 15200 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.ct (.pair 1) (.pair 1)) (.pair 5))))) 398 15200
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_399 : ∃ C : Circuit 399, C.Computes (fourierMatrix 399) ∧ C.size = 9701 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.pair 3) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 399 9701
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_401 : ∃ C : Circuit 401, C.Computes (fourierMatrix 401) ∧ C.size = 12803 :=
  XPlan.certify (.rader (.ct (.pfa (.ct .two .two) (.pair 2)) (.pfa (.ct .two .two) (.pair 2)))) 401 12803
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_402 : ∃ C : Circuit 402, C.Computes (fourierMatrix 402) ∧ C.size = 13816 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 1) (.pair 5)))))) 402 13816
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_403 : ∃ C : Circuit 403, C.Computes (fourierMatrix 403) ∧ C.size = 11830 :=
  XPlan.certify (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))) 403 11830
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_404 : ∃ C : Circuit 404, C.Computes (fourierMatrix 404) ∧ C.size = 11641 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.ct (.pfa .two (.pair 2)) (.pfa .two (.pair 2))))) 404 11641
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_406 : ∃ C : Circuit 406, C.Computes (fourierMatrix 406) ∧ C.size = 11128 :=
  XPlan.certify (.pfa .two (.pfa (.pair 3) (.rader (.pfa (.ct .two .two) (.pair 3))))) 406 11128
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_407 : ∃ C : Circuit 407, C.Computes (fourierMatrix 407) ∧ C.size = 11601 :=
  XPlan.certify (.pfa (.pair 5) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))) 407 11601
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_408 : ∃ C : Circuit 408, C.Computes (fourierMatrix 408) ∧ C.size = 7247 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.ct .two (.ct .two .two)) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 408 7247
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_409 : ∃ C : Circuit 409, C.Computes (fourierMatrix 409) ∧ C.size = 15311 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.ct .two (.ct .two .two)) (.rader (.ct .two (.ct .two (.ct .two .two))))))) 409 15311
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_410 : ∃ C : Circuit 410, C.Computes (fourierMatrix 410) ∧ C.size = 9928 :=
  XPlan.certify (.pfa .two (.pfa (.pair 2) (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two)))))) 410 9928
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_411 : ∃ C : Circuit 411, C.Computes (fourierMatrix 411) ∧ C.size = 14233 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.ct .two (.ct .two .two)) (.rader (.ct .two (.ct .two (.ct .two .two))))))) 411 14233
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_412 : ∃ C : Circuit 412, C.Computes (fourierMatrix 412) ∧ C.size = 14099 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 1) (.rader (.ct .two (.ct .two (.ct .two .two)))))))) 412 14099
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_413 : ∃ C : Circuit 413, C.Computes (fourierMatrix 413) ∧ C.size = 20339 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa .two (.rader (.pfa (.ct .two .two) (.pair 3)))))) 413 20339
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_415 : ∃ C : Circuit 415, C.Computes (fourierMatrix 415) ∧ C.size = 18737 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa .two (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))))) 415 18737
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_416 : ∃ C : Circuit 416, C.Computes (fourierMatrix 416) ∧ C.size = 7293 :=
  XPlan.certify (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.ct .two (.ct .two (.ct .two (.ct .two .two))))) 416 7293
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_417 : ∃ C : Circuit 417, C.Computes (fourierMatrix 417) ∧ C.size = 23690 :=
  XPlan.certify (.pfa (.pair 1) (.bluestein 139 (.ct (.pfa (.pair 1) (.ct .two .two)) (.pfa (.pair 1) (.ct .two (.ct .two .two)))))) 417 23690
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_418 : ∃ C : Circuit 418, C.Computes (fourierMatrix 418) ∧ C.size = 11160 :=
  XPlan.certify (.pfa .two (.pfa (.pair 5) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 418 11160
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_419 : ∃ C : Circuit 419, C.Computes (fourierMatrix 419) ∧ C.size = 23157 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 5) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))))) 419 23157
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_421 : ∃ C : Circuit 421, C.Computes (fourierMatrix 421) ∧ C.size = 14763 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pfa (.pair 2) (.pair 3))))) 421 14763
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_422 : ∃ C : Circuit 422, C.Computes (fourierMatrix 422) ∧ C.size = 14136 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 1) (.pfa (.pair 2) (.pair 3)))))) 422 14136
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_423 : ∃ C : Circuit 423, C.Computes (fourierMatrix 423) ∧ C.size = 20030 :=
  XPlan.certify (.pfa (.ct (.pair 1) (.pair 1)) (.bluestein 47 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 423 20030
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_424 : ∃ C : Circuit 424, C.Computes (fourierMatrix 424) ∧ C.size = 13401 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 424 13401
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_425 : ∃ C : Circuit 425, C.Computes (fourierMatrix 425) ∧ C.size = 9227 :=
  XPlan.certify (.pfa (.rader (.ct .two (.ct .two (.ct .two .two)))) (.ct (.pair 2) (.pair 2))) 425 9227
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_426 : ∃ C : Circuit 426, C.Computes (fourierMatrix 426) ∧ C.size = 13040 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 2) (.pair 3)))))) 426 13040
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_427 : ∃ C : Circuit 427, C.Computes (fourierMatrix 427) ∧ C.size = 11937 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pair 2))))) 427 11937
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_428 : ∃ C : Circuit 428, C.Computes (fourierMatrix 428) ∧ C.size = 24283 :=
  XPlan.certify (.pfa (.ct .two .two) (.bluestein 107 (.ct (.pfa .two (.pair 1)) (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1)))))) 428 24283
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_429 : ∃ C : Circuit 429, C.Computes (fourierMatrix 429) ∧ C.size = 10543 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.pair 5) (.rader (.pfa (.pair 1) (.ct .two .two))))) 429 10543
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_430 : ∃ C : Circuit 430, C.Computes (fourierMatrix 430) ∧ C.size = 12184 :=
  XPlan.certify (.pfa .two (.pfa (.pair 2) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3)))))) 430 12184
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_431 : ∃ C : Circuit 431, C.Computes (fourierMatrix 431) ∧ C.size = 25229 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 2) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3))))))) 431 25229
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_433 : ∃ C : Circuit 433, C.Computes (fourierMatrix 433) ∧ C.size = 12819 :=
  XPlan.certify (.rader (.ct (.pfa .two (.pair 1)) (.ct (.pfa .two (.pair 1)) (.pfa (.pair 1) (.ct .two .two))))) 433 12819
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_434 : ∃ C : Circuit 434, C.Computes (fourierMatrix 434) ∧ C.size = 11376 :=
  XPlan.certify (.pfa .two (.pfa (.pair 3) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2)))))) 434 11376
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_435 : ∃ C : Circuit 435, C.Computes (fourierMatrix 435) ∧ C.size = 11753 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.pair 2) (.rader (.pfa (.ct .two .two) (.pair 3))))) 435 11753
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_436 : ∃ C : Circuit 436, C.Computes (fourierMatrix 436) ∧ C.size = 11553 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.ct (.pfa .two (.pair 1)) (.pfa .two (.ct (.pair 1) (.pair 1)))))) 436 11553
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_437 : ∃ C : Circuit 437, C.Computes (fourierMatrix 437) ∧ C.size = 16495 :=
  XPlan.certify (.pfa (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))) (.pair 11)) 437 16495
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_438 : ∃ C : Circuit 438, C.Computes (fourierMatrix 438) ∧ C.size = 10552 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.ct (.pfa .two (.pair 1)) (.pfa (.pair 1) (.ct .two .two)))))) 438 10552
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_439 : ∃ C : Circuit 439, C.Computes (fourierMatrix 439) ∧ C.size = 21981 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.rader (.ct (.pfa .two (.pair 1)) (.pfa (.pair 1) (.ct .two .two))))))) 439 21981
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_442 : ∃ C : Circuit 442, C.Computes (fourierMatrix 442) ∧ C.size = 10374 :=
  XPlan.certify (.pfa .two (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 442 10374
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_443 : ∃ C : Circuit 443, C.Computes (fourierMatrix 443) ∧ C.size = 21633 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.ct .two (.ct .two (.ct .two .two))))))) 443 21633
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_444 : ∃ C : Circuit 444, C.Computes (fourierMatrix 444) ∧ C.size = 9995 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1)))))) 444 9995
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_445 : ∃ C : Circuit 445, C.Computes (fourierMatrix 445) ∧ C.size = 15811 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa (.ct .two (.ct .two .two)) (.pair 5)))) 445 15811
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_446 : ∃ C : Circuit 446, C.Computes (fourierMatrix 446) ∧ C.size = 20216 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1)))))))) 446 20216
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_447 : ∃ C : Circuit 447, C.Computes (fourierMatrix 447) ∧ C.size = 19705 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.ct .two .two) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))))) 447 19705
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_449 : ∃ C : Circuit 449, C.Computes (fourierMatrix 449) ∧ C.size = 14223 :=
  XPlan.certify (.rader (.pfa (.pair 3) (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 449 14223
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_451 : ∃ C : Circuit 451, C.Computes (fourierMatrix 451) ∧ C.size = 13225 :=
  XPlan.certify (.pfa (.pair 5) (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two))))) 451 13225
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_452 : ∃ C : Circuit 452, C.Computes (fourierMatrix 452) ∧ C.size = 12597 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa (.pair 3) (.ct .two (.ct .two (.ct .two .two)))))) 452 12597
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_453 : ∃ C : Circuit 453, C.Computes (fourierMatrix 453) ∧ C.size = 14627 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 1) (.ct (.pair 2) (.pair 2)))))) 453 14627
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_454 : ∃ C : Circuit 454, C.Computes (fourierMatrix 454) ∧ C.size = 25424 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.rader (.pfa (.pair 3) (.ct .two (.ct .two (.ct .two .two)))))))) 454 25424
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_455 : ∃ C : Circuit 455, C.Computes (fourierMatrix 455) ∧ C.size = 10309 :=
  XPlan.certify (.pfa (.pair 2) (.pfa (.pair 3) (.rader (.pfa (.pair 1) (.ct .two .two))))) 455 10309
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_456 : ∃ C : Circuit 456, C.Computes (fourierMatrix 456) ∧ C.size = 9613 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 456 9613
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_457 : ∃ C : Circuit 457, C.Computes (fourierMatrix 457) ∧ C.size = 20139 :=
  XPlan.certify (.rader (.pfa (.pair 1) (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa .two (.ct (.pair 1) (.pair 1))))))) 457 20139
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_458 : ∃ C : Circuit 458, C.Computes (fourierMatrix 458) ∧ C.size = 19344 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))))) 458 19344
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_459 : ∃ C : Circuit 459, C.Computes (fourierMatrix 459) ∧ C.size = 9413 :=
  XPlan.certify (.pfa (.rader (.ct .two (.ct .two (.ct .two .two)))) (.ct (.pair 1) (.ct (.pair 1) (.pair 1)))) 459 9413
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_461 : ∃ C : Circuit 461, C.Computes (fourierMatrix 461) ∧ C.size = 28527 :=
  XPlan.certify (.rader (.pfa (.ct .two .two) (.pfa (.pair 2) (.pair 11)))) 461 28527
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_463 : ∃ C : Circuit 463, C.Computes (fourierMatrix 463) ∧ C.size = 20729 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 1) (.pfa (.pair 3) (.pair 5))))) 463 20729
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_464 : ∃ C : Circuit 464, C.Computes (fourierMatrix 464) ∧ C.size = 11421 :=
  XPlan.certify (.pfa (.ct .two (.ct .two (.ct .two .two))) (.rader (.pfa (.ct .two .two) (.pair 3)))) 464 11421
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_465 : ∃ C : Circuit 465, C.Computes (fourierMatrix 465) ∧ C.size = 12007 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.pair 2) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2)))))) 465 12007
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_466 : ∃ C : Circuit 466, C.Computes (fourierMatrix 466) ∧ C.size = 22904 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa (.ct .two .two) (.pair 3)))))) 466 22904
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_467 : ∃ C : Circuit 467, C.Computes (fourierMatrix 467) ∧ C.size = 30630 :=
  XPlan.certify (.bluestein 467 (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))))) 467 30630
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_468 : ∃ C : Circuit 468, C.Computes (fourierMatrix 468) ∧ C.size = 8905 :=
  XPlan.certify (.pfa (.ct .two .two) (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa (.pair 1) (.ct .two .two))))) 468 8905
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_469 : ∃ C : Circuit 469, C.Computes (fourierMatrix 469) ∧ C.size = 17615 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa .two (.pfa (.pair 1) (.pair 5))))) 469 17615
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_470 : ∃ C : Circuit 470, C.Computes (fourierMatrix 470) ∧ C.size = 22266 :=
  XPlan.certify (.pfa .two (.pfa (.pair 2) (.bluestein 47 (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))) 470 22266
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_471 : ∃ C : Circuit 471, C.Computes (fourierMatrix 471) ∧ C.size = 17093 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two))))))) 471 17093
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_472 : ∃ C : Circuit 472, C.Computes (fourierMatrix 472) ∧ C.size = 21719 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa .two (.rader (.pfa (.ct .two .two) (.pair 3)))))) 472 21719
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_473 : ∃ C : Circuit 473, C.Computes (fourierMatrix 473) ∧ C.size = 15819 :=
  XPlan.certify (.pfa (.pair 5) (.rader (.pfa .two (.pfa (.pair 1) (.pair 3))))) 473 15819
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_474 : ∃ C : Circuit 474, C.Computes (fourierMatrix 474) ∧ C.size = 16408 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa .two (.pfa (.pair 1) (.rader (.pfa (.pair 1) (.ct .two .two)))))))) 474 16408
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_475 : ∃ C : Circuit 475, C.Computes (fourierMatrix 475) ∧ C.size = 11889 :=
  XPlan.certify (.pfa (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))) (.ct (.pair 2) (.pair 2))) 475 11889
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_476 : ∃ C : Circuit 476, C.Computes (fourierMatrix 476) ∧ C.size = 9795 :=
  XPlan.certify (.pfa (.ct .two .two) (.pfa (.pair 3) (.rader (.ct .two (.ct .two (.ct .two .two)))))) 476 9795
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_477 : ∃ C : Circuit 477, C.Computes (fourierMatrix 477) ∧ C.size = 16103 :=
  XPlan.certify (.pfa (.ct (.pair 1) (.pair 1)) (.rader (.pfa (.ct .two .two) (.rader (.pfa (.pair 1) (.ct .two .two)))))) 477 16103
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_478 : ∃ C : Circuit 478, C.Computes (fourierMatrix 478) ∧ C.size = 19832 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.pfa (.pair 3) (.rader (.ct .two (.ct .two (.ct .two .two)))))))) 478 19832
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_479 : ∃ C : Circuit 479, C.Computes (fourierMatrix 479) ∧ C.size = 30654 :=
  XPlan.certify (.bluestein 479 (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))))) 479 30654
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_481 : ∃ C : Circuit 481, C.Computes (fourierMatrix 481) ∧ C.size = 13754 :=
  XPlan.certify (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.pfa (.ct .two .two) (.ct (.pair 1) (.pair 1))))) 481 13754
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_482 : ∃ C : Circuit 482, C.Computes (fourierMatrix 482) ∧ C.size = 13472 :=
  XPlan.certify (.pfa .two (.rader (.pfa (.pair 1) (.pfa (.pair 2) (.ct .two (.ct .two (.ct .two .two))))))) 482 13472
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_485 : ∃ C : Circuit 485, C.Computes (fourierMatrix 485) ∧ C.size = 12123 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.pfa (.pair 1) (.ct .two (.ct .two (.ct .two (.ct .two .two))))))) 485 12123
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_487 : ∃ C : Circuit 487, C.Computes (fourierMatrix 487) ∧ C.size = 17177 :=
  XPlan.certify (.rader (.pfa .two (.ct (.pair 1) (.ct (.pair 1) (.ct (.pair 1) (.ct (.pair 1) (.pair 1))))))) 487 17177
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_488 : ∃ C : Circuit 488, C.Computes (fourierMatrix 488) ∧ C.size = 12065 :=
  XPlan.certify (.pfa (.ct .two (.ct .two .two)) (.rader (.pfa (.pair 1) (.pfa (.ct .two .two) (.pair 2))))) 488 12065
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_489 : ∃ C : Circuit 489, C.Computes (fourierMatrix 489) ∧ C.size = 15251 :=
  XPlan.certify (.pfa (.pair 1) (.rader (.pfa .two (.ct (.pair 1) (.ct (.pair 1) (.ct (.pair 1) (.pair 1))))))) 489 15251
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_491 : ∃ C : Circuit 491, C.Computes (fourierMatrix 491) ∧ C.size = 20825 :=
  XPlan.certify (.rader (.pfa .two (.pfa (.pair 2) (.ct (.pair 3) (.pair 3))))) 491 20825
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_492 : ∃ C : Circuit 492, C.Computes (fourierMatrix 492) ∧ C.size = 11479 :=
  XPlan.certify (.pfa (.pair 1) (.pfa (.ct .two .two) (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two)))))) 492 11479
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_493 : ∃ C : Circuit 493, C.Computes (fourierMatrix 493) ∧ C.size = 15294 :=
  XPlan.certify (.pfa (.rader (.ct .two (.ct .two (.ct .two .two)))) (.rader (.pfa (.ct .two .two) (.pair 3)))) 493 15294
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_494 : ∃ C : Circuit 494, C.Computes (fourierMatrix 494) ∧ C.size = 13234 :=
  XPlan.certify (.pfa .two (.pfa (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.pfa .two (.ct (.pair 1) (.pair 1)))))) 494 13234
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_496 : ∃ C : Circuit 496, C.Computes (fourierMatrix 496) ∧ C.size = 11615 :=
  XPlan.certify (.pfa (.ct .two (.ct .two (.ct .two .two))) (.rader (.pfa .two (.pfa (.pair 1) (.pair 2))))) 496 11615
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_497 : ∃ C : Circuit 497, C.Computes (fourierMatrix 497) ∧ C.size = 16799 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.pfa .two (.pfa (.pair 2) (.pair 3))))) 497 16799
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_498 : ∃ C : Circuit 498, C.Computes (fourierMatrix 498) ∧ C.size = 21920 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.rader (.pfa .two (.rader (.pfa (.pair 2) (.ct .two (.ct .two .two)))))))) 498 21920
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_499 : ∃ C : Circuit 499, C.Computes (fourierMatrix 499) ∧ C.size = 30694 :=
  XPlan.certify (.bluestein 499 (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))))) 499 30694
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_501 : ∃ C : Circuit 501, C.Computes (fourierMatrix 501) ∧ C.size = 30698 :=
  XPlan.certify (.bluestein 501 (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))))) 501 30698
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_502 : ∃ C : Circuit 502, C.Computes (fourierMatrix 502) ∧ C.size = 18312 :=
  XPlan.certify (.pfa .two (.rader (.pfa .two (.ct (.pair 2) (.ct (.pair 2) (.pair 2)))))) 502 18312
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_503 : ∃ C : Circuit 503, C.Computes (fourierMatrix 503) ∧ C.size = 30702 :=
  XPlan.certify (.bluestein 503 (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))))) 503 30702
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_505 : ∃ C : Circuit 505, C.Computes (fourierMatrix 505) ∧ C.size = 15839 :=
  XPlan.certify (.pfa (.pair 2) (.rader (.ct (.pfa .two (.pair 2)) (.pfa .two (.pair 2))))) 505 15839
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_507 : ∃ C : Circuit 507, C.Computes (fourierMatrix 507) ∧ C.size = 12938 :=
  XPlan.certify (.pfa (.pair 1) (.ct (.rader (.pfa (.pair 1) (.ct .two .two))) (.rader (.pfa (.pair 1) (.ct .two .two))))) 507 12938
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_508 : ∃ C : Circuit 508, C.Computes (fourierMatrix 508) ∧ C.size = 15899 :=
  XPlan.certify (.pfa (.ct .two .two) (.rader (.pfa .two (.pfa (.pair 3) (.ct (.pair 1) (.pair 1)))))) 508 15899
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_509 : ∃ C : Circuit 509, C.Computes (fourierMatrix 509) ∧ C.size = 30714 :=
  XPlan.certify (.bluestein 509 (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two (.ct .two .two)))))))))) 509 30714
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_510 : ∃ C : Circuit 510, C.Computes (fourierMatrix 510) ∧ C.size = 10168 :=
  XPlan.certify (.pfa .two (.pfa (.pair 1) (.pfa (.pair 2) (.rader (.ct .two (.ct .two (.ct .two .two))))))) 510 10168
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem xdft_511 : ∃ C : Circuit 511, C.Computes (fourierMatrix 511) ∧ C.size = 13941 :=
  XPlan.certify (.pfa (.pair 3) (.rader (.ct (.pfa .two (.pair 1)) (.pfa (.pair 1) (.ct .two .two))))) 511 13941
    (by decide +kernel) (by decide +kernel) (by decide +kernel)

end FdrsFormal.NumberTheory.Characters.FourierCircuit.SearchCertificatesExt
