/-
Copyright 2026 Hyphaeic SPC.

Licensed under the Hyphaeic Public License, Version 1.0 (the
"License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

https://github.com/hyphaeic/hpl

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.

# Runtime Algebra Definition

This file defines the runtime operator algebra ℜ_N generated by
diagonal gates, Dirichlet transforms, and the Tick shift.

## Mathematical Content (fdrs.md Phase 4)

**Runtime Algebra ℜ_N**: The algebra generated by:
- Diagonal gates M_g (pointwise multiplication by g)
- Dirichlet transforms T_a
- Tick shift operator T (from Operations)

**Guarded Instruction Form**: `Instr(g, a) = M_g T_a`

**Key Result**: Runtime locality - all operations have bounded-touch implementation.

## References

- fdrs.md, Phase 4, Section 4.4 (Runtime Algebra)
- fdrs.md, Phase 4, Section 4.5 (Locality Contract)
-/

import FdrsFormal.Core
import FdrsFormal.Operations
import FdrsFormal.NumberTheory
import FdrsFormal.Integration.Programs.IntegerSemantics

namespace FdrsFormal.Integration.RuntimeAlgebra

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-!
## Diagonal Gates
-/

/--
Diagonal gate: pointwise multiplication by a function g.

**fdrs.md**: `M_g(f)(n) = g(n) · f(n)`
-/
def diagonalGate (g : ℕ → ℝ) (f : ℕ → V) : ℕ → V :=
  fun n => g n • f n

/--
Diagonal gates compose pointwise.
-/
theorem diagonalGate_compose (g₁ g₂ : ℕ → ℝ) (f : ℕ → V) :
    diagonalGate g₁ (diagonalGate g₂ f) = diagonalGate (g₁ * g₂) f := by
  ext n
  simp only [diagonalGate, Pi.mul_apply, mul_smul]

/-!
## Guarded Instructions
-/

/--
Guarded instruction: composition of diagonal gate and Dirichlet transform.

**fdrs.md**: `Instr(g, a) = M_g T_a`
-/
def guardedInstruction (g : ℕ → ℝ) (a : ℕ) (f : ℕ → V) : ℕ → V :=
  diagonalGate g (Integration.Programs.integerProgram a f)

/--
Identity instruction is `Instr(1, 1)`.
-/
theorem guardedInstruction_identity (f : ℕ → V) :
    guardedInstruction 1 1 f = f := by
  unfold guardedInstruction
  rw [Integration.Programs.integerProgram_one]
  ext n
  simp only [diagonalGate, Pi.one_apply, one_smul]

/--
Guarded instructions compose: `Instr(g₁, a₁) ∘ Instr(g₂, a₂) = Instr(g', a₁·a₂)`
where `g'(m) = if a₁ | m then g₁(m) · g₂(m/a₁) else 0`.

This is the key algebraic identity ensuring closure under composition.
-/
theorem guardedInstruction_comp (g₁ g₂ : ℕ → ℝ) (a₁ a₂ : ℕ) (ha₁ : a₁ ≠ 0) (f : ℕ → V) :
    guardedInstruction g₁ a₁ (guardedInstruction g₂ a₂ f) =
    guardedInstruction (fun m => if a₁ ∣ m then g₁ m * g₂ (m / a₁) else 0) (a₁ * a₂) f := by
  ext m
  simp only [guardedInstruction, diagonalGate, Integration.Programs.integerProgram]
  by_cases ha₁m : a₁ ∣ m
  · -- a₁ | m
    simp only [ha₁m, ↓reduceIte]
    by_cases ha₂m : a₂ ∣ (m / a₁)
    · -- a₂ | m/a₁, so a₁*a₂ | m
      have hab : (a₁ * a₂) ∣ m := Nat.mul_dvd_of_dvd_div ha₁m ha₂m
      simp only [hab, ha₂m, ↓reduceIte, mul_smul, Nat.div_div_eq_div_mul]
    · -- a₂ ∤ m/a₁, so a₁*a₂ ∤ m
      have hab : ¬((a₁ * a₂) ∣ m) := by
        intro h
        exact ha₂m ((Nat.dvd_div_iff_mul_dvd ha₁m).mpr (mul_comm a₁ a₂ ▸ h))
      simp only [hab, ha₂m, ↓reduceIte, smul_zero]
  · -- a₁ ∤ m, so a₁*a₂ ∤ m
    have hab : ¬((a₁ * a₂) ∣ m) := fun h => ha₁m (dvd_trans (dvd_mul_right a₁ a₂) h)
    simp only [ha₁m, hab, ↓reduceIte, zero_smul, smul_zero]

/-!
## Runtime Algebra Structure
-/

/--
The runtime algebra is the span of guarded instructions.

**fdrs.md**: ℜ_N = span{Instr(g, a) : g ∈ Gates, a ∈ ℕ}
-/
structure RuntimeAlgebra where
  /-- Coefficient function for each (gate, integer) pair -/
  coeffs : (ℕ → ℝ) × ℕ → ℝ
  /-- Finite support -/
  finite_support : Set.Finite {p | coeffs p ≠ 0}

/--
Application of runtime algebra element to a function.

Note: Full implementation requires summing over the finite support.
This is a placeholder that returns zero - proper implementation would
use Finset.sum over the finite support.
-/
noncomputable def RuntimeAlgebra.apply (R : RuntimeAlgebra) (f : ℕ → V) : ℕ → V :=
  R.finite_support.toFinset.sum fun p => R.coeffs p • guardedInstruction p.1 p.2 f

/-!
## Markov Locality
-/

/--
Runtime locality: each guarded instruction `Instr(g, a)` depends on at most
`a` positions: `(Instr(g, a) f)(m)` depends only on `f(m/a)` when `a | m`.

**fdrs.md**: The Markov locality theorem states that augmented state
(position + finite memory) suffices for all runtime operations.
-/
theorem runtime_locality (g : ℕ → ℝ) (a : ℕ) (f₁ f₂ : ℕ → V) (m : ℕ)
    (h : ∀ n, a ∣ n → f₁ (n / a) = f₂ (n / a)) :
    guardedInstruction g a f₁ m = guardedInstruction g a f₂ m := by
  simp only [guardedInstruction, diagonalGate, Integration.Programs.integerProgram]
  by_cases ha : a ∣ m
  · rw [h m ha]
  · simp [ha]

/--
Closure under composition: composing two guarded instructions gives a guarded
instruction with product integer and composed gate.
-/
theorem runtimeAlgebra_closed_composition (g₁ g₂ : ℕ → ℝ) (a₁ a₂ : ℕ)
    (ha₁ : a₁ ≠ 0) (f : ℕ → V) :
    guardedInstruction g₁ a₁ (guardedInstruction g₂ a₂ f) =
    guardedInstruction (fun m => if a₁ ∣ m then g₁ m * g₂ (m / a₁) else 0) (a₁ * a₂) f :=
  guardedInstruction_comp g₁ g₂ a₁ a₂ ha₁ f

end FdrsFormal.Integration.RuntimeAlgebra
