/-
Copyright 2026 Hyphaeic SPC.

Licensed under the Hyphaeic Public License, Version 1.0 (the
"License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

https://github.com/hyphaeic/hpl

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.

# Dual Filtrations

This file defines the additive (cylinder) and multiplicative (valuation)
filtration structures.

## Mathematical Content (fdrs.md Phase 4)

**Additive Filtration**: Based on `n mod B_L` (cylinder/residue classes)
**Multiplicative Filtration**: Based on `v_P(n)` (P-adic valuation vector)

**Key Insight**: Dirichlet transforms are local on the valuation lattice,
not on cylinders. This is the "dual filtration" structure.

**Factorization Lens**: `Λ_P(n) = (u_P(n), v_P(n))` where
- u_P(n) is the P-smooth part coprime to P-complement
- v_P(n) is the valuation vector

## References

- fdrs.md, Phase 4, Section 4.6 (Dual Filtrations)
- fdrs.md, Phase 4, Theorem D (Dual Filtrations)
-/

import FdrsFormal.Core
import FdrsFormal.Topology
import FdrsFormal.NumberTheory

namespace FdrsFormal.Integration.DualFiltrations

/-- Block size at depth L: B_L = ∏_{i=0}^{L-1} b_i -/
def blockSize (b : ℕ → ℕ) : ℕ → ℕ
  | 0 => 1
  | n + 1 => blockSize b n * b n

/-!
## Additive (Cylinder) Filtration
-/

/--
Additive filtration level: residue classes mod B_L.

**fdrs.md**: σ-algebra ℱ^add_L generated by {n : n ≡ a (mod B_L)}
-/
def additiveFiltrationLevel (b : ℕ → ℕ) (L : ℕ) : Set (Set ℕ) :=
  {S | ∃ a : Fin (blockSize b L),
    S = {n : ℕ | (n : ZMod (blockSize b L)) = (a.val : ZMod (blockSize b L))}}

/--
Additive filtration covers ℕ: every natural number belongs to some residue class.

When the block size B_L > 0, every n ∈ ℕ belongs to the residue class [n mod B_L],
which is an element of the additive filtration at level L.
-/
theorem additiveFiltration_cylinder (b : ℕ → ℕ) (L : ℕ) (hpos : 0 < blockSize b L) :
    ∀ n : ℕ, ∃ S ∈ additiveFiltrationLevel b L, n ∈ S := by
  intro n
  refine ⟨_, ⟨⟨n % blockSize b L, Nat.mod_lt n hpos⟩, rfl⟩, ?_⟩
  simp only [Set.mem_setOf_eq]
  exact (ZMod.natCast_mod n (blockSize b L)).symm

/-!
## Multiplicative (Valuation) Filtration
-/

/--
Valuation vector at a finite set of primes P.

**fdrs.md**: `v_P(n) = (v_p(n))_{p ∈ P}` where v_p is p-adic valuation
-/
def valuationVector (P : Finset ℕ) (n : ℕ) : P → ℕ :=
  fun ⟨p, _⟩ => Nat.factorization n p

/--
P-smooth part: the P-power divisor of n.

**fdrs.md**: `n_P = ∏_{p ∈ P} p^{v_p(n)}`
-/
def smoothPart (P : Finset ℕ) (n : ℕ) : ℕ :=
  P.prod fun p => p ^ (Nat.factorization n p)

/--
P-rough part: n divided by P-smooth part.

**fdrs.md**: `u_P(n) = n / n_P` (coprime to all p ∈ P)
-/
def roughPart (P : Finset ℕ) (n : ℕ) : ℕ :=
  n / smoothPart P n

/--
Factorization lens: decomposition into smooth and rough parts.

**fdrs.md**: `Λ_P(n) = (u_P(n), v_P(n))`
-/
def factorizationLens (P : Finset ℕ) (n : ℕ) : ℕ × (P → ℕ) :=
  (roughPart P n, valuationVector P n)

/-- Helper: if m is coprime to each element, m is coprime to the product. -/
private lemma coprime_of_coprime_prod (m : ℕ) (s : Finset ℕ) (f : ℕ → ℕ)
    (h : ∀ x ∈ s, Nat.Coprime m (f x)) :
    Nat.Coprime m (s.prod f) := by
  induction s using Finset.induction with
  | empty => simp [Nat.Coprime]
  | insert a s' ha ih =>
    rw [Finset.prod_insert ha]
    apply Nat.Coprime.mul_right
    · exact h a (Finset.mem_insert_self a s')
    · exact ih (fun x hx => h x (Finset.mem_insert_of_mem hx))

/--
The smooth part divides n (each prime power divides n by factorization definition).

**Mathematical argument**: smoothPart P n = ∏_{p ∈ P} p^{v_p(n)}, where each p^{v_p(n)} | n.
The product of divisors of n also divides n when the divisors are coprime prime powers.

**Proof**: By induction on P. For the inductive step, use that:
1. Prime powers for distinct primes are coprime
2. Each p^{v_p(n)} | n by definition of factorization
3. Coprime divisors can be combined: if gcd(a,b)=1 and a|n and b|n, then ab|n
-/
theorem smoothPart_dvd (P : Finset ℕ) (hP : ∀ p ∈ P, Nat.Prime p) (n : ℕ) :
    smoothPart P n ∣ n := by
  by_cases hn : n = 0
  · simp [hn]
  · unfold smoothPart
    induction P using Finset.induction with
    | empty => simp
    | insert a s ha ih =>
      rw [Finset.prod_insert ha]
      apply Nat.Coprime.mul_dvd_of_dvd_of_dvd
      · -- Coprimality: a^(v_a(n)) is coprime to product over s
        apply Nat.Coprime.pow_left
        apply coprime_of_coprime_prod
        intro q hqs
        apply Nat.Coprime.pow_right
        apply (Nat.coprime_primes (hP a (Finset.mem_insert_self a s))
                                  (hP q (Finset.mem_insert_of_mem hqs))).mpr
        intro heq
        subst heq
        exact ha hqs
      · -- a^(v_a(n)) | n
        rw [(hP a (Finset.mem_insert_self a s)).pow_dvd_iff_le_factorization hn]
      · -- product over s | n (by IH)
        exact ih (fun p hp' => hP p (Finset.mem_insert_of_mem hp'))

/--
The smooth part captures exactly the p-adic valuation for p ∈ P.

**Mathematical argument**: smoothPart P n = ∏_{p ∈ P} p^{v_p(n)}, so v_p(smoothPart P n) = v_p(n)
for each p ∈ P (since the other prime powers are coprime to p).
-/
theorem smoothPart_valuation (P : Finset ℕ) (hP : ∀ p ∈ P, Nat.Prime p) (n : ℕ) (hn : n ≠ 0)
    (p : ℕ) (hp : p ∈ P) :
    (smoothPart P n).factorization p = n.factorization p := by
  unfold smoothPart
  have hprime := hP p hp
  -- Show each factor is nonzero
  have hne : ∀ q ∈ P, q ^ (n.factorization q) ≠ 0 := by
    intro q hq
    exact pow_ne_zero _ (Nat.Prime.ne_zero (hP q hq))
  rw [Nat.factorization_prod hne]
  simp only [Finsupp.coe_finset_sum, Finset.sum_apply]
  rw [Finset.sum_eq_single p]
  · -- Main term: p^{v_p(n)} contributes v_p(n)
    rw [Nat.factorization_pow, Finsupp.smul_apply, smul_eq_mul,
        Nat.Prime.factorization_self hprime, mul_one]
  · -- Other terms q ≠ p contribute 0 to v_p
    intro q hq hqp
    rw [Nat.factorization_pow, Finsupp.smul_apply, smul_eq_mul]
    -- p doesn't divide q (distinct primes are coprime, so neither divides the other)
    have hndvd : ¬(p ∣ q) := by
      have hcoprime : Nat.Coprime p q := (Nat.coprime_primes hprime (hP q hq)).mpr (Ne.symm hqp)
      exact hprime.coprime_iff_not_dvd.mp hcoprime
    rw [Nat.factorization_eq_zero_of_not_dvd hndvd]
    ring
  · -- p ∉ P case (contradiction with hp)
    intro hnp
    exact absurd hp hnp

/--
Rough part is coprime to all primes in P.

**Mathematical argument**: The rough part u_P(n) = n / n_P has all p-adic valuations for p ∈ P
removed (they're in the smooth part n_P). So v_p(u_P(n)) = 0 for all p ∈ P,
meaning u_P(n) is coprime to each p ∈ P.

**Proof**: By the divisibility property n = smoothPart P n * roughPart P n,
and the valuation property v_p(smoothPart P n) = v_p(n), we get
v_p(roughPart P n) = v_p(n) - v_p(smoothPart P n) = 0.
A number with v_p = 0 is coprime to p.
-/
theorem roughPart_coprime (P : Finset ℕ) (hP : ∀ p ∈ P, Nat.Prime p) (n : ℕ) (hn : n ≠ 0) :
    ∀ p ∈ P, Nat.Coprime (roughPart P n) p := by
  intro p hp
  unfold roughPart
  have hsmooth_dvd := smoothPart_dvd P hP n
  have hsmooth_pos : 0 < smoothPart P n := by
    apply Finset.prod_pos
    intro q hq
    exact Nat.pow_pos (Nat.Prime.pos (hP q hq))
  -- roughPart = n / smoothPart, and v_p(roughPart) = v_p(n) - v_p(smoothPart) = 0
  have hval := smoothPart_valuation P hP n hn p hp
  -- Coprime means p doesn't divide roughPart
  rw [Nat.coprime_comm, Nat.Prime.coprime_iff_not_dvd (hP p hp)]
  intro hdvd
  -- If p | (n / smoothPart), then v_p(n / smoothPart) ≥ 1
  have hrough_pos : 0 < n / smoothPart P n := by
    exact Nat.div_pos (Nat.le_of_dvd (Nat.pos_of_ne_zero hn) hsmooth_dvd) hsmooth_pos
  have hrough_ne : n / smoothPart P n ≠ 0 := Nat.pos_iff_ne_zero.mp hrough_pos
  have h1 : 1 ≤ (n / smoothPart P n).factorization p := by
    exact ((hP p hp).dvd_iff_one_le_factorization hrough_ne).mp hdvd
  -- But v_p(n / smoothPart) = v_p(n) - v_p(smoothPart) = 0
  have h2 : (n / smoothPart P n).factorization p = n.factorization p - (smoothPart P n).factorization p := by
    have := Nat.factorization_div hsmooth_dvd
    exact congr_fun (congrArg DFunLike.coe this) p
  rw [h2, hval] at h1
  omega

/--
Factorization lens is injective on positive integers.

**fdrs.md Def 46 (line 2502)**: Λ_P bijects ℕ⁺ → (P-free) × ℕ^P.

**Proof**: If roughPart and valuationVector agree, then smoothPart agrees
(since smoothPart = ∏_{p∈P} p^{v_p}), and n = roughPart * smoothPart.
-/
theorem factorizationLens_bijective (P : Finset ℕ) (hP : ∀ p ∈ P, Nat.Prime p)
    (n₁ n₂ : ℕ) (_hn₁ : n₁ ≠ 0) (_hn₂ : n₂ ≠ 0)
    (h : factorizationLens P n₁ = factorizationLens P n₂) : n₁ = n₂ := by
  simp only [factorizationLens, Prod.mk.injEq] at h
  obtain ⟨hrough, hval⟩ := h
  -- valuationVector equality implies smoothPart equality
  have hsmooth : smoothPart P n₁ = smoothPart P n₂ := by
    simp only [smoothPart]
    exact Finset.prod_congr rfl (fun p hp => by
      congr 1; exact congr_fun hval ⟨p, hp⟩)
  -- n = roughPart * smoothPart (by Nat.div_mul_cancel with smoothPart_dvd)
  have h1 : roughPart P n₁ * smoothPart P n₁ = n₁ := by
    show n₁ / smoothPart P n₁ * smoothPart P n₁ = n₁
    exact Nat.div_mul_cancel (smoothPart_dvd P hP n₁)
  have h2 : roughPart P n₂ * smoothPart P n₂ = n₂ := by
    show n₂ / smoothPart P n₂ * smoothPart P n₂ = n₂
    exact Nat.div_mul_cancel (smoothPart_dvd P hP n₂)
  calc n₁ = roughPart P n₁ * smoothPart P n₁ := h1.symm
    _ = roughPart P n₂ * smoothPart P n₂ := by rw [hrough, hsmooth]
    _ = n₂ := h2

/-!
## Dirichlet Locality on Valuation Lattice
-/

/--
Dirichlet transforms are local on the valuation lattice:
dividing n by a divisor d decomposes factorizations additively.
For each prime p, v_p(n/d) + v_p(d) = v_p(n).

**fdrs.md Key Insight**: T_a acts locally in valuation coordinates,
not in cylinder coordinates. When a is P-smooth and d | n, the
quotient n/d stays in the same P-free fiber as n.

-- fdrs.md lines 3633-3638, Corollary 22
-/
theorem dirichlet_valuation_local (P : Finset ℕ) (_hP : ∀ p ∈ P, Nat.Prime p)
    (n d : ℕ) (hn : n ≠ 0) (hd : d ≠ 0) (hdn : d ∣ n) :
    ∀ p ∈ P, (n / d).factorization p + d.factorization p = n.factorization p := by
  intro p _
  have h_nd_ne : n / d ≠ 0 := Nat.pos_iff_ne_zero.mp
    (Nat.div_pos (Nat.le_of_dvd (Nat.pos_of_ne_zero hn) hdn) (Nat.pos_of_ne_zero hd))
  have h_mul := Nat.factorization_mul hd h_nd_ne
  rw [Nat.mul_div_cancel' hdn] at h_mul
  -- h_mul : n.factorization = d.factorization + (n / d).factorization
  have h_at_p := congr_fun (congr_arg DFunLike.coe h_mul) p
  simp only [Finsupp.coe_add, Pi.add_apply] at h_at_p
  omega

/-!
## Theorem D: Dual Filtrations
-/

/--
**Theorem D (Dual Filtrations)**: The additive and multiplicative
filtrations provide complementary views of the integer structure.

**fdrs.md Theorem D**: The factorization lens Λ_P intertwines
cylinder locality (additive) with valuation locality (multiplicative).

**Core content**: For every positive integer n, the factorization lens
decomposes n = u · s where s = smoothPart P n = ∏_{p∈P} p^{v_p(n)} is the
P-smooth part and u = roughPart P n = n/s is coprime to all primes in P.
Moreover, this decomposition is compatible with divisibility: for d | n,
the valuation vectors satisfy v_P(n/d) + v_P(d) = v_P(n).
-/
theorem dual_filtrations (_b : ℕ → ℕ) (_hb : ∀ i, 2 ≤ _b i)
    (P : Finset ℕ) (hP : ∀ p ∈ P, Nat.Prime p) :
    (∀ n : ℕ, n ≠ 0 →
      roughPart P n * smoothPart P n = n ∧
      (∀ p ∈ P, Nat.Coprime (roughPart P n) p)) ∧
    (∀ n d : ℕ, n ≠ 0 → d ≠ 0 → d ∣ n →
      ∀ p ∈ P, (n / d).factorization p + d.factorization p = n.factorization p) := by
  constructor
  · intro n hn
    exact ⟨Nat.div_mul_cancel (smoothPart_dvd P hP n),
           roughPart_coprime P hP n hn⟩
  · intro n d hn hd hdn
    exact dirichlet_valuation_local P hP n d hn hd hdn

end FdrsFormal.Integration.DualFiltrations
