/-
Topology Filtration - σ-algebra filtration

Filtration of σ-algebras generated by cylinder sets.

## Key Results
- Definition of cylinderAlgebra (ℱ_L)
- Monotone nesting ℱ_L ⊆ ℱ_{L+1}
- Cylinder measurability
- Limit generates Borel σ-algebra

## References
- fdrs.md Phase 1 Fragment 3
- Paper (external draft): Measurable structure
-/

import FdrsFormal.Topology.Filtration.Definition
